### ISSUE TITLE
deploy prefixes service with "kontena" if version is 2 instead of '2'

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1002]
```
version: 2
name: myproject

services:
  cassandra-node:
```

becomes: `kontena-myproject-cassandra-node`

```
version: '2'
name: myproject

services:
  cassandra-node:
```

becomes: `myproject-cassandra-node`

This is kinda weird from UX point of view.

**Comment by nevalla** [comment]
This is definitely a bug. However #993 resolved also this issue.
