### ISSUE TITLE
Cli: grid logs --tail throws error

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1006]
It seems that current master (upcoming 0.15.2) has some kind of regression when logs are tailed:

```
/Users/jari/.rvm/gems/ruby-2.3.1/gems/kontena-cli-0.15.2/lib/kontena/cli/helpers/log_helper.rb:19:in `stream_logs': undefined local variable or method `token' for #<Kontena::Cli::Grids::LogsCommand:0x007f81b510da90> (NameError)
```

**Comment by SpComb** [comment]
Argh, I can't believe I didn't catch this. Must apply to the `kontena grid logs --tail` command only, and I missed that. Needs better test coverage :(

It'd be fixed in #1001, but I'll submit something smaller for use in 0.15.2.
