### ISSUE TITLE
kontena service show clips over 60 char env variables

### ISSUE THREAD

**Issue by timolehto** [kontena/kontena#1014]
e.g.

```
kontena service show localgyver-registry
localgyver/localgyver-registry:
--SNIP--
  env: 
    - KONTENA_LB_VIRTUAL_HOSTS=kontena-registry.localgyve...
```

Would be nice to have the envs printed out in full so that one don't need to issue yet another command to check the values. Or even a bit larger say 80 char limit would solve this in this particular case, but really I don't understand why must there be a limit at all..

**Comment by dsmiley** [comment]
me to.  Seems to be 50 chars for the value.
