### ISSUE TITLE
kontena grid logs -t raises if there are no logs

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1025]
```
$ kontena grid logs -t
undefined method `colorize' for nil:NilClass (NoMethodError)
```

(usecase: showing logs from the beginning of an automated kontena setup)

**Comment by SpComb** [comment]
Quick testing with 0.15.1, 0.15.2 and master using `kontena grid create logs-test` and `kontena grid logs -t` seems to behave correctly.

It this with `kontena version` 0.15.2 of the cli/master or earlier? Does `kontena grid logs` without the `--tail` also raise a similar error for the same logs? Can you give the `DEBUG=1 kontena grid logs -t` output with the traceback?

Not entirely sure what this is, I assume it's from the `log['name'].colorize(color)`. With the current code it wold mean that there was something parseable as JSON on the wire that wasn't actually a ContainerLog JSON object. Or there's a ContainerLog without a name on the server.

**Comment by jakolehm** [comment]
Let's reopen if this problem pops-up again.
