### ISSUE TITLE
Container can be deleted without kontena being notified on Docker for Mac 

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1029]
Service will stuck in `deleting...`

Fix: restart agent

**Comment by jnummelin** [comment]
Happen to remember which version of Kontena was running at the time? There was a fix to docker event stream in 0.15.3 which might explain this.

**Comment by matti** [comment]
I'm pretty sure that this is still in 0.15.3. I'll try to post here when I see this again (with 0.15.4+)

**Comment by nevalla** [comment]
Should be fixed in #1289
