### ISSUE TITLE
Node evacuate

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1030]
It should be possible to "evacuate" a node for example before doing maintenance work (or before terminating a node). Evacuate could just disable node from accepting any new services and reschedule stateless services to different nodes .

**Comment by jakolehm** [comment]
It should also stop service instances that cannot be moved.

**Comment by SpComb** [comment]
Blocking on #1873

**Comment by SpComb** [comment]
@jnummelin still working on this (assigned), or bump to 1.3.0?

**Comment by jnummelin** [comment]
I did have a poke around this BEFORE #1873 got merged. Most likely it will be easier to start over again. So not really working on this currently. I'll un-assign it for now.
