### ISSUE TITLE
Add a default affinity rule for a grid

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#1032]
it’d be nice if there was, say a special label that Kontena interpreted as the node being ineligible for automatic assignment.  It would take an affinity rule to get services on the node in question.  Or another way to view this, as the title suggests, is for the grid to have a default affinity rule which one might set to something like `label!=reserved=true`  Assuming one put a reserved=true label on certain nodes.  Perhaps this particular suggested affinity rule might even be the default, so I wouldn't need to set my grid default affinity rule once I know I want to reserve some nodes.  Otherwise, services created beforehand wouldn't know they shouldn't migrate to these reserved nodes.

**Comment by jnummelin** [comment]
Sounds like a good idea. Kinda relates to #1030

**Comment by jnummelin** [comment]
Closed in #1564
