### ISSUE TITLE
Document how logs are collected and how they can be streamed out of Kontena

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#1038]
The general process should be documented and some info how logs are stored so that users can stream them out of Kontena to some archive or analysis system. (Splunk, ELK, ...)

https://github.com/kontena/kontena-log-archiver

**Comment by otisg** [comment]
Is kontena-log-archiver still the way to go?
Or let me ask more specific questions.

1. If I want to ship logs to ELK (or hosted log management service with ES API, like Sematext Logsene), how should that be done these days, with or without kontena-log-archiver?
2. Could I simply use a log shipper that knows how to get logs via the Docker API, such as https://github.com/sematext/sematext-agent-docker or does Kontena prefer Docker API not to be used?
Thanks!

**Comment by megastef** [comment]
I would like to add one more question for log collection via Docker API: 

How to define in Kontena global services, which deploys a container to every node? 
See e.g. this thread, resulting in global Swarm services: https://github.com/docker/swarm/issues/601

We could then use such global services to deploy Sematext Docker Agent to all Kontena nodes.

**Comment by SpComb** [comment]
> How to define in Kontena global services, which deploys a container to every node?

Use [`--deploy-strategy daemon`](https://kontena.io/docs/using-kontena/deploy.html#daemon)

**Comment by jnummelin** [comment]
> Is kontena-log-archiver still the way to go?

That's one way to do it. The referenced GitHub repo should be considered more like an example.

> Could I simply use a log shipper that knows how to get logs via the Docker API, such as https://github.com/sematext/sematext-agent-docker or does Kontena prefer Docker API not to be used?

Yes, you can. The only drawback I can think of is the fact that Kontena also streams the logs from Docker API and thus multiple open streams might increase the load on Docker a bit.


The docs have been updated with different options how to get logs out from the system.
http://kontena.io/docs/using-kontena/logs.html

Let us know if there's some missing things on the docs.

**Comment by jnummelin** [comment]
docs have been updated, blogs have been written. :)
