### ISSUE TITLE
Populate an INSTANCE_NUM env var

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#1039]
Please populate an environment variable with the instance number of the service.  Some software, like Apache ZooKeeper and Apache Kafka, for example, want to know which instance they are to know who's who.

**Comment by jnummelin** [comment]
It's already populated at the container labels so makes sense to have it in the envs also.

**Comment by dsmiley** [comment]
Not only an env var (very useful, but it would be good to be able to reference it in the kontena.yml for, say, affinity rules or volume references, just as (presumably) `${project}` can be used today.  At least I think project can be used like that.  In this way, I might have nodes with label or machine names containing the service name and instance number with attached storage that this service is expecting to put its data on.

Sorry for possible scope creep :-)

**Comment by jnummelin** [comment]
For the volume references we do have support for, see: https://github.com/kontena/examples/blob/master/wordpress-cluster/kontena.yml#L41

You just have to make sure that you do have same amount of instances defined for both services, obviously. :)
