### ISSUE TITLE
Should cause error if "affinity" isn't defined where it should be.

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#1052]
I put "affinity:" underneath deploy because I didn't know any better... and "kontena app config" didn't complain (but didn't have "affinity present), and "kontena app deploy" seems to have deployed it where I want out of dumb luck.  But then I saw another of my kontena.yml where it was top-level, so then went to view the docs and noticed it appears top level.

Perhaps this applies to other params too.

BTW, I think "affinity" conceptually belongs underneath "deploy".

**Comment by nevalla** [comment]
#1041 will introduce strict validation and it will resolve this issue.

**Comment by nevalla** [comment]
Fixed in #1041
