### ISSUE TITLE
Replace all "ShellSpinner" calls with "spinner"

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1076]
We should get rid of `ShellSpinner` wrapper that is there just to provide backwards compatibility.

**Comment by kke** [comment]
Actually the Kontena::Cli::ShellSpinner is there to provide plugins a way to include the spinner without including Kontena::Cli::Common

There's no `ShellSpinner "foo" do ..` commands  in the cli or plugins anymore

**Comment by jakolehm** [comment]
Oh, did not realize that `ShellSpinner` calls were already refactored...
