### ISSUE TITLE
Linux distribution choice when creating Kontena Master

### ISSUE THREAD

**Issue by renegat59** [kontena/kontena#1081]
Hi,
I just started using Kontena. It seems great, however I would like to ask why there is no choice of distribution when creating Kontena Master? I create it with CLI:
`kontena upcloud master create ...`
It automatically creates a new upcloud instance for me and puts CoreOS on it. Would be great if one could choose the distribution (like Ubuntu)
Thanks!

**Comment by jnummelin** [comment]
The reason why we're limiting the automatic provisioning support (for now at least) to CoreOS is mainly resources. All the distros require somewhat different configs. And when you add to the mix the variations on different cloud provider environments (networking for example) you'd get pretty big matrix of possible distro/environmment combinations. And then add to the mix also different versions of distros and you'll end up in three dimensional matrix. :)

There's also some technical reason why we've chosen CoreOS as the default. CoreOS has really nice auto-update functionality and it's probably the most stable docker setup out-of-box. What we really want to provide for users is something that really works out-of-box and no tuning required.

I'm not saying this cannot or should not be done. If you check out the provisioning plugin code it is actually pretty straight-forward to enhance those. You could create a proper `cloud-init.yml` for the desired distro and then have the plugin to prompt the desired distro. Then some logic to select correct image etc.. PR's are welcome. :)

**Comment by jnummelin** [comment]
Let's (re-)open feature request issues on specific plugin repos (kontena-plugin-xyz) as these kind of issues have to be dealt on plugin level.
