### ISSUE TITLE
Substitute KONTENA_* environment variables in kontena.yml

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#1098]
It's nice that KONTENA_SERVICE_INSTANCE and other KONTENA_\* vars are available to the _container_, but obviously typical images out there (e.g. for Zookeeper, Kafka, ...) don't know anything about Kontena to use them.  Such services _do_ have env variables like KAFKA_ID.  Unfortunately, it appears these env variables aren't getting resolved within the docker-compose/konenta YML file so that I can do this:

```
environment:
  KAFKA_ID: ${KONTENA_SERVICE_INSTANCE}
```

**Comment by jakolehm** [comment]
Currently this is not possible because many of those env variables are resolved after scheduling happens in the Kontena Master. You can re-map these env variables if you create a custom entrypoint/script for your image.
