### ISSUE TITLE
Master does not take account node engine labels on initial agent connection

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1136]
Master sends node information back to agent before agent  sends docker engine labels to master.

This is troublesome in situations where docker engine labels have a custom `region` label because the master will resolve overlay (weave) peer addresses using this label information. Basically this means that node tries to connect to other nodes via public ip which in most cases is not a valid assumption.

**Comment by SpComb** [comment]
Maybe include the critical information from the node as GET parameters in the intiial Websocket connection request?

**Comment by matti** [comment]
workaround: ssh in on of the nodes and `docker restart kontena-agent`

**Comment by matti** [comment]
~never happens on azure since azure is so damn slow to start instances.

**Comment by matti** [comment]
still present with `0.16.1.rc3` (fyi)
