### ISSUE TITLE
Update completion script

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1142]
The autocompleter script is currently out of sync in master, some removed commands are still there and any new commands are not.

Either:

A) Update the script

or

B) Replace the script with something automatic that stays up to date, for example some variation of #985 

Perhaps a good idea would be to add the lazy loader in #1093 while at it to make it snappier (about 2x faster cli spin up).

**Comment by jakolehm** [comment]
For 0.16.0 my vote goes to option A.

**Comment by jakolehm** [comment]
Fixed in #1168 .. for B we can open a new issue.
