### ISSUE TITLE
Fix Ubuntu master installation / auth docs

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1143]
Docs in the master branch are missing few critical pieces:

- configuring initial token
- login with initial token
- how to configure external authentication

**Comment by jnummelin** [comment]
The initial admin code setup is now documented in the packaging update PR.

External auth is IMO pretty well already documented in master, see 
https://github.com/kontena/kontena/blob/master/docs/using-kontena/authentication.md
