### ISSUE TITLE
Local auth backend

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#116]
Would be nice to have local auth backend with master. In cases where both master and nodes are deployed in private datacenters it might be an issue to have auth in public cloud. Some local option would be really usable in these kind of cases. And by local I mean something close to master if not really build in to master.

Of course people can do this by "reverse-engineering" the auth API calls made in https://github.com/kontena/kontena/blob/master/server/app/services/auth_service/client.rb, but at least some "official" documentation about the API should be available. Also, to enable more out-of-box usability of Kontena it would be really nice to have some local option available out-of-box. Maybe some docker image that uses some embedded storage.

**Comment by jakolehm** [comment]
For local auth backend see: https://github.com/jnummelin/kontena-local-auth

**Comment by mtrofimm** [comment]
thanks @jnummelin :+1:
