### ISSUE TITLE
Xenial package uses different ports

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1182]
Ubuntu Xenial packages uses ports 80/443, Trusty uses ports 8080/8443.

**Comment by SpComb** [comment]
Should we document the new ports, revert to the old ports, and/or make them configurable via `/etc/kontena-server.env` e.g. `PUBLISH_HTTP/HTTPS=80/443`?

**Comment by jakolehm** [comment]
I think we should use the old ports, easier to document and does not confuse users too much (and they allow to install master + agent on the same machine). It might be also a good idea to make them configurable.
