### ISSUE TITLE
Add LetsEncrypt cert register & renewal to loadbalancer

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#1194]
The LetsEncrypt support in Kontena Master's haproxy is great.  This issue is to request that a similar capability be added to the loadbalancer/haproxy for my grid.  The "kontena certificate" feature assumes I can manipulate my DNS TXT records, but due to organizational reasons, it's not an option for me.  Even if this feature was just for renewal; it'd still be awesome.

**Comment by mlaitinen** [comment]
I'm currently using `jwilder/nginx-proxy` with the [Let's Encrypt companion container for nginx-proxy](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) and I really really hope that Kontena would offer something similar. That project could be a good starting point for a `letsencrypt-kontena-lb-companion`.

With Kontena I'd have to renew the certificates every 3 months by hand and I don't even have access to all of the DNS records.

**Comment by jnummelin** [comment]
With 1.4 there's gonna be a new way to handle LE domain authorizations using tls-sni. there's also gonna be automatic renewal with that.
See:
#2732 
#2736 
#2816

**Comment by dsmiley** [comment]
Awesome guys 👍
