### ISSUE TITLE
0.16 UI improvements (was: kontena.io verification email could be styled more)

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1204]
Finer things in life...

![agontena__appgyver__-_flowdock](https://cloud.githubusercontent.com/assets/3893/19685644/4f5aa968-9ac6-11e6-9dcf-6908eaed1345.png)

**Comment by matti** [comment]
(same template is used with password reset request)

**Comment by matti** [comment]
while at it: resetting password says "now you can login with your password" (something like that) and the linked word login is BLUE inside GREEN container, looks bad.

**Comment by matti** [comment]
![kontena_cloud](https://cloud.githubusercontent.com/assets/3893/19687552/7735283e-9ace-11e6-9d63-ed15c191a5c6.png)

**Comment by nevalla** [comment]
Thanks for the feedback. I have delegated this to our design team and some of these ideas are already implemented. Maybe we should create some dedicated repo for these issues related to Kontena Cloud.
