### ISSUE TITLE
Unable to install kontena-server on Ubuntu 14.04.3

### ISSUE THREAD

**Issue by r4wr** [kontena/kontena#121]
Was following the bare metal install:

    # apt-get install kontena-server
    Reading package lists... Done 
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     kontena-server : Depends: lxc-docker (= 1.7.1) but it is not installable or
                           docker-engine (= 1.7.1) but 1.7.1-0~trusty is to be installed
    E: Unable to correct problems, you have held broken packages.

OS Version:

    # cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
    
I initially had the latest docker installed 1.8, but purged and reinstalled 1.7.1. Any ideas?

**Comment by jakolehm** [comment]
Is docker installed from official docker repository?

**Comment by r4wr** [comment]
Yes, it's installed from the official docker repo.

```
# apt-cache policy docker-engine
docker-engine:
  Installed: 1.7.1-0~trusty
  Candidate: 1.8.1-0~trusty
  Version table:
     1.8.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
 *** 1.7.1-0~trusty 0
        100 /var/lib/dpkg/status
```

**Comment by jakolehm** [comment]
That seems really odd, kontena-server package requires docker-engine >= 1.7.0. Can you try to remove kontena-server, then install docker-engine and finally install kontena-server package again?

**Comment by r4wr** [comment]
I wasn't able to get kontena-server installed so I can't remove it. The error in my initial post was from my first attempt at installing kontena-server.

**Comment by jakolehm** [comment]
Ok, this seems to relate to new docker apt repository. We have uploaded a new packages that should work. Just run `apt-get update` and try to install again.

Thanks for reporting this!
