### ISSUE TITLE
Generated self signed cert for master should be installed locally

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1228]
The provisioning plugins place the cert into cloudinit.

To install the cert locally and get rid of the SSL cert errors you need to dig that file from the host over ssh.

The .pem should be installed automatically to `~/.kontena/certs/<hostname>.pem`

**Comment by kke** [comment]
It would also be possible to generate the cert on master if one was not supplied and have a command on CLI that would install it magically (`kontena master ssl-certificate install`)

**Comment by aleksijohansson** [comment]
This would really be a good feature.

**Comment by nevalla** [comment]
Fixed in #1337
