### ISSUE TITLE
HAProxy should use more secure SSL config

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1233]
The default HAProxy settings get a 'C' on ssllabs.com. I suggest locking this down with the following change:

```
- bind 0.0.0.0:443 ssl crt /etc/ssl/private/
+ bind 0.0.0.0:443 ssl crt /etc/ssl/private/ ciphers AES128+EECDH:AES128+EDH force-tlsv12 no-sslv3
```

Now it gets an 'A' (although I also had to append newly generated DH params to the SSL_CERT).

Looks like it is in lib/kontena/haproxy_config_generator.rb:55 but I can't find this file in the repo to submit a PR..

For the master I think supporting old clients probably doesn't need to be considered since it isn't user-facing. For the Kontena Load Balancer it probably does though so you might make this more configurable in the LB somehow (if it isn't already, I didn't see any way to change it on the master without editing the rb file).

**Comment by kke** [comment]
kontena/kontena-haproxy:

[https://github.com/kontena/kontena-haproxy/blob/master/lib/kontena/haproxy_config_generator.rb
](https://github.com/kontena/kontena-haproxy/blob/master/lib/kontena/haproxy_config_generator.rb
)

**Comment by jnummelin** [comment]
Kontena LB gets A rating, at least with LE certificates. It has the proper cipher suites set:
https://github.com/kontena/kontena-loadbalancer/blob/master/confd/templates/haproxy.tmpl#L9

**Comment by colinmollenhour** [comment]
With respect to kontena-loadbalancer which may be used for customer-facing sites I would note that SSLv3 is allowed by PCI-DSS through June 2018. Good old IE is the main reason for allowing it. I'm not personally using the LB in this capacity but it could potentially be a blocker for some people. For kontena-haproxy disabling sslv3 is the right thing to do IMO.

Do I need to open an issue on the other project?

**Comment by jakolehm** [comment]
@colinmollenhour no need to open an issue to other repos.

Maybe we could allow to set `ssl-default-bind-ciphers` via env to kontena-loadbalancer.  Kontena-haproxy default needs a fix (and maybe also possibility to define own ciphers).
