### ISSUE TITLE
kontena cloud password change does not work in Safari

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1235]
I hit "update" hard, does nothing.

**Comment by ixrock** [comment]
Browser? OS?
I tried to do in latest Chrome, OS X 10.11.6, works for me in dev/prod envs.

**Comment by jakolehm** [comment]
Just a side note that we should move these cloud related issues to somewhere else.

**Comment by matti** [comment]
@ixrock safari

@jakolehm just tell where

**Comment by matti** [comment]
@ixrock tested again: works in chrome, fails in Safari

**Comment by ixrock** [comment]
@matti OS? version? is it working if you press enter after password value changed and pointer  focused on the input?

**Comment by ixrock** [comment]
Ok, I guess I figured out what the problem.. seems like it's safari bug with submit buttons.. will be fixed soon.
