### ISSUE TITLE
Setting memory size of vagrant node is not working

### ISSUE THREAD

**Issue by aleksijohansson** [kontena/kontena#1244]
If I choose the memory size of 2048MB kontena still creates the nodes with 1024MB of memory. This happens if I create one node at a time or multiple nodes at once. Kontena CLI version 0.1.6

**Comment by jnummelin** [comment]
Vagrant related issues should be reported in the https://github.com/kontena/kontena-plugin-vagrant repository.

This is a regression bug with 0.16, I will whip up a PR in few minutes.

**Comment by jnummelin** [comment]
This issue was moved to kontena/kontena-plugin-vagrant#21
