### ISSUE TITLE
Modify resolve.conf file for agent docker-compose installs

### ISSUE THREAD

**Issue by mattdavenport** [kontena/kontena#1260]
It appears that deploying nodes via [docker-compose](https://www.kontena.io/docs/getting-started/installing/docker-compose) does not modify /etc/resolv.conf like the Ubuntu package does [here](https://github.com/kontena/kontena/blob/50376cc0edefdea8a2bb8d05c3bb444113e80537/agent/packaging/ubuntu/kontena-agent/etc/init/kontena-agent.conf#L14).

**Comment by jnummelin** [comment]
There's already a docs update PR for this: #1257

**Comment by mattdavenport** [comment]
Must have missed that one. Thanks!
