### ISSUE TITLE
App build is missing --pull option

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1284]

**Comment by jakolehm** [comment]
Or should we always pull? 

/cc @kontena/core-platform

**Comment by jnummelin** [comment]
Pulling always should be quite ok. It's just bit annoying to wait for the pull even if nothing is updated but should not be that big deal. What if the pull fails, should the build still continue?

Another option is to pull always and have a flag `--no-pull`

**Comment by colinmollenhour** [comment]
My $.02: pull always with `--no-pull` option

**Comment by nevalla** [comment]
@jakolehm Is this included in upcoming stacks?

**Comment by jakolehm** [comment]
@nevalla see #1331

**Comment by jnummelin** [comment]
Closed via #1331
