### ISSUE TITLE
Cannot recreate registry

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1288]
I was working on a grid and suddenly could no longer push to the registry.. No idea what changed..

```
Successfully built edbc29fc086e
Pushing image registry.kontena.local/mariadb-galera:latest to registry
The push refers to a repository [registry.kontena.local/mariadb-galera]
Get https://registry.kontena.local/v1/_ping: dial tcp 10.81.1.159:443: getsockopt: connection refused
 [error] Failed to push image registry.kontena.local/mariadb-galera:latest
         Rerun the command with environment DEBUG=true set to get the full exception
```

I disconnected from OpenVPN and reconnected. The DNS was resolving and I could ping the IP but curl also showed "Connection refused". I didn't think this was supposed to be an HTTPS connection so I tried HTTP:

```
$ curl -v http://registry.kontena.local:80/v1/_ping                                                        
* Hostname was NOT found in DNS cache
*   Trying 10.81.1.159...
* Connected to registry.kontena.local (10.81.1.159) port 80 (#0)
> GET /v1/_ping HTTP/1.1
> User-Agent: curl/7.35.0
> Host: registry.kontena.local
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Fri, 04 Nov 2016 22:51:55 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host registry.kontena.local left intact
```

Regardless, I just needed it working so I tried to remove the registry and recreate it.

```
$ k registry rm
> Destructive command. You can skip this prompt by running this command with --force option. Are you sure? Yes
 [done] Removing registry service  
### wait a bit..
$ k registry create
 [error] Registry already exists
```

So now the service is stuck in "deleting" and cannot be deleted. The containers are completely gone though (verified on node with `docker ps` ) so it is just Kontena's metadata..

```
$ k service show registry
mytest/registry:
  status: deleting
  image: kontena/registry:2.2
  revision: 1
  stateful: yes
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
  dns: registry.mytest.kontena.local
  env: 
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    - REGISTRY_HTTP_ADDR=0.0.0.0:80
    - REGISTRY_HTTP_SECRET=5ec77605f957e8c8c8f511736603f5376482442f67bc0cb6
  net: bridge
  volumes:
    - /registry
  instances:
    registry-1:
      rev: 2016-10-31 21:23:46 UTC
      service_rev: 1
      node: test4.local.lan
      dns: registry-1.mytest.kontena.local
      ip: 10.81.1.159
      public ip: 147.75.***.***
      status: dead
      exit code: 137
```

Trying to remove it again now it just hangs for a long time. 

```
$ k service rm registry
Destructive command. To proceed, type "registry" or re-run this command with --force option.
> Enter 'registry' to confirm:  registry
 [fail] Removing service registry      ^C
```

On the master logs I see the following request is repeating multiple times per second until I killed the "service rm registry" command.

```
"GET /v1/services/mytest/registry HTTP/1.1" 200 867 0.1151
```

How can I get this working again without completely wiping out my grid/master again?

**Comment by SpComb** [comment]
> So now the service is stuck in "deleting" and cannot be deleted. The containers are completely gone though (verified on node with docker ps ) so it is just Kontena's metadata..

Check `docker ps -a` on the node for any status=dead containers?

**Comment by jakolehm** [comment]
@colinmollenhour ssh into node `test4` and restart kontena-agent. After that `k service show registry` should not have dead instance. Then `k service stop registry && k service rm --force registry` should work.

**Comment by jakolehm** [comment]
First problem with push to the registry might come from Docker for Mac (just a guess). DfM sometimes seem to forgot "insecure-registry" option during upgrade...

**Comment by jakolehm** [comment]
Stuck in "deleting" issue is tracked here: https://github.com/kontena/kontena/issues/828

**Comment by colinmollenhour** [comment]
@SpComb `docker ps -a` did not show any registry containers while Kontena was still showing the "dead" registry-1 container.

@jakolehm After restarting docker on test4 Kontena still had the "registry" service in "deleting" status but it no longer showed the "registry-1" instance and it was successfully removed with "k service rm --force registry".

Thanks guys, I don't think I saw the `--force` option for the rm before. At least now I know how to recover if it happens again. Will close as it seems to be a duplicate of #828.
