### ISSUE TITLE
Service deploy --force to deprecate --force-deploy

### ISSUE THREAD

**Issue by mattdavenport** [kontena/kontena#1294]
Similar to #969, for API consistency `kontena service deploy --force-deploy` should be changed to simply `kontena service deploy --force`. Also similar, this should deprecate --force-deploy for current backwards compatibility until fully removed in a major version bump or otherwise.

**Comment by matti** [comment]
nice, good catch

**Comment by nevalla** [comment]
Fixed in #1295
