### ISSUE TITLE
Custom init process to replace agent hacks

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1316]
Docker now supports custom init processes (see: https://github.com/docker/docker/pull/26061) so we could replace container entrypoint hacks with init process that reaps zombies and starts actual run command after agent has sent specific signal to init.

**Comment by SpComb** [comment]
This needs to wait for Docker 1.13:

Related Docker PRs:

* https://github.com/docker/docker/pull/26061
* https://github.com/docker/docker/pull/28037
* https://github.com/docker/docker/pull/26941
