### ISSUE TITLE
Container stop/restart timeout is not configurable

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1334]
`kontena service stop`, `restart` (and others like `scale` ?) use docker defaults (10s) to wait for process to terminate -- there are valid cases where services need more than 10s to exit.

`SIGTERM` --> 10s --> `SIGKILL`

**Comment by matti** [comment]
a) global grid wide default setting for all services?
b) per service setting (possibly a+b) ?

**Comment by matti** [comment]
prob best off with `--timeout` as: `kontena service stop --timeout=60 redis`

**Comment by jakolehm** [comment]
I think this should also be in the service definition.

**Comment by jnummelin** [comment]
I think having a reasonable short default is ok for most services but the ability to make it longer in service definition would allow user to increase it for services which require longer timeout.

**Comment by matti** [comment]
agreed
