### ISSUE TITLE
Regex support for kontena LB's KONTENA_LB_VIRTUAL_PATH

### ISSUE THREAD

**Issue by Edke** [kontena/kontena#1343]
Would be useful to have possibility to use regular expression for `KONTENA_LB_VIRTUAL_PATH` to handle multiple locations on HAProxy side:

```yaml
  - KONTENA_LB_VIRTUAL_PATH=\/(static|media)
```

**Comment by jakolehm** [comment]
Would comma separated list of virtual paths help?
See https://github.com/kontena/kontena-loadbalancer/pull/31

**Comment by Edke** [comment]
@jakolehm sure, that is really sufficient in my use case, thanks. When it's scheduled for release ?

**Comment by SpComb** [comment]
Available now via `kontena/lb:edge` for testing. That will be promoted to be the default `kontena/lb:latest` later.

**Comment by Edke** [comment]
Great, will test it, thanks

**Comment by Edke** [comment]
@SpComb tested, works great, for me this is a fix, issue can be closed

**Comment by jakolehm** [comment]
Fixed in https://github.com/kontena/kontena-loadbalancer/pull/31
