### ISSUE TITLE
Fix plugins node create cloud-config DOCKER_OPTS=--insecure-registry=10.81.0.0/16

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1352]
New `kontena registry create` stack services will be deployed at `10.81.128.X/17` addresses, outside of the existing `10.81.0.0/19` subnet (see #1330).

Existing Kontena 0.16 installs configured with docker daemon `--insecure-registry="10.81.0.0/19"` will be unable to use any deployed kontena registry service after the 0.16 -> 0.17 upgrade.

**Comment by jnummelin** [comment]
All plugins updated and released already with this fix.
