### ISSUE TITLE
Failed to create Packet master

### ISSUE THREAD

**Issue by adersberger** [kontena/kontena#1353]
`kontena packet master create` fails with the following error message:

```
> Packet plan: Type 0
 [done] Retrieving a list of available facilities at Packet
> Packet facility: Amsterdam, NL (baremetal,storage)
 [error] undefined method `to_hash' for "qaware-jad@Josefs-MacBook-Pro.fritz.box":String
Did you mean?  to_s
         Rerun the command with environment DEBUG=true set to get the full exception
```

**Comment by jakolehm** [comment]
Which ruby version?

**Comment by adersberger** [comment]
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]

**Comment by jakolehm** [comment]
Ok, is Kontena CLI using latest packet plugin (0.2.2)? If yes, are there any other packet plugin versions installed on your system `gem list |grep plugin-packet` ?

**Comment by adersberger** [comment]
kontena-plugin-packet (0.2.3)

**Comment by kke** [comment]
@adersberger Could you get a backtrace by using `DEBUG=true kontena packet master create` ?

**Comment by kke** [comment]
Plugin updated, install to fix:

```sh
$ kontena plugin uninstall packet && kontena plugin install packet
```

**Comment by adersberger** [comment]
perfect! Now it works. thx.
