### ISSUE TITLE
kontena-cli: installation problem

### ISSUE THREAD

**Issue by nam-vuhoang** [kontena/kontena#138]
After running 'gem install kontena-cli' and then 'kontena -v' I've got this error message:

/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find kontena-cli (>= 0) amongst [] (Gem::LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
        from /usr/lib/ruby/1.9.1/rubygems.rb:1210:in `gem'
        from /usr/local/bin/kontena:18:in `<main>'

=============================================

Some related information:

1) At the beginning I had ruby 1.8.7 on my Ubuntu comp. Then I installed ruby 1.9.3 by this command:

sudo apt-get install ruby1.9.3

2) Then I changed the default ruby link (to change from ruby 1.8.7 to 1.9.3) by running command:

sudo update-alternatives --config ruby

3) After that I run 'gem install kontena-cli' and 'kontena -v' as mentioned above.

**Comment by jakolehm** [comment]
We support only >= Ruby 2.0.
