### ISSUE TITLE
Agent Weave unnecessarily calls weaveexec launch-router, and logs error

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1397]
Restarting the kontena-agent on a running node that has already launched weave will log the following ERROR message from `Kontena::NetworkAdapters::WeaveExecutor`:

```
kontena-agent | E, [2016-11-24T12:01:03.211914 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "...", "--trusted-subnets", ""]
kontena-agent | weave is already running; you can stop it with 'weave stop-router'.
kontena-agent | 
kontena-agent | I, [2016-11-24T12:01:03.233038 #1]  INFO -- Kontena::NetworkAdapters::Weave: attaching router
kontena-agent | D, [2016-11-24T12:01:04.106596 #1] DEBUG -- NetworkAdapters::WeaveExecutor: weaveexec ok: ["--local", "attach-router"]
kontena-agent | 
```

This is mostly harmless (apart from leaking the weave secret), but the `Weave#start` logic should be fixed to only perform the `weaveexec launch-router` when necessary, i.e. on the initial kontena-agent start, and after upgrading the weave image/configuration. `Weave#start` should call `weaveexec attach-router` if the weave container is already running, but the weave bridge does not exist. If the weave container is running and the weave bridge already exists, we don't necessarily need to call either, unless weave is in some uncertain state needing a `weaveexec reset`:

```
kontena-agent | E, [2016-11-21T14:44:21.189053 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "attach-router"]
kontena-agent | Inconsistent bridge state detected. Please do 'weave reset' and try again.
```

**Comment by jakolehm** [comment]
@SpComb we should fix this asap.

**Comment by SpComb** [comment]
Seeing as this is semi-related;

The `weaveexec reset` logic needs some improvement to not just check if the `weave` container is running; that doesn't say anything about the actual `weave` bridge being up. Instead, we should probably run `weaveexec reset` if the `weaveexec attach-router` fails.

**Comment by SpComb** [comment]
I am experimenting with a attach vs launch or reset approach in my agent refactoring branch: https://github.com/kontena/kontena/blob/e58e18a/agent/lib/kontena/launchers/weave.rb#L94-L116

Once we figure out where that is going, I can try and submit a PR that fixes this, but it's not immediately apparent yet.

**Comment by SpComb** [comment]
Bumping to 1.4 because the agent weave refactoring didn't make it for 1.3
