### ISSUE TITLE
SSL certificate not generated?

### ISSUE THREAD

**Issue by plathon** [kontena/kontena#1400]
The installation process work perfectly without errors
but when i try to execute a command 
i receive the follow error

![Image](https://i.imgsafe.org/72acfaf537.png)

I suspect the problem is when it comes to generating the SSL certificate

![Image](https://i.imgsafe.org/72acfb9eac.png)

ps: i don't have any "~/.kontena" directory

**Comment by jakolehm** [comment]
Certificate is generated to the provisioned Kontena Master server but not installed automatically to the cli. Next version of cli can install certificate automatically if cloud provider plugin passes certificate back to cli during provisioning.

See: https://github.com/kontena/kontena/pull/1337

**Comment by WoLfulus** [comment]
How can I transfer the certificate from master to CLI manually?

**Comment by kke** [comment]
This could work to install it manually:

`$ openssl s_client -showcerts -connect <master_ip_address>:443 < /dev/null 2>/dev/null | openssl x509 -text -outform pem > ~/.kontena/certs/<master_ip_address>.pem`

**Comment by jnummelin** [comment]
I think we can close this with #1337 and the various plugin enhancements that return the self-signed certificate.
