### ISSUE TITLE
container affinity

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1402]
Currently there is `service` affinity like:

```
affinity:
  - service==mysql
```

But there are some (raw docker) cases when one would like to schedule a service in the same machine as where a container is running (see https://github.com/jeroenpeeters/docker-ssh)

Affinity setting `container==mysql-1` would ensure this.

**Comment by jnummelin** [comment]
There is `container`affinity: https://github.com/kontena/kontena/blob/master/server/app/services/scheduler/filter/affinity.rb#L25

Should be documented... :)

**Comment by matti** [comment]
hnnngggh
