### ISSUE TITLE
Force remove service volumes

### ISSUE THREAD

**Issue by mattdavenport** [kontena/kontena#1449]
Not sure how useful this would be to the majority, but in development/testing I've found myself wanting this feature. There should be a `--remove-volumes` type flag for `kontena service rm` or `kontena app rm` which would remove the dangling volumes on the nodes which the services are deployed on. For instance, running something like `docker volume rm $(docker volume ls -qf dangling=true)` but more specific to the service being removed. I realize volume containers are meant specifically to be stateful, and shouldn't be removed. However it helps in debugging certain issues if the user expects an entirely new volume to be created, but instead the service uses an existing volume (potentially with bad/corrupt data).

**Comment by jnummelin** [comment]
When you create a stateful service, Kontena automatically creates a volume container also with the name `service-1-volumes`. When the service is removed, Kontena removes also the volume container so there should not be any "dangling" volumes left behind. If there is, it's a bug somewhere. :)

If I understand your use-case right, you'd like to create a new fresh volume during the deploy to wipe any previous data? If that's what is wanted, I think it could be a flag of some sort in the deploy command, something like: `kontena stack/app deploy --replace-volumes --force xyz`. Would that cover your use case?

**Comment by mattdavenport** [comment]
Ah yes, that's what I was going for. Thanks for the clarification!

**Comment by jakolehm** [comment]
@mattdavenport is this still an issue with new volume handling/commands?

**Comment by mattdavenport** [comment]
Nope, the new volume commands cover this for our use cases very satisfactorily. Thanks!
