### ISSUE TITLE
Cloud login during master deploy wizard doesn't work.

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1451]
If you `kontena cloud login` before master create, it's all good.

If you haven't logged on, or maybe your token has expired (~~I think refresh isn't working either~~), you'll get to complete the cloud login procedure, but installation halts right after, saying "You must log in to kontena cloud".

**Comment by kke** [comment]
![image](https://cloud.githubusercontent.com/assets/224971/20743537/9f234f1a-b6df-11e6-8bdc-bf55d652e84a.png)

Now it works.

Didn't work yesterday.

**Comment by jnummelin** [comment]
Shall we close this or have you been still able to reproduce?

**Comment by kke** [comment]
Haven't been deploying now, but since nobody else seems to be reporting, maybe it was just me.
