### ISSUE TITLE
kontena grid health for etcd

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1470]
With the Kontena IPAM based on etcd, the health of the grid's initial nodes and the kontena-etcd cluster is more critical than before; service deploys will not succeed without a functional kontena-etcd and kontena-ipam. Before Kontena 1.0 with the kontena-ipam, this kind of unhealthy grid would still let you deploy services, but the LB linking/registrations would be broken, which you might not even notice.

These kind of etcd cluster failures can be caused by configuration issues, doing e.g. `kontena grid create --initial-size=3` but only creating one node. #1468 addresses the configuration issues by having `kontena node ls` show warnings/errors when trying to run a grid with fewer nodes than required.

However, the `/v1/grid/:grid/nodes` configuration itself is not really enough to verify that the grid's etcd cluster is actually healthy. This would need to actually query the etcd cluster-health on each of the host node agents.

**Comment by jnummelin** [comment]
I was thinking of something like:
```
kontena etcd cluster-health
```

Maybe some options to force the node where the etcd is actually queried.
