### ISSUE TITLE
--rm option for kontena app build command

### ISSUE THREAD

**Issue by mattdavenport** [kontena/kontena#1492]
When building a service via `kontena app build <service_name`, it appears that kontena leaves the previous image on a successful build. This previous image is untagged, and in some (most?) cases, won't be used anymore. As a convenience, it would be nice to be able to specify an `--rm` flag or similar to the build command which would instruct kontena to remove the untagged/old image upon successful build.

**Comment by jnummelin** [comment]
closing as app commands are now fully deprecated and moved to separate plugin
