### ISSUE TITLE
pre-1.0 service containers have an empty overlay IP in the server API

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1495]
The Kontena 1.0 server `/v1/services/:grid/:stack/:service/containers` API returns en empty JSON `{"ip_address": ...}` for any service containers deployed pre-1.0. This is harmless but confusing - the service containers will have an existing `10.81.1.X` overlay IP (but not managed by the Kontena IPAM).

The API service containers JSON is from `Container#ip_address` -> `self.networks.dig('kontena', 'overlay_cidr')`, which exists based on the `io.kontena.container.overlay_network=kontena` label. This label is only set on containers deployed with Kontena 1.0, and is missing from existing containers.

The server `ContainerInfoMapper#parse_networks` should probably default a missing `io.kontena.container.overlay_network` label to be `kontena` to support 0.16 containers.

**Comment by jnummelin** [comment]
Probably not an issue anymore as people are running more recent versions. :)
