### ISSUE TITLE
Multiple node_info calls to agent might trigger weave setup error

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1530]
Logs from the crime scene: https://gist.github.com/jakolehm/72ed5feca99f8a90e7fccc4b1fc05a93

**Comment by SpComb** [comment]
Dissecting `Weave`, it looks like multiple 'node_info` events will lead to multiple async calls to `self.start`. If these happen while the agent is still busy pulling the `weave` images, then all of those calls will sleep waitiing for the images, and then proceed to `weavexec launch-router` multiple times concurrently.

This will be more likely to happen when deploying multiple nodes simultaneously, where each node coming online will update the `peer_ips`, and trigger multiple `node_info`'s in a short time..

## `def initialize`

```ruby
      subscribe('agent:node_info', :on_node_info)
      ...
      async.ensure_images if autostart
```

## `def on_node_info(topic, info)`

```ruby
      async.start(info)
```

## `def start(info)`
```ruby
      sleep 1 until images_exist?
```

**Comment by SpComb** [comment]
Multiple concurrent `weaveexec launch-router`s will then tickle weave to race with itself and thus crash out: https://github.com/weaveworks/weave/issues/2638

**Comment by jalberto** [comment]
I can confirm this, deploying with ansible 3 nodes in a row (is sequential but quite fast) deployed around 12 times in brand new created servers, same error each time, etcd cannot go to quorum and 500s in kontena-ipam
