### ISSUE TITLE
Affinity and port options do not work together

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#154]
When ever service is updated with port information the service spec loses it's affinity setup. And when affinity is set the service loses its port configuration.

Steps to reproduce:
```
kontena service create --affinity node==xyz nginx nginx:latest
kontena service deploy nginx
kontena service show nginx # Should show affinity in action
kontena service update -p 80:80 nginx
kontena service deploy nginx
kontena service show nginx # Affinity setup lost!!!
```

Seems to work ok if one specifies BOTH options at the same time. :)

**Comment by nevalla** [comment]
I located error to CLI's update command. CLI sends empty affinity value to server when affinity options are not set.
https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/services/update_command.rb#L40

Correct implementation should be something like this:
`data[:affinity] = affinity_list unless affinity_list.empty?`
