### ISSUE TITLE
Read stack variable defaults from master or a file

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1551]
When installing or upgrading read defaults for variable answers from the previous answers stored to stack info on master or a settings file.

Also add the possibility to answer questions and write the answers to such a file.

Also maybe something like `stack reconfigure` (which does almost the same as upgrade, re-answer questions and create a new revision)

**Comment by jnummelin** [comment]
@kke didn't #1662 implement this?

**Comment by kke** [comment]
It implemented the server part. The reading part from file was implemented in #1560 

Reading from the saved ones in master is still TODO.
