### ISSUE TITLE
kontena container exec is too complicated to use

### ISSUE THREAD

**Issue by timolehto** [kontena/kontena#1563]
Back in the days of 0.1x.x you could do things like:

    #assuming that there's an instance -1 of your service..
    kontena container exec rails-app-1 rake db:migrate

Now:
```
kontena version
cli: 1.0.2
master: 1.0.2 
````

...you need to do something like this:

    kontena container ls | grep rails-app | head -n1 | cut -d " " -f1 | xargs -I_ kontena container exec _ rake db:migrate

**Comment by SpComb** [comment]
You can use the new `kontena service exec` now.
