### ISSUE TITLE
Master/mongo connectivity issues

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1576]
When doing a MITG style deployment:

root/initial VMs: `initial-master-node, mongo-node`
- `initial-master-node` cloud config starts a master that points to mongo-vm (that runs mongodb with cloud config)
- `initial-grid` is created here

master-grid VMs: `mitg-node-0, mitg-node-1, mitg-node-2`
- these nodes run kontena-agent and they join the `initial-grid`
- mongo replica set is deployed as a kontena service (daemon) on these nodes (as `mongo-peer-1, mongo-peer-2, mongo-peer-3`)
- kontena master is deployed as kontena service (daemon) on these nodes (as master-1, master-2, master-3) and mongo is configured as `MONGO_URI=mongo://mongo-peer-1:27017,mongo-peer-2:27017,mongo-peer-3:27017`

Problem:
t0: mongo replica set is started
t1: masters are started, ruby(?) resolves `mongo-peer-1..3` as `10.81.128.101..103`
t2: mongo replica set restarts, `mongo-peer-1` is now `10.81.128.201..203`
t3: masters have stale DNS and are thus unable to connect to the mongo nodes. master constantly throws exceptions on unable to connect to the replica set, but does not die.
t4: operator manually restarts masters, DNS is refreshed --> works again.
t5: GOTO t2

Suggested actions:
- Somehow force refresh of DNS records..?
- If the master is unable to connect to mongo --> exit and docker will restart

**Comment by matti** [comment]
prob. due to https://github.com/mongoid/moped/issues/236

**Comment by matti** [comment]
I guess the real problem is that master is considered healthy in this state

**Comment by matti** [comment]
https://github.com/kontena/kontena/pull/1290

**Comment by timolehto** [comment]
https://github.com/kontena/kontena/pull/1580 sort of fixes this I thinks

**Comment by jakolehm** [comment]
#1290 should fix this properly

**Comment by jakolehm** [comment]
#2257 should fix this (again)
