### ISSUE TITLE
Agent weave start segmentation fault, Inconsistent bridge state

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1582]
#1545 locked the agent weave actor against concurrent start operations to avoid weave panics/segfaults caused by concurrent `weaveexec launch-router` / `weaveexec attach-router` operations on the same bridge interfaces ( #1530).

However, there are still such `Segmentation fault (core dumped)` -> `Inconsistent bridge state detected. Please do 'weave reset' and try again.` errors during inital node startup with Weave 1.7.2 on Kontena 1.0.2, even without multiple concurrent start operations running:

```
E, [2016-12-20T09:36:11.201456 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "...", "--trusted-subnets", ""]
weave is already running; you can stop it with 'weave stop-router'.
I, [2016-12-20T09:36:11.264815 #1]  INFO -- Kontena::NetworkAdapters::Weave: attaching router
E, [2016-12-20T09:36:12.553573 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "attach-router"]
Segmentation fault (core dumped)
E, [2016-12-20T09:36:13.681063 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 7: ["--local", "connect", "--replace", "..."]
curl: (7) Failed to connect to 127.0.0.1 port 6784: Connection refused
I, [2016-12-20T09:36:13.714326 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers ...
I, [2016-12-20T09:36:13.714466 #1]  INFO -- Kontena::NetworkAdapters::Weave: using trusted subnets:
E, [2016-12-20T09:36:14.466956 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "expose", "ip:10.81.0.3/16"]
Inconsistent bridge state detected. Please do 'weave reset' and try again.
E, [2016-12-20T09:36:14.571925 #1] ERROR -- Kontena::NetworkAdapters::Weave: Failed to expose host node at cidr=10.81.0.3/16
```

This segfault is *presumably* caused by weave attempting to create a OVS `datapath` interface that already exists, receiving EEXIST, and attempting to continue with a nil `dpif`: https://github.com/weaveworks/weave/issues/2638#issuecomment-263268720
  
See https://github.com/weaveworks/weave/pull/2706 tracking a fix to use the pre-existing `datapath` interface instead.

Remains unknown why the datapath interface would already exist during early boot?

**Comment by jakolehm** [comment]
It seems that Weave 1.8.3 will have that fix.

**Comment by SpComb** [comment]
The agent has some logic to run `weaveexec reset` and re-try the start:

```ruby
        if weave.nil? || !weave.running?
          @executor_pool.execute(['--local', 'reset'])
        end
```

However, this is not going to trigger in this situation where the `weave` container is running, stuck waiting for the weave interfaces. The reset logic should be improved to detect this situation and automatically reset to retry.

**Comment by kke** [comment]
Requires updates to weave, probably won't be there for 1.1.0

**Comment by jnummelin** [comment]
Closing as weave is updated to have the relevant fixes in.
