### ISSUE TITLE
OpenVPN client warns that cipher block is too small

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1604]
I was noticing this pop up in the vpn log, as I use the CLI client. 

```
Fri Dec 30 14:07:06 2016 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
```

I'm relatively new to OpenVPN, but after a bit of reading, it sounds like OpenVPN needs to be updated beyond `2.3.2`. I don't know what else might be involved in terms of changing configurations etc.

I was looking at the`Dockerfile` for it and noticed that it's simply installing via `apt-get` and it might be as simple as just rebuilding the docker image, so I gave that a shot. But, `apt` didn't seem to have the latest version of `openvpn`.

After building, I checked to see what the status was.
```
root@41ec81a38355:/etc/openvpn# apt-cache policy openvpn
openvpn:
  Installed: 2.3.2-7ubuntu3.1
  Candidate: 2.3.2-7ubuntu3.1
  Version table:
 *** 2.3.2-7ubuntu3.1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.3.2-7ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

Could probably use a different `apt` source: https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
or it could also be built from source: https://openvpn.net/index.php/open-source/downloads.html

**Comment by jakolehm** [comment]
I think we should update base image to Ubuntu Xenial (16.04). 

http://packages.ubuntu.com/xenial/openvpn

/cc @jnummelin

**Comment by counterbeing** [comment]
That looks like it would do the trick :)

**Comment by thoughtbox** [comment]
Any chance of adding the monitored interface to the log entries? Particularly useful on a heavily multi-homed host.
