### ISSUE TITLE
Drop support for Ruby 2.0

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1614]
More and more gems are no longer installing on 2.0. Most recently Nokogiri:

```
nokogiri-1.7.0 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p648
```

**Comment by jakolehm** [comment]
MacOS (OSX) is the most problematic one because it ships with ruby 2.0.. we will try to fix this by providing an installer for mac (see #1112).

**Comment by kke** [comment]
Done in #1560 and #1112
