### ISSUE TITLE
 etcdserver: failed to reach the peerURL

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1615]
This isn't a show-stopper, but I'm seeing this in my grid logs a lot:

```
kontena-etcd | 2017-01-03 19:00:56.199314 W | etcdserver: failed to reach the peerURL(http://10.81.0.1:2380) of member 1e9fce08da9bfda7 (Get http://10.81.0.1:2380/version: dial tcp 10.81.0.1:2380: i/o timeout)
```

It's been there for several days. One thing to note about my setup is that I originally started with a few smaller nodes and decided to replace them with nodes with more memory. My only guess is that it's related to that. It just seems like whatever cleanup needs to occur, should happen on its own when using kontena tools to add and remove nodes.

Please let me know if there's any more information I can provide.

**Comment by SpComb** [comment]
Sounds like you're missing one of your initial nodes. This needs #1468 for the CLI to display that clearly.

Do you have any offline initial nodes in `kontena node ls`? If you're replacing nodes, then you must first shutdown the node, and then `kontena node rm`. Once you have removed an initial node, then any new node that you install will replace that initial node.

**Comment by counterbeing** [comment]
That sounds like exactly what's going on. I did remove one of my initial nodes. I didn't shut it down as I recall, I just used the digital ocean plugin to remove it. Then once removed, added replacement nodes, and manually deleted the node from DO.

```
Name                                                                   Status     Initial    Labels
morning-morning-52                                                     online     yes        region=sfo1,az=sfo1,provider=digitalocean
long-firefly-44                                                        online     yes        region=sfo1,az=sfo1,provider=digitalocean
late-water-57                                                          online     no         region=sfo1,az=sfo1,provider=digitalocean
proud-sun-11                                                           online     no         region=sfo1,az=sfo1,provider=digitalocean
patient-fog-31                                                         online     no         region=sfo1,az=sfo1,provider=digitalocean```

I know that at one point I had three nodes marked as initial.

**Comment by counterbeing** [comment]
In the state I'm currently in, it sounds as though I need to somehow promote a node to `initial`. But the word `initial` doesn't sound like it's something you change. Do you have any advice for someone with kontena in this state?

**Comment by timolehto** [comment]
So right now you're running a slightly degraded grid "that's all".

At what point did you run `kontena node rm some-node-xy` for the original initial node? Or are you saying you never did that? Because from my experience until you do that the node lingers in the node list as offline and once you do remove it, next time you provision a new node it will join and take it's place in the grid. So I'm guessing you provisioned new nodes to the grid and then later on removed the old initial node from kontena, thus resulting in a grid like that. And now if you provision one more new node that should take it's place as the third initial node in the grid, though you may run in to some problems with that because of this: https://github.com/kontena/kontena/issues/1136, 1.0.4 should fix that

**Comment by counterbeing** [comment]
That makes sense. What I did, assuming it was the safe route, was add new nodes, and then remove nodes. It sounds like I did it in the reverse order! Of course, it does still sound safer to add nodes before removing others. Thanks for taking the time to explain 👍  

Though, given that you're reducing redundancy when removing nodes, it still seems like it would be nice for a new node to take its place if you add nodes first.

**Comment by timolehto** [comment]
It may be slightly confusing, but consider this. Kontena does not know that you have in fact terminated the node, it only knows it seems to be down, but might be coming up at any time. So if you then start a new node and that node was to steal the place of the offline node as one of the intial nodes then what would happen if the original initial node were to come online at some point later? You would end up having 4 initial nodes, but your grid was configured as a 3 intial node grid so obviously that would cause some serious problems.

**Comment by jakolehm** [comment]
I agree that it would be nice to promote a new node to initial before terminating an old one. This requires a separate command (and lot's of internal magic) because master cannot resolve this kind of situation automatically (as @timolehto explained).

/cc @jnummelin

**Comment by counterbeing** [comment]
The one thing I'm uncertain of is wether or not I terminated the node or removed it. Until this conversation, they two were somewhat synonymous to me. But, just to share, I added a new node and it took the place of the missing "initial" node. I have to say, the descriptor "initial" is a bit misleading to me, because now that it's been replaced, it's no longer "initial". It seems that maybe a different word should be used?

**Comment by jnummelin** [comment]
The term `initial` comes from etcd clustering. I do agree that it's a bit misleading, but at this point it's bolted already at some APIs and might not be possible to change in all places while keeping API compatibility.

Technically I think it's possible to "swap" one node to take `initial` role of from another node. However, it will temporarily anyway impair your grid heavily as many of the Kontena components on a node need to be recreated with different config. For example Weave needs to be reconfigured and etcd needs to be re-created from "scratch". As @jakolehm said, this requires lot's of internal magic to make it happen automatically.

For some background on the initial node replacement, we have a blog post that explains some of the details: http://blog.kontena.io/automatic-etcd-cluster-member-replacement/

**Comment by timolehto** [comment]
The funny thing about `kontena node rm` is that in a sense you can't really remove a healthy node. Doing that will remove it temporarily, but as the node is really healthy out there it will almost instantly rejoin the grid. It seems it will reappear on the list as offline though and will not automatically recover, however to fully recover it seems you just need to reboot the node.

**Comment by counterbeing** [comment]
I'm going to close this as I've fixed it on my end, and I know a related fix went in on your end.
