### ISSUE TITLE
Containers won't start when upgrading from Docker 1.6.x to 1.7.x

### ISSUE THREAD

**Issue by miskun** [kontena/kontena#164]

**Comment by jakolehm** [comment]
Just to clarify a bit. This happened when coreos updated automatically to latest stable version and it fetched latest kontena-agent version on boot. And only etcd seems to fail so investigation continues...

**Comment by jakolehm** [comment]
This seems to be a Docker bug that somehow loses volumes-from references on 1.6 -> 1.7 upgrade. Redeploying services should fix this.
