### ISSUE TITLE
manual master creation starts API at port 8080

### ISSUE THREAD

**Issue by sallespro** [kontena/kontena#1644]
Also, after creating master a a single node, it seems it was unable to start etcd.

**Comment by SpComb** [comment]
What exactly do you mean by manual master creation? The `kontena/server` Docker image will listen on port 9292, and the `kontena/haproxy` Docker image will forward traffic at port 80/443. The `kontena-server` Ubuntu package publishes those `kontena/haproxy` ports at host ports 8080/8443 per default, configurable via `/etc/kontena-server.env`. The installation docs for Ubuntu refer to `https://master_ip:8443`.

Do you mean that Ubuntu package should default to publishing on ports 80/443?

RE unable to start etcd, what does `docker logs kontena-etcd` on the node say? If you created the grid with e.g. `--initial-size=3`, then you need at least two nodes for etcd to start working.

**Comment by sallespro** [comment]
yes, so why would the manual installation on Ubuntu differ from the plugin automated install ?

By the the, it is not clear how to proceed with the assigning of an EIP ( AWS ) when creating the master / nodes. i suspect this makes the "ip update" or node discovery to required a reboot and etcd sync...?
