### ISSUE TITLE
 [error] Forbidden at kontena cloud master update

### ISSUE THREAD

**Issue by sallespro** [kontena/kontena#1645]
`kontena cloud master update --url http://masterip:8080 5856ee35a35b0c00010d6b46
 [error] Forbidden`

**Comment by jnummelin** [comment]
@nevalla Any ideas why this could happen?

**Comment by adrianchifor** [comment]
Getting the same thing. Also, I did `kontena cloud master show xyz` and connected doesn't show, can't see any master in cloud.kontena.io/platforms but the master appears fine when doing `kontena cloud master ls`.

**Comment by jnummelin** [comment]
There has been some updates on the Kontena cloud side in past weeks, do you still encounter this?

**Comment by jnummelin** [comment]
Closing as inactive. Feel free to re-open if this happens again.
