### ISSUE TITLE
EIP address attribution (AWS ) 

### ISSUE THREAD

**Issue by sallespro** [kontena/kontena#1646]
kontena-cli shows `Status offline` despite the fact that Kontena Cloud shows the updated EIP

**Comment by jnummelin** [comment]
So is some of your nodes shown as `offline`? Did I understand correctly (based on some other issues you created recently) that you configured your master to have elastic IP?

**Comment by sallespro** [comment]
i have assigned an EIP to a node, not the master, and when this is done, kontena cloud shows the updated EIP ok but the client shows the node offline.

it is necessary to reboot the node in order to update the status.

`sudo locksmithctl reboot`
