### ISSUE TITLE
mygridname-master-admin appears as if it was a master

### ISSUE THREAD

**Issue by sallespro** [kontena/kontena#1647]
why is it that `kontena master list` shows two masters ?

```
Name                     Url
* mygridname-master           https://instanceip
mygridname-master-admin       https://instanceip

```

**Comment by jnummelin** [comment]
Now with Kontena > 0.16, creating the master creates always a initial admin account on each master. That account is used for the first login and with which the Kontena cloud authentication is configured on the master.

**Comment by sallespro** [comment]
ok, it is confusing an `account` to be shown in the same category as  grid `master`.
