### ISSUE TITLE
Can't pull from private image registry

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1652]
I'm playing with dockerhub, and for some reason kontena is unable to find the image.

I have:
- Pushed the repo, and verified it's name
- Added `hub.docker.com` like so: `kontena external-registry add --username fake  --email faek --password fakefake https://hub.docker.com/r/corylogan/my-private-image`
- Removed the stack and re-added it 

The error I see in the logs is: 
```
Docker::Error::NotFoundError: No such image: corylogan/my-private-image:latest
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:121:in `create'
kontena-agent | 	/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
kontena-agent | 	/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | 	(celluloid):0:in `remote procedure call'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
kontena-agent | 	/app/lib/kontena/service_pods/creator.rb:161:in `ensure_image'
kontena-agent | 	/app/lib/kontena/service_pods/creator.rb:25:in `perform'
kontena-agent | 	/app/lib/kontena/service_pods/creator.rb:70:in `block in perform_async'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

I'm on kontena 1.0.4.
It may be worth noting that i did try to deploy once before  realize I needed to add my credentials for the external registry.

**Comment by counterbeing** [comment]
Further, and this might be a separate issue, I can't seem to remove the stack:

```
➜  infrastructure git:(master) ✗ kon stack rm --force rails

 [fail] Removing stack rails      ^C
➜  infrastructure git:(master) ✗ kon stack rm --force rails

 [fail] Removing stack rails      ^C
➜  infrastructure git:(master) ✗ kon stack rm --force rails

    *   Removing stack rails  .. /
```

I was letting it run for about 20 minutes, but it just spins, and the logs say that the agent is still trying to pull the image in a loop.

**Comment by counterbeing** [comment]
Jussi sorted me out on the initial issue, but the other issue still remained. The other issue being that after adding a container that doesn't exist, the agent got stuck in a loop, and there was nothing i could seem to do to stop it through the cli. I'd like to adjust this issue to target that part.

**Comment by jnummelin** [comment]
Agent retries the image pull 10 times per deployment. Also master will do periodic deployments for a given service when it notices that it's not properly running. (missing instances)

In this case agent should tell master more clearly about the error cause and that should then be also given back to the user. In this case the error for user could be something like: 
```
$ kontena stack install --deploy web.yml 
 [done] Creating stack web      
 [fail] Deploying stack web     
        halting deploy of test/web/nonexisting, one or more instances failed. No such image: jnummelin/test:latest
```
Note that it's impossible for the agent to know whether the image really does not exist or cannot be pulled because of bad credentials. Registries just respond with 404 in when pulling a private image without credentials.

There are couple of PR's already in the pipeline (#1607 and #1512 ) to make the deployment errors better and also make the agent-master comms better in these kind of cases. Not yet sure if they already tackle this issue. /cc @jakolehm @SpComb

**Comment by counterbeing** [comment]
A better error message would be helpful for sure.  You might even include a note in the message that it's possible authorization just failed. 
But, the thing that constitutes a bug here, is really the loop that didn't even allow me to remove the stack. That's kind of a show stopper.

**Comment by jnummelin** [comment]
Yes, it should really be more "graceful" failover in this case. (hence I added the bug label)

**Comment by jakolehm** [comment]
Things should be better in >= 1.2.0.
