### ISSUE TITLE
role master_admin should auto-include grid access

### ISSUE THREAD

**Issue by simu-fs** [kontena/kontena#1686]
When a new user gets created and the master_admin role gets assigned to them, they are still lacking access to configured grids.

I would expect grid-access to automatically be available to them as an auto-include upon receiving the master_admin role.

**Comment by SpComb** [comment]
Related:  #1442

It is possible that some server APIs (`kontena grid`, `kontena stack`) will work for such `master_admin` role users, but others will not.

**Comment by kke** [comment]
Yes. You would expect master_admin to have access to eveything.

**Comment by SpComb** [comment]
Symptom is HTTP 403 `Access denied` errors on some CLI operations but not others.

Workaround is to explicitly add yourself as a grid admin:
```
kontena grid user add <email>
```

**Comment by SpComb** [comment]
Should have been fixed in #1970
