### ISSUE TITLE
After Kontena Node Loss, State is Not Changed

### ISSUE THREAD

**Issue by four43** [kontena/kontena#169]
I terminated an instance that was running as a Kontena Node. After creating a new node and registering it with the cluster nothing happened. Kontena did not try and restart VPN, the registry, or services that were running on that host. Is this desired behavior? Kontena is still staging that the registry is up and running just fine, even though the host it is on is gone:

```
$ kontena service show registry
mygrid/registry:
  status: running
  stateful: yes
  scaling: 1
  image: kontena/registry:2.1
  dns: registry.mygrid.kontena.local
  affinity: 
    - node==ip-10-0-0-99
  cmd: 
  env: 
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    - REGISTRY_HTTP_ADDR=0.0.0.0:80
  ports:
  volumes:
    - /registry
  volumes_from:
  links: 
  cap_add:
  cap_drop:
  containers:
```

That host is no longer in the cluster:
```
$ kontena node list
Name                           OS                                       Driver          Labels                         Status    
ip-10-0-0-166                  Ubuntu 14.04.2 LTS (3.13.0-48-generic)   aufs            -                              online 
```

**Comment by jakolehm** [comment]
Which version are you using? (This can be verified with `curl http://masterip:8080`)

**Comment by four43** [comment]
8.2 it looks like:

```
{"name":"Kontena Master","tagline":"Application Containers for Masses","version":"0.8.2"}
```

**Comment by four43** [comment]
Biggest issue here is that the registry is now not running and gone. How do I get it back? I created started it with S3 config, I would assume a `kontena service restart registry` would do it, but the affinity is locked onto a server that isn't doesn't exist anymore. `kontena registry restart` would be nice, then it could update DNS in the VPN too.

**Comment by jakolehm** [comment]
You can just create a new registry with the same S3 configuration. Nice thing about S3 (and azure etc) backend is that you can nuke registry node without loosing images.
