### ISSUE TITLE
LB health check port needs to be configurable

### ISSUE THREAD

**Issue by pcornelissen** [kontena/kontena#1709]
I have services that have their health checks on a separate port than the "regular" endpoints. This leads to problems because haproxy tries to query the configured health check path on the regular port instead of the management port and as far as I have seen, there is no way to configure this port yet.

It would be nice to be able to configure this.

**Comment by jnummelin** [comment]
This is in the classic borderline between a bug or feature. :) Mapped to get fixed in 1.5 release scope.
