### ISSUE TITLE
LE Certificate renewal

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#1716]
Currently Kontena does not renew the certificate automatically when it's about to expire.

Kontena can do the renewal, it just needs to open the certificate a bit and look at the expiration date. Then X days earlier just issue a renewal on the LE API.

**Comment by SpComb** [comment]
The LE `dns-01` validation challenge's domain authorization is only valid for 7-30 days?

https://community.letsencrypt.org/t/how-long-is-the-dns-01-challenge-valid/22525

> The "authz validity time" (i.e. the time in which you don't need to re-verify your domain using your account key) is currently 60 days, however I believe the goal is to reduce that down to 7 days.

So AFAIK to automate cert renewal with `dns-01` validation, you would also need to automate the `dns-01` challenge?

**Comment by jnummelin** [comment]
The automation of `dns-01` validation would require integration to MANY DNS providers. Although doable, but maybe not something that we really want to maintain.

Another option seems to be to use the `tls-sni-01` validation where one needs to craft a self-sined cert with special altNames. When LE makes the validation request, the server (Kontena LB) needs to respond with that specific certificate.

The `tls-sni-01` verification would make the certificate automation possible with steps like:
- ´kontena certificate register`, creates the private key to interact with LE
- `kontena certificate get --authz tls-sni-01 --lb infra/lb-external foo.example.com`
  1. This creates the authz object with LE API
  2. Server creates the proper LE_TLS_AUTH_CERT_foo_example_com secret with properly crafted self-signed authorization cert
  3. Server "injects" that secret into given LB, in this case `infra/lb-external`
  4. Server requests LE to do the authorization request
  5. Once the authz request passes, get the cert from LE API
  6. Store as previously
  7. Look into the cert to expiry date
  8. Once the expiry date is close (say within 7 days), GOTO 1

**Comment by jnummelin** [comment]
fixed in #2816
