### ISSUE TITLE
Enable us to pipe service(/cluster?) logs to ELK Stack for example

### ISSUE THREAD

**Issue by pcornelissen** [kontena/kontena#1719]
Currently kontana stores the logs on the master, which is better than having them on the nodes, but searchability is limited and we can't for example build reports and dashboards around that using common tools like Kibana.
As you mentioned in Gutter it's possible to scrape the logs from the mongo DB on the master, but this has to be done outside of the cluster which is not ideal, because we have to maintain dedicated hosts to handle the logs and can't use docker resp. kontena to host elasticsearch, kibana etc.

It would be great if additionally(?) we could activate something like filebeat/logspout/logstash or something like that, that also pipes the data into elasticsearch so we can better search and monitor the logfiles. Especially when you have things like zipkin etc. to follow request through your system, you need some aggregated view on the logs.

I think it would be sufficient for kontena to provide a service that gathers the logs and is able to pipe them into logstash server or elasticsearch directly. This would help a lot!

https://hub.docker.com/r/sebp/elk/ is a nice combined docker image that I used with docker swarm.

**Comment by jnummelin** [comment]
This is actually something we've been discussing few times already. :) The main idea has been to enable agent(s) to ship the logs also to some other endpoint in addition to Kontena master. Currently we're thinking of supporting fluentd as the "protocol". The configuration would be pretty much the same as one does for enabling direct statistics exporting, so soomething like:
```
$ kontena grid update --fluentd-log-server foo.bar.com:12345 my-grid
```
This would activate the log shiping on all agents within the grid.

Tentatively scheduled for 1.2 release.

**Comment by pcornelissen** [comment]
Sounds good and the log server could also be running as service in this cluster?

What is the (rough) timeframe for the 1.2 release?

**Comment by jnummelin** [comment]
Yes, this way the ELK stack (or whatever is capable to receive fluentd) can be run within the same grid. But it also allows it to be running anywhere, separate grid, external logging service or where-ever. :)

We're still working on some of the items for 1.1 release so I'd say 1.2 is should be out in the end of February timeframe.

**Comment by kke** [comment]
An obvious protocl IMHO would be [syslog](https://tools.ietf.org/html/rfc5424).
