### ISSUE TITLE
Simplify PXE boot provisioning

### ISSUE THREAD

**Issue by faddat** [kontena/kontena#172]
make  a Virtualbox VM image or vagrantfile that sets up a PXE server and runs through a coreos bare metal master installation and then serves up coreos images for the nodes.  It's not so much that people can't do this, it's more that having it done in a known good configuration would really speed things along.

**Comment by jakolehm** [comment]
Cool idea! Have you done this already? If yes, can you contribute documentation / vagrantfile?

**Comment by faddat** [comment]
Here's as far as I've gotten: 

https://github.com/danderson/pixiecore
https://github.com/faddat/k8sinstallmetal2finished/blob/master/metal

It's certainly not all the way there yet.  One of the things that I had difficulty with was:

 * What is the recommended deploy spec for Kontena?

One of the reasons (at least, it's my reason) people need cluster managers is a shift away from the high fixed monthly costs of the public cloud.  (but there are plenty of other good reasons, too!)

**Comment by jakolehm** [comment]
Just drafted coreos userdata for kontena-master + pixiecore (totally untested): https://gist.github.com/jakolehm/07de4f8b14cdd4a1aeb4
Hope this gives some ideas how it could work.

About the deploy specs, don't know what you mean exactly but kontena master is running quite ok with smallest digitalocean droplet (1 cpu, 512MB memory). For nodes we recommend 1024MB or more.

**Comment by faddat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Cool!  So that is part of it, yes.  I had no idea that kontena is so
small.  Also, I want to let you know about my use case some, because
other orchestrators, like k8s & mesosphere seem inappropriate for it
(mesosphere > kubernetes) I'm expecting that 1 container will have
1-10 users, as in apps generally don't need to scale.

K8s spends so much effort on smooth scaling that it becomes rather
cumbersome if you expect to have, say, a ton of single user pods.  I'm
pretty curious what direction you plan on taking Kontena in.  At the
moment (literally) I'm playing with vamp+mesosphere, but I'd be glad
to give Kontena another whirl.  I like that you've got a full solution
stack put together.

Ps.

Are you using weave at some level?

Best,
- -Jake

On 10/4/15 11:52 PM, Jari Kolehmainen wrote:
> Just drafted coreos userdata for kontena-master + pixiecore 
> (totally untested): 
> https://gist.github.com/jakolehm/07de4f8b14cdd4a1aeb4 Hope this 
> gives some ideas how it could work.
> 
> About the deploy specs, don't know what you mean exactly but 
> kontena master is running quite ok with smallest digitalocean 
> droplet (1 cpu, 512MB memory). For nodes we recommend 1024MB or 
> more.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/kontena/kontena/issues/172#issuecomment-145366027>
.
>
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJWEWIoAAoJEOz3hbjUn3si0VkP/2UfN+RYClNQ8NfkHQk+AtNm
C57L/jKpsDdkwncORI9GSVpA/u32+TWUk4ZiKsJAtrs1FH3Uirw5rEkvEJ1x+AkI
uYXGQplMbUEr6G3LA3RPqSMTxcuZWJO3tZay5E2WRxvWrjY1XwnGVAoRwUzuw0MH
gklrBezy5ckPRREXYE6g0GXBlHEsnUsS6MLj4JtnhyCYty7AUsMFPWgjsj0l6Rda
DAMRDAl4ENZmXc31d9JzWbqPrF1zxFZ+3DuhrRehRNVz5vQE4PCwFmQbqy3zu3XU
iXS5XbsfQwDBG313KJ/mgmBS98EZ9zASONXQRRgbCO9Aa2k99xvVXtCTc9D6zRAk
6vJI2/9/uCwI6ES3s3ikAr8wnDGBq4OqbRpKPSrMokvayZpxlnfnH8eceUXwCrey
WT88Q7HBU0hs+DXwV9nl6o/1/xtRGHcy0zQGnNUb7xD1T2SGt4xkr/f6ybgo/nn1
PliDD1jcft9zy02/QejWFu3b5v9R54l/BljwcFyEK5hlxuwPz2Vx/hklvGEwV0xQ
SrDYbwt7UEUQsF7dwoXqjRQqGnDUfMSxp/Zv+WsL66DwS2DJw5yNnGcZFAL7X12K
bzUP85PdMArFfW0LK9hBj9cGITel81nuf9FKNcz6bAUOAJizZ4PGwAElxNt2qSBz
ub5P6Bm7vf8Kz+63voMB
=HbNx
-----END PGP SIGNATURE-----

**Comment by jakolehm** [comment]
Full solution stack (that is easy to install & use) is indeed important goal for Kontena. Most projects don't need complexity of k8/mesos or the operational overhead that comes with many of these tools.

And yes, Kontena uses Weave as an overlay network. Weave (and dns) is automatically started/configured on each node that connects to Kontena Grid.

**Comment by faddat** [comment]
I have a feeling that I was talking about things like:

 * Node to master ratio
 * Multi-Cloud compatiblity (how tightly is the cluster coupled)
 * Topology
 * Best practices for Kontena.
 * Maximum size (in terms of nodes)
 * Maximum size (in terms of services)

One of the things I find kind of hilarious about working in this space
is that each product I've encountered requires a solid hour's use before
I can even define what it is intended to do!  Generally:  Why, it runs
containers, on several computers, which you or a "cloud" company owns....

Specifically:  It has N characteristics.... <blablabla>

Thanks!

-Jake

**Comment by faddat** [comment]
This issue is more or less solved if #367 is resolved, so I'm going to close this and append the PXE info to that.
