### ISSUE TITLE
kontena registry create uses the wrong API when checking for existing registry service

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1724]
```ruby
      registry = client(token).get("services/#{current_grid}/registry") rescue nil
      exit_with_error('Registry already exists') if registry
```

The URL is missing the stack, the response is always HTTP 404, and this check never fires:

```
[API Client Request]: GET http://localhost:9292/v1/services/development/registry | Headers: {Accept: application/json, Authorization: Bearer} 
[API Client Error]: 
D, [2017-01-25T14:56:52.444247 #4024] DEBUG -- CLIENT: Request GET /v1/services/development/registry: 404 Not Found: 
D, [2017-01-25T14:56:52.444363 #4024] DEBUG -- CLIENT: JSON parse exception: 743: unexpected token at '' : 743: unexpected token at ''
```

Instead it fails on the POST later on:

```
D, [2017-01-25T14:56:52.800295 #4024] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"name":"registry already exists"}}
bundler: failed to load command: bin/kontena (bin/kontena)
Kontena::Errors::StandardError: {"name"=>"registry already exists"}
```

This is mostly cosmetic, and harmless, the resulting error just looks different:

```
 [error] {"name"=>"registry already exists"}
```

We could probably just remove the starting check?

**Comment by kke** [comment]
rescue nil wins again

**Comment by SpComb** [comment]
The check for the `registry` service might actually be a feature, not a bug, since it will prevent the `kontena registry create` command from creating a new `registry` stack if there already is an existing pre-1.0 `registry` service in the grid?

**Comment by SpComb** [comment]
Marking as invalid because it seems like the check for the legacy `registry` service before creating the `registry` stack is a useful feature, not a bug. Ping @jakolehm?
