### ISSUE TITLE
cloud: Adding admin user to a new master fails

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1730]
![login_ _kontena_cloud_and_13_95_9_253_and_kontena_cloud](https://cloud.githubusercontent.com/assets/3893/22403356/fa3ae82e-e61c-11e6-8412-3e7ddfa6a8fa.png)

Happened twice today -- not sure of the exact repro steps. Maybe: browser has not logged in to Kontena cloud -> add admin -> this.

**Comment by nevalla** [comment]
Thanks for reporting this. I think I have identified the issue and fixed that. Please reopen if you still face this issue.
