### ISSUE TITLE
weave is kinda slow

### ISSUE THREAD

**Issue by derDieDasJojo** [kontena/kontena#175]
I consider using kontena, but i read an article that says that you loose 94% of the bandwidth by using weave, wich is used by kontena:
http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/

if i loose 94% of my bandwidth by using kontena it doesn't seem to make much sense to me using kontena.
did you make any performance tests with kontena ?
do you consider switching from weave to flannel (and add vpn-support to flannel)?

**Comment by jakolehm** [comment]
Yes, we have benchmarked weave and in our tests it is only 15-20% slower. If you have really high-performance networking needs this might not be acceptable.. but usually it's good enough.

Flannel is faster if you use vxlan backend but there are currently too many tradeoffs for us. One is that Flannel requires etcd to boot, we start etcd only after the overlay network is up (etcd is protected by weave/overlay network).
