### ISSUE TITLE
Ubuntu xenial dpkg-reconfigure is broken

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1750]
The Ubuntu xenial `kontena-server` and `kontena-agent` dpkg `postinstall` scripts only work for an initial install, where they configure the commented defaults:

```sh
# Fetching configuration from debconf
db_get kontena-agent/server_uri
URI="KONTENA_URI=${RET}"
sed -i -r "s#\#KONTENA_URI=.*#${URI}#" /etc/kontena-agent.env

db_get kontena-agent/grid_token
TOKEN="KONTENA_TOKEN=${RET}"
sed -i -r "s#\#KONTENA_TOKEN=.*#${TOKEN}#" /etc/kontena-agent.env
```

Using `dpkg-reconfigure kontena-*` to re-run the postinst script will prompt with the previous value stored in debconf (?), but using the prompt to change the value will not have any effect on the actual `/etc/kontena-*.env` configuration or running systemd services.

Does this debconf prompting also happens on package upgrades?

Best option may be to just skip the debconf prompts for anything except the initial install. Alternatively, we have to write out the shell-gunk to load the existing `.env` values, and the enhance the sed-magic to update the values.

**Comment by japsu** [comment]
It would be nice to be able to update these values with `dpkg-reconfigure kontena-agent`.
