### ISSUE TITLE
Set node labels from kontena-agent container labels

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1771]
Currently setting node labels is cumbersome:

```
$ cat > /etc/docker/daemon.json <<DOCKERCONFIG
{
  "labels": ["region=<name_here>"],
  "insecure-registries": ["10.81.0.0/16"]
}
DOCKERCONFIG
```

or cloud-init...

Let's be awesome and take node labels from `kontena-agent` ! wohoo!

**Comment by SpComb** [comment]
Would the `KONTENA_NODE_LABELS` env in #2590 also be acceptable?

**Comment by matti** [comment]
@spcomb yes, that’s better
