### ISSUE TITLE
Add --force flag to kontena stack deploy

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/kontena#1782]
If `--force` flag is used, then the kontena agent should use `--force` flag when removing docker containers.

This would make kontena usable with RHEL and the DeviceMapper storage driver, since the kontena agent often can't remove a container, but the containers can be removed using the `--force` flag.

**Comment by panuhorsmalahti** [comment]
See: https://github.com/kontena/kontena/pull/1196/files

**Comment by jnummelin** [comment]
Using force in container remove can be problematic as it can cause `dead` containers. see https://github.com/docker/docker/issues/26372

Maybe this is more environment specific issue, so maybe the config could be made on agent level. So some kind of a ENV flag that could be set if the containers need to be removed with force or not. 

/cc @jakolehm

**Comment by panuhorsmalahti** [comment]
Yeah, I was actually just thinking that :). It should be an ENV flag since there can be different pathways to the `rm` command in any case.

In our case *not* using --force actually causes `Dead` containers, since using rm without --force causes docker to error out with devicemapper related "device in use" errors.

An "uglier" workaround (but more robust) would be to use unique names for the containers, e.g. "my-stack/my-service-<random id>", so that even if the agent fails to remove the container, at least a new one can be created and the service can continue to run.. at that point it's up to the admin to notice these Dead containers and remove them manually. In any case the paramount issue here is how we can guarantee that Kontena keeps the services up and running.

**Comment by SpComb** [comment]
The agent has a "ContainerCoroner" that will cleanup the state for dead containers once they disappear. IIRC this is used for the newer Docker versions which have some form of deferred deletion on container remove errors, but I can't remember the exact details off-hand: https://github.com/kontena/kontena/pull/1289

Bottom line is that the workarounds needed for storage driver  `docker rm` errors unfortunately vary a lot between platforms and Docker versions, I don't think adding a CLI `--force` is going to solve them, just cause even more confusion.

It needs a good understanding of the underlying bugs and the required workarounds, and then we should implement those in the agent for the platforms that we support. Let's track the general mountns confusion stuff in #1668, and the RHEL device-mapper issues in #1631 (or some new related issue).
