### ISSUE TITLE
Some error / debug messages duplicate the message

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1812]
There are several pieces of code that do something along the lines of:

```ruby
logger.debug "#{$!} #{$!.message}"
```

That seems to output the same message twice.

**Comment by SpComb** [comment]
There should be a

```ruby
do
    ...
rescue => error
    logger.exception "Failed to asdf: #{error}"
end
```

that handles logging the backtrace and stuff. There's a ridiculous amount of repeated `exc.backtrace.join("\n")` throughout the codebase: https://github.com/kontena/kontena/search?utf8=%E2%9C%93&q=backtrace+join&type=Code
