### ISSUE TITLE
kontena [stateful?] stack rm does not remove volumes

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1817]
```
kontena stack install matti/gogs
# configure gogs
kontena stack rm --force gogs
kontena stack install matti/gogs
# gogs still configured (volumes were not deleted)
```

**Comment by jnummelin** [comment]
How did you define the volumes, or did you just specify `stateful` flag?

**Comment by matti** [comment]
Like this https://github.com/kontena/kontena/issues/1818

**Comment by kke** [comment]
I guess stack rm would then need `--no-remove-volumes` or something in case you want to keep it.

**Comment by matti** [comment]
`--keep-volumes` :)

**Comment by matti** [comment]
on the other hand
```
volumes:
  - /data
```

are destroyed.

not sure how kontena should behave.

**Comment by colinmollenhour** [comment]
I've *definitely* needed to remove a stack before without removing the named volumes that go with it. I think "keep" should be the default and an option like "--remove-named-volumes" would be appropriate to make it clear that it only applies to named volumes (unnamed are already destroyed which is fine by me)

**Comment by SpComb** [comment]
Needs explicit support for stack-level volumes (#1803) to consider support for actually deleting volumes.

The current `volumes: foo:/foo` named volume thing is pretty much an accidential feature passed through as-is to Docker, not something that Kontena actually recognizes.

**Comment by SpComb** [comment]
With Kontena 1.2 and explicit stack volumes, this should now work for basic `local` volumes. The `kontena stack rm` will terminate and remove the services using those volumes, allowing the `kontena volume rm` command to be used to destroy the actual volumes.
