### ISSUE TITLE
Volumes should have stack prefix?

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1818]
stack with:
```
volumes:
  - postgres_data:/data
```

creates a docker volume `postgres_data` that will conflict with other stacks that have the same `postgres_data` name?

**Comment by kke** [comment]
You could use:

```yaml
volumes:
  - ${STACK}_postgres_data:/data
```

**Comment by matti** [comment]
I could, I don't think user should.

**Comment by matti** [comment]
okay, maybe this is more of a docker "issue" than kontena

**Comment by SpComb** [comment]
Issue for explicit stack-level volumes support: https://github.com/kontena/kontena/issues/1803
