### ISSUE TITLE
brew cask install kontena-cli

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1825]
🍺  for the brave individual who makes this happen

**Comment by kke** [comment]
Seems to work:

```
$ brew tap kke/kontena-cli-cask
$ brew cask install kontena-cli
```

need to test a bit more before trying to get it into the official library.

**Comment by jakolehm** [comment]
This is great! Do we really need a formula for the non-installer version? What is the benefit?

**Comment by kke** [comment]
Well then you could just `brew install` instead of `brew cask install`.  

Btw `brew cask uninstall kontena-cli` works with this formula too.

**Comment by matti** [comment]
@kke 🍻  deserved

**Comment by kke** [comment]
Cool PR number 👌

**Comment by kke** [comment]
Another benefit of non-cask brew install would be that installing wouldn't require your password.

**Comment by kke** [comment]
And the main benefit: they didn't accept the installer.

https://github.com/caskroom/homebrew-cask/pull/30000#issuecomment-278943956
😢

**Comment by matti** [comment]
>Please submit it first to Homebrew/core and only if they don’t accept it, submit here (linking back to the pull request where it was refused).

@kke could this be submitted to homebrew core, without the installer?

**Comment by kke** [comment]
Yes. I already have a recipe but haven't yet reopened the PR.

`brew tap kke/kontena-cli` 
`brew install [--HEAD] kontena-cli`

**Comment by kke** [comment]
Closed in https://github.com/Homebrew/homebrew-core/pull/19497

Just `brew install kontena`
