### ISSUE TITLE
kontena stack rm --force hangs

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1836]
with: 1.1.1 & 1.1.0
```
kontena stack install matti/lb-ingress
kontena stack install matti/sentry
# .. wait until booted up
kontena stack rm --force sentry
# always hangs, rerun works almost immediately
```

Once I also got this on the second try
```
 [fail] Removing stack sentry
 [error] invalid_token
```

**Comment by SpComb** [comment]
Would you still have a chance to look for any errors in the Kontena master logs from around the same time?

**Comment by matti** [comment]
It kinda puzzles me that you haven't seen this?

While developing these `kontena stack reg search | grep matti | wc -l` --> 20 stacks I've been removing an installing **a** **lot** and I'd say that ~13.32% of rm --force's have hanged. I'm so used to it that I usually just hit ctrl+c after removing has been taking more than 5s because then it has prob. hanged. Then when I issue the command again and it completes in less than 2 seconds.

So here's a repro that worked 1min ago:

`$ kontena stack install matti/selenium` --> creates services that depends_on

Wait for deploy to complete

`$ kontena stack rm --force selenium`

--> hangs and in the logs:

```
I, [2017-02-22T10:21:41.963815 #94]  INFO -- GridServiceDeployer: service lol/selenium/node-chrome-debug has been deployed
172.27.0.1 - - [22/Feb/2017:10:21:57 +0000] "DELETE /v1/stacks/lol/selenium HTTP/1.1" 200 2 0.0993
E, [2017-02-22T10:21:57.084326 #94] ERROR -- StackRemoveWorker: Cannot remove service lolgyver/selenium/hub: {"service"=>"Cannot delete service that is linked to another service (node-chrome-debug, node-firefox-debug)"}
```

--> then issuing another stack rm works&completes in ~1.3seconds.

**Comment by SpComb** [comment]
Right, the `DELETE /v1/stacks/:grid/:name` API error case is indeed broken, as the removal happens asynchronously, and the HTTP 200 response only means that it has asked the `StackRemoveWorker` to remove the stack.

The actual sync stack removal will only log an error on service removal, and leave the stack in place with the failed-to-remove services. The CLI spins until `GET /v1/stacks/:grid/:name` returns HTTP 404, which doesn't happen.

The reason that running `kontena stack rm` a second time succeeds is that the service removal failures on inter-service links are order-dependent. The server tries to sort the services in the correct order for removal, but apparently that sorting is broken.

So this is a combination of three things:

* The `StackRemoveWorker` removes linked stack services in the wrong order
* The `DELETE /v1/stacks/lol/selenium`  -> `Stacks::Delete` errors are limited to pre-validation errors, and not the actual  `StackRemoveWorker' errors
* The CLI `kontena stack remove` assumes that a succesful delete will cause GET to return 404, which is not necessarily the case

**Comment by SpComb** [comment]
@jakolehm is there any particular reason for the `Stacks::Delete` to happen asynchronously via the `StackRemoveWorker`? Could we fix the error case and remove the need for CLI stack polling by just having the server do the `DELETE` synchronously?

**Comment by SpComb** [comment]
Fixed the `StackRemoveWorker` linked service sorting in #1887
