### ISSUE TITLE
kontena app init insinuates false defaults.

### ISSUE THREAD

**Issue by chav02** [kontena/kontena#184]
[the \[Yn\] notation](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/apps/init_command.rb#L41) is normally used to signal that default behaviour achieved with empty input is "Y".

The method (as well as it's sibling a few lines down) should either output [yN], or accept empty string as a positive response.

**Comment by jakolehm** [comment]
Fixed in #185
