### ISSUE TITLE
Interactive prompts crash on Windows

### ISSUE THREAD

**Issue by sampeson** [kontena/kontena#1841]
I cannot create master node in Windows 10 and it fails in creation phase. There is workaround to specify this configuration as command line parameters. See attached output for additional info:
[problem_output.txt](https://github.com/kontena/kontena/files/766726/problem_output.txt)

Workaround:
[workaround.txt](https://github.com/kontena/kontena/files/766727/workaround.txt)

Versions:
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

$ gem --version
2.6.7

$ gem list --local
addressable (2.5.0)
bigdecimal (default: 1.2.8)
clamp (1.1.1)
did_you_mean (1.0.0)
equatable (0.5.0)
excon (0.55.0, 0.49.0)
hash_validator (0.7.0)
io-console (default: 0.4.5)
json (default: 1.8.3)
kontena-cli (1.1.1)
launchy (2.4.3)
liquid (4.0.0)
minitest (5.10.1, 5.8.3)
necromancer (0.3.0)
net-telnet (0.1.1)
opto (1.8.3)
pastel (0.7.1)
power_assert (1.0.1, 0.2.6)
psych (default: 2.0.17)
public_suffix (2.0.5)
rake (12.0.0, 10.4.2)
rdoc (default: 4.2.1)
retriable (3.0.0, 2.1.0)
ruby_dig (0.0.2)
rubygems-update (2.6.10, 2.6.7)
safe_yaml (1.0.4)
semantic (1.6.0)
test-unit (3.2.3, 3.1.5)
tty-color (0.4.2)
tty-cursor (0.4.0, 0.3.0)
tty-prompt (0.10.1)
wisper (1.6.1)

$ kontena --version
kontena-cli 1.1.1 [ruby2.3.1+x64-mingw32]

$ kontena plugin list
NAME                                     VERSION    DESCRIPTION
aws                                      0.2.5      Kontena Amazon Web Services plugin
vagrant                                  0.2.6      Kontena Vagrant plugin

**Comment by kke** [comment]
(related: https://github.com/piotrmurach/tty-prompt/issues/31)

**Comment by kke** [comment]
Noted during testing: Prompts with timeouts don't seem to react to enter, you have to wait until it reaches 0

Otherwise, looks like it works for me:

## 1
![image](https://cloud.githubusercontent.com/assets/224971/22828379/9281091a-efa5-11e6-8fec-f02882e3a3c8.png)

## 2
![image](https://cloud.githubusercontent.com/assets/224971/22828385/a3983714-efa5-11e6-8835-20ff1b53349f.png)

## 3
![image](https://cloud.githubusercontent.com/assets/224971/22828410/c80fecb8-efa5-11e6-91f7-8050c4eb0491.png)
(what's wrong with packet plugin?)

**Comment by piotrmurach** [comment]
@kke The `tty-prompt` master branch provides support for Windows now :smile: Pretty much all prompts should work as expected. I would appreciate help testing examples on Windows which would speed up releasing new version.

**Comment by kke** [comment]
@piotrmurach select, multi_select, ask, yes? all seem to work just fine and cursor keys too… whaaaaaaat? :D got to check how you did that.

Running windows 10 in a virtualbox vm myself, you can get the image for free [from microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) no questions asked.

**Comment by piotrmurach** [comment]
@kke Released `0.11.0` with Windows support and many fixes. Please let me know if it resolves this issue.
