### ISSUE TITLE
kontena stack upgrade stackname searches for kontena.yml

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1844]
```
kontena stack upgrade lb-ingress

 [done] Reading stack lb-ingress metadata from Kontena Master
 [error] No such file or directory @ rb_sysopen - /Users/mpa/dev/kontena-compose/kontena.yml
         Rerun the command with environment DEBUG=true set to get the full exception
```

Shouldn't it upgrade from the original stack instead?

**Comment by matti** [comment]
I can also see why it searches kontena.yml, but I think that if it has been installed from a registry stack it should follow that..?

**Comment by jnummelin** [comment]
@kke Do we have the "metadata" stored to figure out from where the stack was installed?

**Comment by SpComb** [comment]
The server knows about the `registry` and `stack_name`, but it looks like the CLI's `stack_from_yaml` is currently [hardcoded](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/stacks/common.rb#L74) to use `{ 'registry' => 'file://' }`, which breaks the automatic `kontena stack upgrade` usecase.

**Comment by kke** [comment]
Yeah the hardcoding in stack_from_yaml is a bug. The registry url is returned by the yaml reader at https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/stacks/yaml/reader.rb#L124 but stack_from_yaml overwrites it.
