### ISSUE TITLE
Normalize whitespace in generated `haproxy.cfg` for easier debugging

### ISSUE THREAD

**Issue by japsu** [kontena/kontena#1858]
Now a moderately sized loadbalancer configuration has hundreds of empty lines, making it hard to read. After rendering the `confd` template, whitespace should be normalized according to simple rules, eg. empty lines removed and single empty lines added before `defaults`, `listen`, `backend` etc.

Or the template could be improved to not create extra empty lines, but that would probably be more tedious than post-processing the generated file.

**Comment by SpComb** [comment]
`confd` 0.11.0 is compiled with an older version of Go that doesn't yet support the `{{- ... -}}` syntax to elide surrounding whitespace, so fixing the `kontena-lb` haproxy confd template would involve upgrading to the "newer" 0.12 alpha releases.

**Comment by jakolehm** [comment]
Fixed in https://github.com/kontena/kontena-loadbalancer/pull/27
