### ISSUE TITLE
Stack validate should not require current master

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1886]

**Comment by SpComb** [comment]
Please unassign if not working on this for 1.2

**Comment by kke** [comment]
It's a bit problematic.

I would not expect `validate` to read from the master and especially not to write anything to the vault. It should just do a simple syntax validation and not ask any questions.

**Comment by SpComb** [comment]
Indeed, the side effects of things like `to: vault` would be a bit surprising when using `kontena stack validate`.
