### ISSUE TITLE
ServiceBalancerJob loop on partially stopped services

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1892]
If a service is `state: running` but has `status: stopped` containers, the server `ServiceBalancerJob` will attempt to rebalance it. Rebalancing a service triggers a `GridServiceDeploy`, which invokes the agent `Kontena::ServicePods::Creator` for each instance.

The `Kontena::ServicePods::Creator` considers the stopped service container as up-to-date, and the deploy succeeds.

The action of deploying a stopped service instance does not start the service container, and so the loop continues.

**Comment by SpComb** [comment]
This can happen if you `kontena service stop`, and then `kontena service start` while some nodes are offline. The offline agents will miss the start RPC.

**Comment by cooperaj** [comment]
I don't know if this is related but I have a ServiceBalancerJob looping away on my loadbalancers.

```

**Comment by SpComb** [comment]
That case is probably https://github.com/kontena/kontena/issues/1895 

There seem to be multiple independent causes for this kind of behavior.

**Comment by SpComb** [comment]
Fixed by #1873, the agent will now independently re-start any stopped services that should be running.
