### ISSUE TITLE
Easy nodes provisioning through Kontena CLI

### ISSUE THREAD

**Issue by miskun** [kontena/kontena#19]
At the moment, Kontena installation is quite complex operation. Idea is to make it possible for users to provision Kontena Nodes on *any* cloud provider through cli with few simple commands.

**Comment by miskun** [comment]
**Proposed solution:**

Create cloud **provider** plugin architecture to support multiple cloud providers. Each plugin should implement necessary functions to:

* Provision, configure and install necessary cloud resources for Kontena Server
* Provision, configure and install necessary cloud resources for Kontena Node(s)
* Terminate above mentioned resources

Add new abstraction layer **cluster** for a server and add following cli commands:

* `kontena cluster create [cluster_name] [provider_name]` - Provision necessary resources and install Kontena Server on selected cloud provider
* `kontena cluster info [cluster_name]` - Retrieve information about the Kontena Server.
* `kontena cluster login [cluster_name]` - Associate cli with Kontena Server; store user credentials on local development environment
* `kontena cluster register [cluster_name]` - Register User to Kontena Server (if supported) 
* `kontena cluster forget [cluster_name]` - Remove stored user credentials from local development environment
* `kontena cluster use [cluster_name]` - Switch default kontena cli context to use selected server.

Finally, add nodes management to cli. E.g. `kontena nodes add [provider_name] [grid_name]` etc.

**Comment by digitalism** [comment]
Why not reuse existing solutions like [docker machine](https://docs.docker.com/machine/)?

**Comment by jakolehm** [comment]
Good point, we have been checking `docker machine` as one possibility to provision machines. Right now kontena installation needs something more than plain server + docker provisioning. Basically we need to install deb packages that do some configuration to host machine... this is not supported by docker machine and that's why we are implementing our own lightweight tool.

**Comment by digitalism** [comment]
I'm not sure that I understand why you depend on ubuntu. In comment https://github.com/kontena/kontena/issues/95#issuecomment-125208404, I showed how I started your existing Dockerfiles using `docker-compose up`. That means both the api server and the agent run in a container. Thus, from my point of view only a plain server + docker provisioning is required.
Am I missing something?

**Comment by jakolehm** [comment]
We don't directly depend on ubuntu but atm we provide packages only for ubuntu. Kontena includes something more than just plain containers, mainly etcd2 and weave. Etcd2 is included in CoreOS and Weave can be installed (or replaced with Flannel) but then agents will miss automatic node discovery and other cool stuff that's baked into ubuntu packages. If you want to port those features to CoreOS systemd (cloud-config) files, here is the ubuntu package magic: 
https://github.com/kontena/kontena/tree/master/agent/packaging/ubuntu 
https://github.com/kontena/kontena/tree/master/server/packaging/ubuntu

**Comment by jakolehm** [comment]
We have now provisioners for vagrant and digitalocean. Both are using coreos-stable. Should we close this?

**Comment by miskun** [comment]
yes. i think this issue can be closed. the current design fulfills the original idea. if we want more provisioning engines, we'll create issue for each one of them in the future.
