### ISSUE TITLE
kontena stack install {"registry"=>"Registry can't be nil"}

### ISSUE THREAD

**Issue by industral** [kontena/kontena#1913]
```
$ kontena stack install kontena.yml
 [fail] Creating stack website
 [error] {"registry"=>"Registry can't be nil"}
```

```
$ cat kontena.yml
stack: test/website
version: 0.1.0
services:
  website:
    image: my/my-image
```

```
$ kontena -v
kontena-cli 1.1.2 [ruby2.3.1+x86_64-linux-gnu]
```

**Comment by SpComb** [comment]
Have you upgraded your Kontena master server to 1.1.2?

This would be related to https://github.com/kontena/kontena/pull/1870 , which changed the way the stack `registry` field was used in `1.1.2`.

**Comment by industral** [comment]
@SpComb yeah you right. I have 1.1.1, but

```
$ sudo apt-get install kontena-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
kontena-server is already the newest version (1.1.1-1).
```

looks like don't have yet deb package with 1.1.2 version?

**Comment by SpComb** [comment]
Looks like those packages were indeed missing, see https://github.com/kontena/kontena/issues/1914

Pushed the missing Ubuntu xenial `1.1.2` packages manually..

**Comment by industral** [comment]
@SpComb Thanks! Works now!
