### ISSUE TITLE
bintray is missing Ubuntu xenial packages for 1.1.2

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1914]
The newest packages available on `https://dl.bintray.com/kontena/ubuntu/` are version `1.1.1-1` for xenial, and `1.1.2-1` for trusty.

**Comment by SpComb** [comment]
> @jakolehm terom: published those packages manually..

The Ubuntu xenial `1.1.2-1` packages should now be available on bintray..

**Comment by industral** [comment]
Thanks for such quick response! Works now!

**Comment by SpComb** [comment]
Caused by a lack of release automation: #1915
