### ISSUE TITLE
Travis does not publish Ubuntu packages automatically

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1915]
We should modify our release scripts so that Ubuntu packages are available immediately after release (and without manual approval).

**Comment by SpComb** [comment]
The current bintray uploads look like

```
curl -T ./release/xenial/kontena-server_1.1.2-1_all.deb -u... 'https://api.bintray.com/content/kontena/ubuntu/kontena-server/1.1.2/pool/main/k/kontena-server-1.1.2-1~xenial_all.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64'
```

The [bintray API](https://bintray.com/docs/api/#_upload_content) looks like:

```
PUT /content/:subject/:repo/:package/:version/:file_path[?publish=0/1][?override=0/1][?explode=0/1]


PUT /content/:subject/:repo/:file_path;bt_package=:package;bt_version=:version[;publish=0/1][;override=0/1][;explode=0/1]
```

So it may be enough to just add `;publish=1` to the curl PUT URL to automatically publish?

**Comment by SpComb** [comment]
The 1.1.3 release did not get pushed to bintray or published. This is because we had to invalidate our bintray tokens in travis...

**Comment by SpComb** [comment]
The 1.2.0.dev1 builds were successfully uploaded and published to http://dl.bintray.com/kontena/ubuntu `xenial/edge`.
