### ISSUE TITLE
AuthProvider configuration is invalid with multiple master processes or nodes

### ISSUE THREAD

**Issue by daniel-bytes** [kontena/kontena#1919]
Kontena server master nodes store oAuth related configuration in the `AuthProvider` class (`server/app/services/auth_provider.rb`).  The configuration is provided by a PATCH or PUT HTTP request to the config API (`server/app/routes/v1/config_api.rb`), generally sent from the cli `kontena master config import` command.

The issue is that this configuration is stored in memory as part of the `AuthProvider` class OpenStruct fields, and as a result will only be available for a single master node process after being set.  This is an issue for cli commands like `kontena master init-cloud`, which first set configuration and then initiate an oAuth authorization.

To recreate this issue, follow the steps in `development.md` on a system with more than one available CPU core (I was able to reproduce easily with 4 cores).  When you get to the `dontena master init-cloud --force` command you should see a failure.

**Comment by SpComb** [comment]
What kind of symptoms does this bug result in? Could this issue cause these kinds of random errors as in https://github.com/kontena/kontena/issues/1836

> Once I also got this on the second try
> ```
> [fail] Removing stack sentry
> [error] invalid_token
> ```
