### ISSUE TITLE
stack upgrade can be done with wrong kontena.yml

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1938]
Something like this: will "work"
```
git clone git@github.com:matti/kontena-stacks
cd kontena-stacks/lb-ingress
kontena stack install
cd ../weavescope
kontena stack upgrade lb-ingress
```

I managed to craft a very specific kontena.yml that broke the master for good (http 500 for all requests)
```
kontena_master_1 | 192.168.81.1 - - [07/Mar/2017:08:56:13 +0000] "GET /v1/grids/vagrant/stacks HTTP/1.1" 500 35 0.0975
kontena_master_1 |
kontena_master_1 | NoMethodError (undefined method `to_path' for nil:NilClass
kontena_master_1 | Did you mean?  to_a):
```

**Comment by SpComb** [comment]
I was thinking about exactly this yesterday....

The server knows the `{ "stack": "matti/weavescope"}` for every installed stack... the `kontena stack upgrade` should prompt/`--force` if the upgrade stack does not match.

**Comment by SpComb** [comment]
Kommando was applied to great effect: https://github.com/kontena/kontena/blob/master/test/spec/features/stack/upgrade_spec.rb#L31

```ruby
    it 'prompts if the stack is different' do
      with_fixture_dir("stack/upgrade") do
        k = kommando 'kontena stack upgrade redis different.yml'
        k.out.on /Are you sure/ do
          k.in << "n\r"
        end
        k.run
        expect(k.code).to eq(1)
        expect(k.out).to match /Replacing stack.*Are you sure\?.*Aborted command/m
      end
    end
```

**Comment by SpComb** [comment]
> I managed to craft a very specific kontena.yml that broke the master for good (http 500 for all requests)

That looks like #1769 ?
