### ISSUE TITLE
Make `kontena vault read` scripting friendly

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1959]
In some cases it would be helpful to be able to script reading values from the vault but currently `kontena vault read KEY` outputs multiple lines and in a format that is not easy to parse for scripting. So, two suggested improvements:

1. Add a '--raw' option so that only the value is output to stdout
2. Any errors such as "Not Found" should go to stderr instead of stdout (this really goes for all commands I think)

**Comment by kke** [comment]
It already has `--value` which outputs the value only.

The error message output stream is fixed in #1963

**Comment by colinmollenhour** [comment]
Thanks, kke. Is that option documented in --help?  I don't recall seeing it.

**Comment by kke** [comment]
```
$ kontena vault read --help

Usage:
    kontena vault read [OPTIONS] NAME

Parameters:
    NAME                          Secret name

Options:
    --grid GRID                   Specify grid to use
    --value                       Just output the value  # <---- there
    -h, --help                    print help
    -D, --debug                   Enable debug (default: $DEBUG)
```
