### ISSUE TITLE
kontena node ssh to accept parameters

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1972]
ssh -F ...

**Comment by SpComb** [comment]
It's a bit of an accident of how the `clamp` argument parser works, but the `kontena node ssh X` command will actually accept arbitrary options and pass them on to the `ssh` command:

```
$ kontena node ssh core-01 -h
unknown option -- h
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]

$ strace kontena node ssh --private-ip -u core core-01 -v ls
execve("/usr/bin/ssh", ["ssh", "core@192.168.66.101", "-v", "ls"], [/* 67 vars */]) = 0
```

This also works for `kontena master ssh`, if you use something like `kontena master ssh -- -v foo` -> `exec(*["ssh", "core@localhost", "-v", "foo"])`.

---

There's actually a hidden bug here that should prevent this from working... The CLI SSH commands contain code to prevent any command options from being interpreted by SSH, but it's actually subtly broken, and doesn't actually insert the `--` argument.

```ruby
      commands_list.insert('--') unless commands_list.empty?
```
