### ISSUE TITLE
Authorization breaks silently on unverified accounts

### ISSUE THREAD

**Issue by aom** [kontena/kontena#1981]
I'm trying to authorize application but get:

![web_inspector_ _cloud_kontena_io_ _authorize_and_login_ _kontena_cloud](https://cloud.githubusercontent.com/assets/2383/23947400/48662e4a-0987-11e7-922b-251ba9e468a0.png)

When I try another browser I can't even log in:

![login_ _kontena_cloud](https://cloud.githubusercontent.com/assets/2383/23947415/605cd616-0987-11e7-8c93-4be89352c6cf.png)

After a refresh I actually was logged in but authorization still fails:

![login_ _kontena_cloud](https://cloud.githubusercontent.com/assets/2383/23947478/981a5fa6-0987-11e7-8a0b-3df0891dde28.png)

**Comment by aom** [comment]
Ah. There it is in the last screenshot in error console! A user error.

Can you convert this into a feature request:

"Tell user that that account is not verified if trying to authorize application with unverified account"

![login_ _kontena_cloud](https://cloud.githubusercontent.com/assets/2383/23947584/07a3b3ae-0988-11e7-839a-50985cc8eacf.png)

**Comment by nevalla** [comment]
Thanks for reporting this. This is definitely bug and will be fixed.

**Comment by SpComb** [comment]
@nevalla close if fixed?

**Comment by nevalla** [comment]
Fixed
