### ISSUE TITLE
vault update -command gets stuck at least with certain parameters

### ISSUE THREAD

**Issue by coodari** [kontena/kontena#2000]
Action:
* "kontena vault update --upsert test_var 1"
Expected result:
* test_var variable is created or updated with value 1 into vault
Observed result:
* Command prompt gets stuck and the action is not performed

Other:
* kontena version
  * cli: 1.1.5
  * master: 1.1.4
* Bug confirmed by @nevalla

**Comment by SpComb** [comment]
Fixed in #2045
