### ISSUE TITLE
Google OAuth 2.0 needs redirect URI to get an access token

### ISSUE THREAD

**Issue by johnnypea** [kontena/kontena#2015]
Exchange an authorization code for an access_token requires `redirect_uri` parameter (see https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code).

The `auth_provider.get_token` method only sends these parameters:
```
request_params = {
  grant_type: 'authorization_code',
  code: code,
  client_id: self.client_id,
  client_secret: self.client_secret
}
```

I think the authentication fails because of this and every time I try to authenticate against Google OAuth 2.0 I get "Authentication failed" message.

**Comment by kke** [comment]
Looks like the oauth2 rfc defines it as a required field too.
