### ISSUE TITLE
kontena stack build doesn't resolve other grid services

### ISSUE THREAD

**Issue by j-a-m-l** [kontena/kontena#2021]
I'm trying to install a dependency (private gem yet) when building a Rails app.

This is the interesting part of my Gemfile:
```ruby
gem 'project', git: 'git://web.git.grid.kontena.local/org/project.git'
```

I've tried to clone the project inside the Dockerfile too:
```Dockerfile
RUN git clone 'git://web.git.grid.kontena.local/org/project.git'
RUN git clone 'git://web.git.grid/org/project.git'
```

Both cases fail because name is not resolved ("Name or service not known").

I've tried terminating all my grid nodes and master and creating again, but the result is the same.

**Comment by jakolehm** [comment]
Where are you building your Docker image? If outside grid, do you have vpn connection open?

**Comment by j-a-m-l** [comment]
I'm using the Vagrant plugin, so I'm building the Docker image in the same computer that is containing the virtual machines.

VPN connection is open (I can access to other services through the load balancer, which is in another stack)

**Comment by SpComb** [comment]
The `kontena stack build` command will use the local Docker engine on the machine that you're running the CLI on, so the Docker containers must be able to resolve the `grid.kontena.local` names. The default Docker configuration should use the host machine's resolver configuration for the lookups.

When you have the VPN up, are you able to `ping web.git.grid.kontena.local` from your host machine, outside of Docker? If not, then there's something wrong with the OpenVPN connection.

(closing as out of date, re-open if needed)
