### ISSUE TITLE
Node went offline and came back online without labels

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#2025]
Another issue seemingly randomly occurred over the weekend.. I'm beginning to think the best way to run Kontena is to use it to launch all of your containers and then just kill the master until you need it again to deploy an upgrade.  :/

You can see in the attached logs where there was a node disconnection and then containers were removed. The services all have affinities and although the node is currently connected it is now missing the "app" and "frontend" labels that it had before. Looks like there are some unexpected Ruby exceptions, but I'm not a strong Ruby debugger so it wasn't obvious to me what the exact cause was.

Master/Node Version: 1.1.5
[kontena-server-api.txt](https://github.com/kontena/kontena/files/873032/kontena-server-api.txt)
[kontena-agent.txt](https://github.com/kontena/kontena/files/873033/kontena-agent.txt)

**Comment by SpComb** [comment]
Is this related to https://github.com/kontena/kontena/issues/1862#issuecomment-283482346, where service containers were terminated by the server while rebalancing? If those services were daemon-strategy with node label affinity, and your nodes were bouncing like this and temporarily showing up without labels?

**Comment by SpComb** [comment]
The `GridServiceDeployer: Unknown error (primary/galera/lb): NoMethodError undefined method `join' for nil:NilClass` exceptions getting logged are #1997 caused by the `GridServiceInstanceDeployer` `RpcClient::TimeoutError` errors missing a backtrace, and should be harmless.

**Comment by SpComb** [comment]
BTW, which named host node are those agent logs from?

However, what is presumably happening here is that the server will clean out nodes that it considers to have been disconnected for over an hour: https://github.com/kontena/kontena/blob/v1.1.5/server/app/jobs/node_cleanup_job.rb#L35-L41

This causes the server forget any node labels set with `kontena node label add`. The node will re-appear as a new node once it does re-connect, but it will not have any of the labels of the original node.

Workaround might be to configure those labels on the host node's Docker engine. Those labels will be picked up as kontena node labels when the node initially connects and is (re)created:

#### `/etc/docker/daemon.json`
```json
{
	"labels": [
		"test=label"
	]
}
```

**Comment by SpComb** [comment]
> BTW, which named host node are those agent logs from?

Let's deal with the bouncing nodes over in #1948

**Comment by colinmollenhour** [comment]
> Is this related to #1862 (comment), where service containers were terminated by the server while rebalancing? If those services were daemon-strategy with node label affinity, and your nodes were bouncing like this and showing up without labels?

IIRC there were zero service containers running when I checked "docker ps" on the node. The only containers running were Kontena Agent related. However, I currently don't have any services that do not use affinity.

**Comment by colinmollenhour** [comment]
> This causes the server forget any node labels set with kontena node label add. The node will re-appear as a new node once it does re-connect, but it will not have any of the labels of the original node.

Ahh I see. Why have such a short time before the node is forgotten? I would think you could always manually remove the node if you're replacing it but if a machine goes down due to whatever circumstance and comes back up I think I would not want it to ever be forgotten.

> Workaround might be to configure those labels on the host node's Docker engine. Those labels will be picked up as kontena node labels when the node initially connects and is (re)created:

Thanks, this is good to know as I was not aware that there was a relationship.

**Comment by SpComb** [comment]
> Ahh I see. Why have such a short time before the node is forgotten? I would think you could always manually remove the node if you're replacing it but if a machine goes down due to whatever circumstance and comes back up I think I would not want it to ever be forgotten.

Usecase for this is IIRC  autoscaling nodes, where transient nodes will appear and then get terminated on their own.

Agreed that the default 1h cleanup is way too fast. It would probably be better to require some kind of node labelling for those kinda of auto-cleanup usecases.
