### ISSUE TITLE
Inviting users is confusing (master + grid access needed)

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2054]
When an admin invites a "master_admin" to the master, there are no indications (or documentation) that also grid access should be given.

More confusingly the new admin can run `$ kontena service ls`, but not `$ kontena service show` - also stack install will work although the install will give an error.

**Comment by SpComb** [comment]
Fixed in 1.2 #1970: `master_admin` role is equivalent to `kontena grid user` access.
