### ISSUE TITLE
Stack upgrade / Service update will not re-deploy service on removal of embedded objects

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2109]
Kontena 1.1 had an issue where every `kontena service update` or `kontena stack deploy` for a service with links to other services would consider the service as changed, and cause the service containers to be re-deployed. This happens because the embdded `GridServiceLink` documents were being re-created with a new mongo ObjectID on every update: #2090

However, fixing the `GridServices::Update` to keep the existing embedded objects unchanged in #2097 introduces a second bug, whereby removing embedded objects from the service will not cause mongoid to consider the service as changed, and will not touch the `updated_at` timestamp on `save`. This means that the service containers will not be re-deployed if multi-valued service fields stored as embedded mongo documents are removed. This affects all of the following service properties:

* hooks 
* links
* secrets
* volumes

The update will be reflected in `kontena service show`, but the container will still be running with the old hooks/secrets/volumes. Use `kontena service deploy --force` to re-deploy the container, and remove the hooks/secrets/volumes from the actual container configuration.

**Comment by SpComb** [comment]
Needs testing if fixed by the #2257 mongo/mongoid upgrade

**Comment by SpComb** [comment]
Unfortunately this still seems to be the case with the newer mongoid version:

```
D, [2017-05-26T16:59:39.575577 #13272] DEBUG -- GridServices::Update: service secrets input: [{"secret"=>"test-secret", "name"=>"TEST_SECRET"}]
D, [2017-05-26T16:59:39.575917 #13272] DEBUG -- GridServices::Update: service secrets pre: [#<GridServiceSecret _id: 59282dfbde3578267a288517, secret: "test-secret", name: "TEST_SECRET", type: "env">, #<GridServiceSecret _id: 592834bade357833d6e274a5, secret: "test2", name: "TEST_SECRET2", type: "env">]
D, [2017-05-26T16:59:39.576228 #13272] DEBUG -- GridServices::Update: service secrets post: [#<GridServiceSecret _id: 59282dfbde3578267a288517, secret: "test-secret", name: "TEST_SECRET", type: "env">]
D, [2017-05-26T16:59:39.578075 #13272] DEBUG -- GridServices::Update: not updating service development/test-secret/foo without changes
```

**Comment by jnummelin** [comment]
@SpComb Did I get it right, this affects only "direct" service commands and not stack upgrades?

**Comment by SpComb** [comment]
> @SpComb Did I get it right, this affects only "direct" service commands and not stack upgrades?

This affects the `GridServices::Update` `changed?` logic, which is used for both `kontena service update` and `kontena stack upgrade`, so yes, it also affects stack upgrades.

Removing a service secret will remove it from mongo, but it will not re-deploy the service because it doesn't consider it as changed.

**Comment by jnummelin** [comment]
But `kontena stack upgrade` does a `deploy` automatically, so it kinda works over this

**Comment by jnummelin** [comment]
Not saying we shouldn't fix this, just trying to grasp the criticality :)

**Comment by SpComb** [comment]
> But kontena stack upgrade does a deploy automatically, so it kinda works over this

Yes, I meant force-deploy. It seems like the `GridService.save` doesn't touch `updated_at` either, so the containers do not get re-created on the deploy, as the agent ServicePodWorker considers them up to date.

```
$ cat test/test.yaml
stack: test/test-secret
services:
  foo:
    image: redis
    secrets:
      - type: env
        secret: test-secret
        name: TEST_SECRET
$ kontena stack upgrade test-secret test/test.yaml 
 [done] Reading stack test-secret metadata from Kontena Master     
 [done] Upgrading stack test-secret     
 [done] Triggering deployment of stack test-secret     
 [done] Waiting for deployment to start     
 [done] Deploying service foo     
$ kontena service show test-secret/foo
  ...
  secrets: 
    - secret: test-secret
      name: TEST_SECRET
      type: env
  ...
$ kontena container inspect core-01/test-secret.foo-1 | grep TEST_
      "TEST_SECRET=foo1",
      "TEST_SECRET2=asdf",
```

**Comment by jnummelin** [comment]
Ah, true. Missed the part in the description that mentions this affects only removing enbedded models. :/
