### ISSUE TITLE
Package Kontena cli with something like traveling ruby

### ISSUE THREAD

**Issue by istvano** [kontena/kontena#2161]
Hi,

I am really impressed with the project it looks great!. I am a developer and I started a habbit few years ago that I try to not install any dev dependencies on my laptop. 
I use vagrant for all the development so the only dependency I have is vagrant and virtualbox. This makes it extremelly easy to work across several laptops, computers etc. 

I wanted to try kontena but it needs a Ruby installed. I did not wish to install Ruby for several reaons.
I was wondering if there is an easy way to create a portable environment for Kontena CLI

There is a great article from Phusion I think that might be somehow relevant.
https://github.com/phusion/traveling-ruby#end_user_problems

I would like to ask for a feature request that the CLI comes bundled with something like traveling ruby 
http://phusion.github.io/traveling-ruby/

This would make it more like Vagrant that has it's embeded ruby and gems pacakged together. 

I am not a Ruby person. I have more like a Java background but I though it would be a good feature.

Let me know what you think.

Kind Regards

**Comment by SpComb** [comment]
The kontena releases include a `kontena-cli` omnibus installer for OS X: https://github.com/kontena/kontena/releases (1.2.0.rc2 is cooking ATM and should be available soonish)

**Comment by istvano** [comment]
Hi,

thanks a lot for getting back to me.
 I saw the OS X one which is great! Although I am a windows users with Cygwin hence I was hoping for a cross-platform installer. I saw 1.2 provides better volume support which is actually somethign I also need! 
it is very exciting!

**Comment by jakolehm** [comment]
We also provide cli as Docker image, see:
- https://hub.docker.com/r/kontena/cli/

And unofficial wrapper script:
- https://github.com/matti/contena

**Comment by SpComb** [comment]
Tracking missing Omnibus installers for other platforms with specific issues:

*  Missing CLI omnibus installer for Windows #2307 
*  Missing CLI omnibus package for Ubuntu #1954
