### ISSUE TITLE
Unresolvable statsd endpoint crashes NodeInfoWorker

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2165]
```
I, [2017-04-17T10:31:56.996052 #1]  INFO -- Kontena::Workers::NodeInfoWorker: exporting stats via statsd to udp://this-does-not-exist.kontena.local:8125
E, [2017-04-17T10:31:56.998093 #1] ERROR -- : Actor crashed!
SocketError: getaddrinfo: Name does not resolve
```

**Comment by SpComb** [comment]
I'm guessing this has always caused the `NodeInfoWorker` to crash, but now with the observable, that crash is stopping the other workers from seeing the node info, because it happens before the `NodeInfoWorker#update_observable`.

**Comment by jakolehm** [comment]
@SpComb yes, now agent is halted if this kind of error occurs. I already refactored stats related bits to a separate actor in #2166 (should be safer and more clear)
