### ISSUE TITLE
Service with newer image is not deployed without force

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#2171]
Kontena Agent is not checking is image updated when doing deploy, this results to situation that service which has only image updated (no changes in configuration) won't be deployed without `--force` option.

**Comment by SpComb** [comment]
Probably introduced by #1873: https://github.com/kontena/kontena/pull/1873/files#r105346920

> This skips the `service_container.config['Image'] != service_pod.image_name` and `image_outdated?` checks in the `Kontena::ServicePods::Creator#service_uptodate?`
