### ISSUE TITLE
Server node plugin/unplug can race on delayed WebsocketBackend open/close events

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2183]
In a scenario where the server `EventMachine` threads are severely delayed  and the agents are reconnecting often (https://github.com/kontena/kontena/issues/1948#issuecomment-289705215), it is possible for different server WebsocketBackend workers to process sequential websocket connection events out of order:

```
I, [2017-03-27T00:52:47.075842 #7]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
I, [2017-03-27T00:52:47.480824 #11]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
I, [2017-03-27T00:53:08.492946 #7]  INFO -- WebsocketBackend: node closed connection: app3
```

This leas to a condition where the agent has an active connection open, but the `HostNode` is marked as disconnected on the server. This condition seems to be caused by a race between two different server worker WebsocketBackends first plugging in the node on a websocket open, and then unpluggging the node on a websocket close. This race seems to be triggered when the agent's WebsocketClient considers the connection be closed and reconnects before the slow server worker's WebsocketBackend has processed the close of the original connection. If the new websocket connection goes to a different server worker, that faster WebsocketBackend might processes the connect event before the slower worker has processed the close event. That leaves the agent websocket connection active, but the server HostNode disconnected.

This could potentially also happen when a server worker stalls for long enough for the agent to timeout and close the connection, open up a new connection, have a different server worker process the connection and re-plugin the node, before the stalled worker wakes up and notices that the old websocket connection is closed, and unplugs the node.

In Kontena 1.1, this condition would leave the agent connected but the host nodes offline (#1948), whereas in Kontena 1.2 the server has been fixed to forcibly disconnect the agent in this scenario, allowing the agent to reconnect and recover from the condition. In this case, the server will log a warning: `WARN -- WebsocketBackend: Close connection of disconnected node ...`

Fixing this race properly would require the server `NodePlugger/NodeUnplugger` to recognize and skip a host node that was already connected / disconnected by some other websocket connection. Given an slow enough EventMachine thread with arbitrarily long delays for processing the websocket open/close events, this kind of race could play out in a variety of ways.

See #2144 for a proposed fix, involving an `Kontena-Connected-At` request header sent by the agent, which increases on each connection attempt.

**Comment by jnummelin** [comment]
fixed in #2144
