### ISSUE TITLE
kontena cli with shell plugin breaks "kontena stack upgrade"

### ISSUE THREAD

**Issue by pcornelissen** [kontena/kontena#2202]
I tried to update an installed stack and got this:
```
deployment (develop *=)$ kontena stack upgrade staging kontena.yml
 [done] Reading stack staging metadata from Kontena Master
> Enter or paste a stack YAML
 [error] NoMethodError : undefined method `[]' for false:FalseClass
         Rerun the command with environment DEBUG=true set to get the full exception
```
Deinstalling the shell plugin fixed it

**Comment by kke** [comment]
The only way I can reproduce this is by leaving the filename out.

```
$ kontena stack upgrade redis redis.yml
```
Works as expected.

```
$ kontena stack upgrade redis
> Enter or paste a stack YAML
(ctrl-d)
 [error] NoMethodError : undefined method `[]' for false:FalseClass
```

It should look for kontena.yml but the shell plugin seems to break that.

**Comment by SpComb** [comment]
I don't understand why the shell plugin is hooking `Kontena::Cli::Stacks::YAML::Reader.new('kontena.yml')` and thus changing the behavior of the `kontena stack` commands when not using the shell, but it looks like #15 should fix the `kontena-plugin-shell` to not do that.

The `NoMethodError : undefined method `[]' for false:FalseClass` seems to be a common lack-of-validation issue for the case of an empty YAML file:  #2204
