### ISSUE TITLE
How to setup Reverse Proxy (træfɪk) with Kontena grid?

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2203]
We are thinking create infra with below pattern:

Internet -> Reverse Proxy -> Grid -> Kontena LB (Public) -> Kontena LB (Private)

We are thinking to use træfɪk  as reverse proxy. I am new to both so Is  any example I get how to integrate træfɪk with kontena?

**Comment by SpComb** [comment]
Kontena includes support for the `image: kontena/lb` reverse proxy (based on `haproxy` + `confd`), where the agent writes running containers/services to etcd under `/kontena/haproxy/`. 

While you can also use the `/kontena/haproxy` etcd configuration schema for some other LB image by linking to a service with `env: KONTENA_SERVICE_ROLE=lb`, integrating some different LB (like traefik.io) into Kontena would require something to write the [`/traefik/frontends`, `/traefik/backends` configuration schema](https://docs.traefik.io/user-guide/kv-config/#key-value-storage-structure) into etcd. Kontena itself does not support these kinds of custom etcd configuration schemes.

If you do want to use a different LB, you can also deploy some custom service registration agent to the nodes as a Kontena service, to sync the Docker service containers into etcd using some custom schema. We're exploring support for this kind of custom LB deployment via [`kontena-registrator`](https://github.com/SpComb/kontena-registrator), but that's still experimental... see [`kontena-nginx`](https://github.com/SpComb/kontena-nginx) as an example of this.

**Comment by daniel-bytes** [comment]
One simple approach to get started may be to just point your external load balancer (træfɪk) at each healthy Kontena node's public IP.  Then you can poll the Kontena master REST API or CLI to monitor the status of your nodes and update the LB accordingly.
