### ISSUE TITLE
upgrading path for named volume

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#2222]
```
- kontena.yml:
  - services:
      api:
        volumes:
          vlapi-data:/app/data: defines volume name, but file does not contain volumes
            definitions
```

In docs: http://kontena.io/docs/references/kontena-yml.html#volume-configuration-reference

is not clear if using external: true will keep previous named volumes or volumes needs to be recreated with cli

**Comment by SpComb** [comment]
Indeed, the migration path for existing services with local named volumes should have been explained in the release notes.

The important part is that after a 1.1 -> 1.2 migration, any existing local named volumes should show up in `kontena volume ls`, and you can safely edit the stack file to add the new `volumes` section, referencing those external volumes created by the migration, and then continue deploying the service.

However, immediately after the 1.2 migration, the Kontena volume won't have any instances in `kontena volume show` associating it with any nodes yet. After you re-deploy the service for the first time with Kontena 1.2, then `kontena volume show` should show instances of the volume existing on all of the nodes that the service has been deployed to. Assuming that the Kontena 1.2 deploy schedules the service instances onto the same nodes that they were running on before the upgrade, then any service containers should be created with exactly the same local Docker volumes as with Kontena 1.1.

This migration path assumes that you're using something like the daemon strategy with label affinities to make sure the service instances always get deployed to the same nodes each time, which is already a pre-requisite for using stable local named volumes in Kontena 1.1.

**Comment by jalberto** [comment]
@SpComb great! that seems perfect addition to the docs :)

What about a new section in the docs with upgrade notes?

**Comment by SpComb** [comment]
> What about a new section in the docs with upgrade notes?

Hmm, we cleaned out all of the version-specific notes from the [upgrading](http://kontena.io/docs/getting-started/installing/upgrading.html) docs in https://github.com/kontena/kontena/commit/f96d81200adc1f364a356cb6ea3b19fb0d915d72

I think I'll add an ***Upgrading stacks with services using named Docker volumes*** to the release notes instead.

**Comment by jalberto** [comment]
good for me

**Comment by SpComb** [comment]
Updated the 1.2.0 release notes.
