### ISSUE TITLE
Support MongoDB 3.4 for Kontena Master

### ISSUE THREAD

**Issue by japsu** [kontena/kontena#2226]
We would like to run a Kontena Master using a replicated cluster provided via a managed solution. Most managed solutions are dropping support for MongoDB 2.x, though. For example, MongoDB Atlas only offers the choice of 3.2 or 3.4.

Please update the Kontena Master to support current versions of MongoDB and use the newest stable by default.

**Comment by jakolehm** [comment]
For >= 3.2 MongoDB support we need to upgrade Mongoid, see #1290.

**Comment by jnummelin** [comment]
Fixed in #2257, will be released with 1.3.0
