### ISSUE TITLE
kontena-agent needs a restart to notice new v1 volume plugins

### ISSUE THREAD

**Issue by giovannicandido** [kontena/kontena#2237]
I'm using the volume driver https://portworx.com/ for volume persistence.
There are two problems in using this custom driver with kontena:

1 - The driver itself is registered by a portworx container. When that container is not started, kontena-agent do not recognize pxd driver. All containers that declare volumes with this driver are not deployed, and if for some reason the driver is unregistred even for a moment, kontena stop the containers (I'm not sure if that is the case but I'm noticing instability and services are dropping, when that happen the command `kontena node show` does _not_ show the pxd volume driver). The driver container need to start **before** kontena-agent, but here comes the second problem
2 - portworx use etcd or consul to orquestrate a cluster of persistent storage and replication volumes. I don't want to maintain two etcd installs, and use kontena etcd, which works great, but portworx driver needs to start **after** kontena-agent which is Chicken and egg problem :-)

What I do now:

1 - Start the node
2 - Wait for pxd service
3 - `kontena node show` will not recognize the driver
4 - Restart kontena-agent. Wait a few moments
5 - `kontena node show` will recognize the driver
6 -  Manual redeploy stack with `kontena stack deploy`

What I whould like to do:

Use a volume with **grid** or **stack** scope and disable the check for the volume driver in order to force the deployment (not so good solution, but I think is necessary to control this behavior in problems like this). I'm using a affinity filter, it should not have problems.

Or, I would like to let the check for the driver on, but kontena needs to be way more tolerant in order to work with not static drivers like this. (maybe checking more often on volume driver information, and having a delay before removing/stopping/rescheduling container service) 

Whould be great to run portworx as a stack with kontena, it was my first try, but I'm running as a systemd service to see if improves stability

**Comment by SpComb** [comment]
> Whould be great to run portworx as a stack with kontena, it was my first try, but I'm running as a systemd service to see if improves stability

Yes, trying to run Docker drivers as Docker containers often does not really work, and tends to lead to a multitude of issues... The answer is to either use systemd services with Docker 1.12, or upgrade to Docker 1.13 and use [`docker plugin`](https://docs.docker.com/engine/extend/) containers.

>  2 - portworx use etcd or consul to orquestrate a cluster of persistent storage and replication volumes. I don't want to maintain two etcd installs, and use kontena etcd, which works great, but portworx driver needs to start after kontena-agent which is Chicken and egg problem :-)

I think the only solution to this problem in general is for the driver to be able to start up without etcd being available yet, and have operations block or fail until etcd becomes available. Then the kontena-agent would need to be able to wait for weave/etcd to be up before querying/retrying those volume driver operations.

> Or, I would like to let the check for the driver on, but kontena needs to be way more tolerant in order to work with not static drivers like this. (maybe checking more often on volume driver information, and having a delay before removing/stopping/rescheduling container service)

The agent will currently refresh volume drivers from `docker info` every 60s. Those are updated to the server, and immediately taken into account for service scheduling decisions... 

> and if for some reason the driver is unregistred even for a moment, kontena stop the containers (I'm not sure if that is the case but I'm noticing instability and services are dropping, when that happen the command kontena node show does not show the pxd volume driver).

When this happens, what does `kontena service events` show? Are you seeing `service ... has wrong number of instances (or they are not distributed correctly)` events that lead to re-scheduling/re-deployments of the service?

**Comment by giovannicandido** [comment]
Update: I managed to create a more stable installation, unfortunately I can't install as a plugin. This is what I did:

1. kontena-agent and portworx driver are systemd services
2. kontena-agent wants portworx.service (weak dependency, in case node has no persistence)
3. Installed consul as a systemd service
4. portworx.service depends on consul

Caveat: Even with portworx service working good, is necessary to have at least one volume with pxd driver, in order to `docker info` command recognize the driver.

Problem: Even with `docker info` command showing the pxd driver. Kontena agent need a restart in order to pick up the driver.

I will keep a eye and see if this setup resist to host restarts. But I think, kontena agent should pick up the driver after 60s, it isn't.

Information:

```
agent version: 1.3.4
  docker version: 17.06.0-ce
  connected: yes
  last connect: 2017-08-05T01:15:17.001+00:00
  last seen: 2017-08-05T01:15:28.373Z
  public ip: x.x.x.x.x
  private ip: x.x.x.x
  overlay ip: 10.81.0.3
  os: Ubuntu 16.04.3 LTS
  kernel: 4.4.0-89-generic
  drivers:
    storage: overlay2
    volume: local,pxd

```

**Comment by SpComb** [comment]
> Problem: Even with docker info command showing the pxd driver. Kontena agent need a restart in order to pick up the driver.

Yes, my earlier comment about the agent refreshing the node info from `docker info` every 60s was wrong, it's actually memoized at startup: https://github.com/kontena/kontena/blob/v1.3.4/agent/lib/kontena/workers/node_info_worker.rb#L139

This probably counts as a bug.

**Comment by SpComb** [comment]
Note that this only applies to classic plugins that Docker picks up from `/var/lib/docker/plugins`: v2 plugins are picked up by the agent even after startup.
