### ISSUE TITLE
Token creation for service users

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#225]
Now when the cli supports token authentication through env vars it would be nice to be able to generate security tokens to use with Jenkins etc.. Now the only option is to use a token from real-users login.

**Comment by jakolehm** [comment]
Good idea, we accept PR's :)

**Comment by miskun** [comment]
Yes, I agree. Personally I like the way how personal tokens are managed here in Github. Maybe something similar?

**Comment by jnummelin** [comment]
I guess the challenge is that the user would not be a normal user as nobody really wants to have someone else to use their tokens. The biggest issue here is the audit log in a way. What at least I'd like to see is that whenever I have Jenkins or the Slack bot doing something I'd like to see that in the audit logs. Now the audit entry shows that I did it as the bot "borrows" my auth token.

**Comment by jnummelin** [comment]
This will be implemented in the renewed oauth thingy.
