### ISSUE TITLE
Kontena image create : no host error

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2258]
Getting no such host error.

I followed below step

1. kontena registry create  --> This created registry
2.  set the daemon cat /etc/docker/daemon.json
{ "insecure-registries":["registry.cbr-dev.kontena.local"] }

3. kontena vpn create   ->vpn created

4. openvpn --config kontena.ovpn --daemon

5.  Then written kontena.yml file like below

stack: kontena/webhook
version: 0.3.0
services:
    webhook:
      extends:
        file: docker-compose.yml
        service: webhook
      image:  registry.cbr-dev.kontena.local/webhook:latest

6.  kontena stack build   // image is creating but failing to push. getting No host error

Put http://registry.cbr-dev.kontena.local/v1/repositories/webhook/: dial tcp: lookup registry.cbr-dev.kontena.local: no such host
/var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/cli/stacks/build_command.rb:98:in `push_docker_image': Failed to push image registry.cbr-dev.kontena.local/webhook:latest (RuntimeError)
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/cli/stacks/build_command.rb:66:in `block in push_docker_images'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/cli/stacks/build_command.rb:63:in `each'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/cli/stacks/build_command.rb:63:in `push_docker_images'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/cli/stacks/build_command.rb:41:in `execute'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/command.rb:200:in `run'
        from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/command.rb:200:in `run'
        from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/lib/kontena/command.rb:200:in `run'
        from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
        from /var/lib/gems/2.3.0/gems/kontena-cli-1.2.1/bin/kontena:17:in `<top (required)>'
        from /usr/local/bin/kontena:23:in `load'
        from /usr/local/bin/kontena:23:in `<main>'

**Comment by SpComb** [comment]
> `kontena stack build // image is creating but failing to push. getting No host error`
> 
> ```
> Put http://registry.cbr-dev.kontena.local/v1/repositories/webhook/: dial tcp: lookup registry.cbr-dev.kontena.local: no such host
> ```

The `kontena stack build` runs `docker build` and `docker push` on your local machine, so it sounds like the OpenVPN client configuration to resolve `kontena.local` names via the VPN is broken. If this is on an Ubuntu machine, then It sounds like you're running into some of the known issues with Kontena VPN related to resolving `kontena.local` names: https://github.com/kontena/kontena/issues/1705#issuecomment-274742213

**Comment by jnummelin** [comment]
closing due inactivity. re-open if still relevant.
