### ISSUE TITLE
How to Attach a single volume to multiple hosts in grid?

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2259]
I am using volume something like below.  Now I am copied to volume folder to 2 instances. where docker running in kontena. Is there any way single volume to multiple hosts in grid?

    volumes:
      - /root/infra-config/json:/etc/webhook/data

**Comment by jnummelin** [comment]
One way is to use "real" grid scoped volumes with a driver that actually has a replicated data storage behind to have the data replicated between nodes. For example in AWS environment you could use Rexray with s3fs support and have the files in a S3 bucket..

**Comment by santhoshkumarhirekerur** [comment]
Thank you but we are still not on public cloud. We created local cloud on VMs using vmware (vsphere)tool.

**Comment by jakolehm** [comment]
@santhoshkumarhirekerur maybe this helps: https://vmware.github.io/docker-volume-vsphere/

**Comment by santhoshkumarhirekerur** [comment]
Thank you @jakolehm.

**Comment by jnummelin** [comment]
closing as assumably solved :)
