### ISSUE TITLE
Show vpn & registry services in service list

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#226]

**Comment by hans-d** [comment]
at least make it visible somewhere - services could be argued to show only user defined services.
And, why not show etcd etc.

getting to see if vpn is available, now done via:
- `docker ps` - bit low level, and hey, there are even more containers that I have as services, and needs to be done per node
- `kontena vpn create` - error if its already existing
- `kontena vpn config` - way more info as needed
- `kontena vpn delete` - oops
