### ISSUE TITLE
Whoami command (for bash completions) is very slow

### ISSUE THREAD

**Issue by xtagon** [kontena/kontena#2270]
Hi,

After enabling Bash completions for Kontena CLI, I noticed it takes a long time to load my bash profile and initialize new terminals. I traced this to the `kontena whoami` command which takes 1.2 seconds to run. Is there any way we can optimize this?

I figured out I can get the path using this command (although I'm not sure it is correct or robust):

```
gem contents kontena-cli | grep /lib/kontena/scripts/init | head -n 1
```

This still takes 0.5 seconds to run, but that's better.

It seems silly that such a simple command should be so expensive. Any ideas?

**Comment by kke** [comment]
It loads quite a few files. 

File | Load time
----|-----------
tty-prompt | 0.0507
safe_yaml | 0.0317
excon | 0.0303
safe_yaml/load | 0.027
kontena/callback | 0.0259
retriable | 0.0225
lib/kontena/callbacks/master/deploy/50_authenticate_after_deploy.rb | 0.0224
openssl/ssl | 0.0109
kontena/plugin/shell/callbacks/stack_file | 0.0106
clamp | 0.0094
tempfile | 0.0094
tmpdir | 0.0084
clamp/command | 0.0071
kontena/stacks_cache | 0.0069
fileutils | 0.0067
psych/visitors | 0.0065
necromancer | 0.0061
openssl.so | 0.0056
kontena/plugin/shell/session | 0.0056
ruby_dig | 0.0053
cgi | 0.0052
psych/nodes | 0.0045
wisper | 0.0042
kontena/plugin/shell/command | 0.004
psych/visitors/yaml_tree | 0.0031
psych/nodes/node | 0.0028
cgi/cookie | 0.0026
rubygems/user_interaction | 0.0025
pastel/delegator | 0.0023
socket.so | 0.0023
clamp/option/declaration | 0.0023
cgi/core | 0.0023
psych/deprecated | 0.0021
json/ext | 0.0019
excon/connection | 0.0019
psych/visitors/to_ruby | 0.0017
pastel/color | 0.0016
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/kontena.rb | 0.0016
tty-color | 0.0015
openssl/config | 0.0015
clamp/option/definition | 0.0015
uri/rfc3986_parser | 0.0014
tty/color | 0.0014
excon/socket | 0.0012
uri/rfc2396_parser | 0.0012
zlib | 0.0011
excon/middlewares/expects | 0.0011
openssl/x509 | 0.0011
excon/errors | 0.001
excon/response | 0.0009
openssl/buffering | 0.0009
etc | 0.0009
json/ext/generator | 0.0009
tty-cursor | 0.0009
psych.so | 0.0009
wisper/global_listeners | 0.0009
kontena/plugin_manager | 0.0009
clamp/help | 0.0008
excon/ssl_socket | 0.0008
uri/mailto | 0.0008
wisper/configuration | 0.0007
excon/utils | 0.0007
psych/visitors/json_tree | 0.0007
openssl/digest | 0.0007
openssl/cipher | 0.0007
clamp/subcommand/declaration | 0.0007
clamp/parameter/declaration | 0.0007
psych/json/tree_builder | 0.0007
readline | 0.0007
date_core | 0.0007
safe_yaml/deep | 0.0006
clamp/subcommand/parsing | 0.0006
cgi/escape | 0.0006
rubygems/util | 0.0006
safe_yaml/psych_handler | 0.0006
lib/kontena/callbacks/master/deploy/70_invite_self_after_deploy.rb | 0.0006
uri/ftp | 0.0006
safe_yaml/transform | 0.0006
tty/cursor | 0.0006
excon/extensions/uri | 0.0006
clamp/option/parsing | 0.0005
excon/constants | 0.0005
safe_yaml/resolver | 0.0005
safe_yaml/parse/date | 0.0005
excon/middlewares/base | 0.0005
digest.so | 0.0005
kontena/main_command | 0.0005
safe_yaml/libyaml_checker | 0.0005
json/generic_object | 0.0005
psych/handlers/document_stream | 0.0005
pastel/color_parser | 0.0005
pastel/color_resolver | 0.0005
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/batch.rb | 0.0005
lib/kontena/callbacks/master/deploy/05_before_deploy_configuration_wizard.rb | 0.0005
excon/middlewares/mock | 0.0004
wisper/registration/object | 0.0004
io/nonblock | 0.0004
excon/headers | 0.0004
excon/middlewares/decompress | 0.0004
openssl/pkey | 0.0004
excon/middlewares/redirect_follower | 0.0004
excon/pretty_printer | 0.0004
psych/coder | 0.0004
subcommand_loader | 0.0004
clamp/parameter/definition | 0.0004
clamp/attribute/instance | 0.0004
tty/color/mode | 0.0004
json/ext/parser | 0.0004
tty/color/support | 0.0004
strscan | 0.0004
excon/middlewares/instrumentor | 0.0004
psych/visitors/emitter | 0.0004
io/wait | 0.0004
wisper/publisher | 0.0004
whoami_command | 0.0003
wisper/temporary_listeners | 0.0003
psych/nodes/scalar | 0.0003
psych/core_ext | 0.0003
safe_yaml/parse/hexadecimal | 0.0003
safe_yaml/parse/sexagesimal | 0.0003
/Users/kimmo/.kontena/gems/2.4.0/gems/kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/debug.rb | 0.0003
psych/parser | 0.0003
psych/visitors/depth_first | 0.0003
kontena/errors | 0.0003
excon/unix_socket | 0.0003
safe_yaml/transform/transformation_map | 0.0003
safe_yaml/transform/to_float | 0.0003
safe_yaml/transform/to_integer | 0.0003
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/context_top.rb | 0.0003
excon/middlewares/idempotent | 0.0003
kontena/plugin/shell/shell_command | 0.0003
excon/middlewares/escape_path | 0.0003
excon/standard_instrumentor | 0.0003
excon/middlewares/capture_cookies | 0.0003
openssl/bn | 0.0003
safe_yaml/psych_resolver | 0.0003
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/help.rb | 0.0003
wisper/broadcasters/logger_broadcaster | 0.0003
psych/nodes/document | 0.0003
kontena/plugin/shell/commands/batch_do | 0.0003
pastel/alias_importer | 0.0003
clamp/parameter/parsing | 0.0003
wisper/registration/registration | 0.0003
clamp/subcommand/definition | 0.0003
forwardable/impl | 0.0003
clamp/subcommand/execution | 0.0003
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/exit.rb | 0.0002
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/context_up.rb | 0.0002
excon/middlewares/response_parser | 0.0002
lib/kontena/callbacks/master/deploy/90_proptip_after_deploy.rb | 0.0002
lib/kontena/callbacks/master/deploy/60_configure_auth_provider_after_deploy.rb | 0.0002
lib/kontena/callbacks/master/deploy/56_set_server_provider_after_deploy.rb | 0.0002
lib/kontena/callbacks/master/deploy/55_create_initial_grid_after_deploy.rb | 0.0002
lib/kontena/callbacks/master/deploy/40_install_ssl_certificate_after_deploy.rb | 0.0002
lib/kontena/callbacks/master/deploy/04_default_master_version.rb | 0.0002
lib/kontena/callbacks/master/deploy/01_show_logo_before_deploy.rb | 0.0002
lib/kontena/callbacks/auth/01_list_and_select_grid_after_master_auth.rb | 0.0002
lib/kontena/callbacks/master/01_clear_current_master_after_terminate.rb | 0.0002
clamp/truthy | 0.0002
clamp/version | 0.0002
uri/ldaps | 0.0002
uri/https | 0.0002
io/console | 0.0002
wisper/broadcasters/send_broadcaster | 0.0002
wisper/registration/block | 0.0002
wisper/version | 0.0002
tty/version | 0.0002
pastel/version | 0.0002
pastel/detached | 0.0002
equatable/version | 0.0002
safe_yaml/safe_to_ruby_visitor | 0.0002
safe_yaml/transform/to_symbol | 0.0002
safe_yaml/transform/to_nil | 0.0002
safe_yaml/transform/to_date | 0.0002
safe_yaml/transform/to_boolean | 0.0002
psych/json/stream | 0.0002
psych/stream | 0.0002
psych/visitors/visitor | 0.0002
psych/streaming | 0.0002
psych/nodes/alias | 0.0002
psych/nodes/mapping | 0.0002
psych/nodes/sequence | 0.0002
psych/nodes/stream | 0.0002
stringio | 0.0002
psych/versions | 0.0002
bytes_helper | 0.0002
openssl | 0.0001
etc.so | 0.0001
socket | 0.0001
pathname | 0.0001
kontena/plugin/shell/version | 0.0001
grid_options | 0.0001
psych | 0.0001
psych/omap | 0.0
json/version | 0.0
json/common | 0.0
json | 0.0
config | 0.0
spinner | 0.0
common | 0.0
yaml | 0.0
clamp/messages | 0.0
timeout | 0.0
clamp/errors | 0.0
psych/json/yaml_events | 0.0
kontena/plugin/shell | 0.0
clamp/attribute/declaration | 0.0
date | 0.0
clamp/attribute/definition | 0.0
kontena_cli | 0.0
kontena/util | 0.0
monitor | 0.0
securerandom | 0.0
psych/json/ruby_events | 0.0
kontena/command | 0.0
psych/tree_builder | 0.0
psych/handler | 0.0
cgi/util | 0.0
psych/exception | 0.0
logger | 0.0
kontena/client | 0.0
set | 0.0
shellwords | 0.0
delegate | 0.0
kontena/plugin/shell/context | 0.0
kontena-plugin-shell-0.1.0/lib/kontena/plugin/shell/commands/batch_do.rb | 0.0
equatable | 0.0
pastel/ansi | 0.0
pastel/decorator_chain | 0.0
tty/color/version | 0.0
pastel | 0.0
time | 0.0
forwardable | 0.0
thread | 0.0
version | 0.0
uri/http | 0.0
base64 | 0.0
kontena/plugin/shell/completer | 0.0
psych/class_loader | 0.0
uri | 0.0
ostruct | 0.0
psych/set | 0.0
singleton | 0.0
rbconfig | 0.0
psych/scalar_scanner | 0.0
uri/common | 0.0
uri/generic | 0.0
uri/ldap | 0.0
TOTAL | 0.4278

The `--bash-completion-path` could be moved to `bin/kontena` like the `kontena complete` in 1.2.0, that way it doesn't need to load much.

**Comment by kke** [comment]
Of course the better solution would be to actually install the bash completions properly to `bash_completions.d` like the brew formula does.

**Comment by xtagon** [comment]
The problem with using `ln -s` manually is that it's one more manual step to do any time I update the system Ruby since the `lib/kontena/` path moves. That's why I'm using the `gem contents` workaround, but it's still pretty slow.

**Comment by jakolehm** [comment]
@xtagon is it still slow with latest cli version?

**Comment by xtagon** [comment]
@jakolehm I don't have a Kontena grid to play with right now but I'll try again in about a week and report back. Thanks!

**Comment by jakolehm** [comment]
@xtagon you can also try Kontena Shell: https://github.com/kontena/kontena-plugin-shell#kontena-shell

**Comment by kke** [comment]
With the latest release it can be made even faster by using `NO_PLUGINS=true kontena whoami --bash-completion-path`.

**Comment by xtagon** [comment]
Thanks everyone! It is faster now especially with @kke's version. Got it down to ~200ms, which still adds some noticable delay to shell startup but muuuuuch better than over 1 second 👍
