### ISSUE TITLE
AWS node provision should open vpn port by default

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#229]
AWS node provisioner does not currently open port 1194/udp.

**Comment by maniankara** [comment]
Hi, It does open 1194/udp.
I see from [code](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/machine/aws/node_provisioner.rb#L132) and also from aws security group `kontena_grid_testing (Kontena Node)` in the `Inbound` tab
```
Custom UDP Rule    UDP    1194    0.0.0.0/0
```
Or are you looking for other than `inbound`? Are you looking for setting up some `source ip` or something like that? cli?

**Comment by jakolehm** [comment]
This has been already fixed. Thanks for noticing :)
