### ISSUE TITLE
Cli list and show commands should have output formatting parameters

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2291]
## lists

When scripting you will do this all the time:

```console
$ kontena service ls|tail -n +2|cut -d' ' -f1
```

There should be some way to output just the field you want and skip the header. Perhaps `--name`, or `--fields name` or `--format %name` and/or to dump the list as JSON.

Before:
```
$ kontena node ssh $(kontena node ls|tail -n +2|head -1|cut -d' ' -f2)
```

After:
```
$ kontena node ssh $(kontena node ls --name|head -1)
```

Also worth noting, cut delimiter default is tab. Lists could be tab separated by default to avoid `-d' '`

## shows

Most if not every `kontena XXX show` commands seem to output YAML or something that is very YAML like. (there are like 5 show commands)

`kontena container inspect [CONTAINER_ID]` however outputs json. And as we have the great [jq](https://stedolan.github.io/jq/) it's quite easy to parse the results:

```
$ kontena container inspect young-wildflower-83/kontena-etcd|jq -r '.NetworkSettings.Networks.host.EndpointID'
1f12fb8104f562fad3b01460b656a7823208aed4ff2a143619d388d84a7db091
```

Sadly there's no proper or commonly used `yq` for yaml, so..

1) Show commands should be able to output json with `-J|--json`.
2) that's it.

Before:
**how about no**

After:
```
$ kontena stack show -J redis | jq '.[].services[] | { image, state }''
{
  "image": "redis:latest",
  "state": "running"
}
{
  "image": "redis:latest",
  "state": "running"
}
```

**Comment by jnummelin** [comment]
`kontena container inspect [CONTAINER_ID]` just dump the results of `docker inspect` from the host node where the given container is running.

**Comment by kke** [comment]
yes and that is nicer for parsing than our `show` commands.

The API responses are json so maybe `-J` or `--raw` could just dump it out in most cases.

**Comment by SpComb** [comment]
The `kontena service list` command has a `-q` flag to list just the stack/service names, it would be a nice first step if the other list commands also had that. Some kind of customizable `--fields` formatting would then be the next step.

> `$ kontena node ssh $(kontena node ls|tail -n +2|head -1|cut -d' ' -f2)`

This specific example is `kontena node ssh --any` :)

> Lists could be tab separated

Likely to end in tears trying to align output, I fear?

**Comment by kke** [comment]
That `-q|--quiet` feels wrong, many commands have `-s|--silent`.

**Comment by SpComb** [comment]
> That -q|--quiet feels wrong, many commands have -s|--silent.

The `-q` is probably inspired from the Docker CLI (`docker ps -q`, `docker images -q`, `docker volume list -q`).

**Comment by kke** [comment]
Then maybe just `-q` for all the lists that dumps the identifying column (usually first)

**Comment by matti** [comment]
-q is definitely right choise now, formatting is the next step
