### ISSUE TITLE
Multiple healthy services removed during stack deploy

### ISSUE THREAD

**Issue by Edke** [kontena/kontena#2297]
Hello.

As discussed in detail with @SpComb, I'm experiencing issues during `kontena stack deploy` when agent after successful deployment of services starts to remove them even when their ID is same and breaks A/B deployments, even removes multiple services linked to LB.

Complete log and detailed screen-cast is already sent to @SpComb.

If more info needed, ping be back.

$ kontena version
cli: 1.2.0
master: 1.2.0

Agent is also 1.2.0

**Comment by SpComb** [comment]
Brief analysis of the screencast/logs shows that the agent `Kontena::Workers::ServicePodWorker` is immediately deciding to re-create the container after it has managed to apply the `deploy_rev` update. This indicates that the agent considers the [`ServicePodWorker#service_container_outdated?`](https://github.com/kontena/kontena/blob/fd4771a393e63ea171ea8690a324206483597095/agent/lib/kontena/workers/service_pod_worker.rb#L98) check is triggering on the newly created container.

The logs indicate that the container is running and not exiting, nor is the image ID changing after the initial pull on deploy. Unfortunately, the agent `ServicePodWorker` logging isn't good enough to tell us exactly why the agent considers the service container to be out of date, but there's two possible causes we've figured out so far:

* #2298 the master and host node clocks are unsynchronized such that the master node is ahead of the host node clock
* #2287 the `Docker::Image.get` is failing somehow

**Comment by Edke** [comment]
@SpComb Master and Node were indeed out of time sync, investigating behavior of deployment after time synced, will report back if was the cause of the problem.

**Comment by Edke** [comment]
@SpComb tested multiple times after syncing time and it did not occur since then, thanks Terom, closing for now.
