### ISSUE TITLE
Missing CLI omnibus installer for Windows

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2307]
The [CLI Omnibus](https://github.com/kontena/kontena/tree/master/cli/omnibus) package is currently only built for OS X.

There should also be a Windows build/installer.

**Comment by kke** [comment]
(This requires a windows box and a windows license on the build system)

**Comment by SpComb** [comment]
If we're not going to setup windows omnibus builds, then we should close this issue with "use WSL with the deb package, or gem install manually" as a workaround?

**Comment by daniel-bytes** [comment]
Just an FYI, WSL is only available on Windows 10 (not 7 or 8, or any server versions) so it might be kind of strict requirement.

**Comment by SpComb** [comment]
The "manual `gem install`" is also acceptable if the ruby windows installers also provide the necessarily compilers + development headers to build the `websocket-driver` extensions when installing the CLI.

I don't know if anyone has tested the 1.4 CLI `gem install` on Windows yet? Does it work with the standard ruby install?

**Comment by jakolehm** [comment]
> Ruby 2.4.0 and newer: The MSYS2 DevKit is downloaded as the last step of the installation. It can be installed later per ridk install command

From https://rubyinstaller.org/downloads/

**Comment by SpComb** [comment]
Closing as WONTFIX for the 1.4 release. We can re-open this if it turns out that we really do need the omnibus windows installer.
