### ISSUE TITLE
Deprecate apps

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2319]
The `kontena app` and it's subcommands should be removed in favor of stacks.

## option a
add a deprecation warning and wait for a couple of releases to remove

## option b
if it makes any sense, add some kind of `kontena app migrate` and replace the commands with a message like `apps have been removed, please run kontena app migrate`

## option c
just replace them with some `apps have been deprecated, please use stacks` message cold turkey

**Comment by jnummelin** [comment]
I'd go for option a and maybe +b :)

**Comment by kke** [comment]
At least the warning should be there in 1.3
