### ISSUE TITLE
Server string validations do not reject newlines

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2324]
The server validations that create new named objects (`GridServices::Create`, `Stacks::Create`, `Volumes::Create` etc)  typically use a regexp to validate the name:

```ruby
      string :name, matches: /^(?!-)(\w|-)+$/ # do not allow "-" as a first character
```

However, the [use of `^` as an anchor in a Ruby Regexp](https://ruby-doc.org/core-2.3.1/Regexp.html#class-Regexp-label-Anchors) does not match the beginning of the string, it matches the beginning of a line. This means that the name can contain a newline, and any arbitrary garbage, provided that least one "line" is a valid name. This allows names like:

* `kontena service create $'redis\ntest'`
* `kontena service create $'redis\n{}test--<>' redis`
* `kontena service create $'redis\n☃' redis`

#### `DEBUG=api kontena service create $'redis\ntest' redis`
```
[API Client Request]: POST http://localhost:9292/v1/grids/development/services | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: 
{"name":"redis\ntest","image":"redis:latest","stateful":false,"secrets":[],"privileged":false,"log_opts":{}}
[API Client Response]: Headers: {Content-Type: application/json}  | Status: 201 | Body: 
{"id":"development/null/redis\ntest","created_at":"2017-05-16T09:21:59.031Z","updated_at":"2017-05-16T09:21:59.031Z","image":"redis:latest","affinity":[],"name":"redis\ntest","stateful":false,"user":null,"instances":1,"cmd":null,"entrypoint":null,"net":"bridge","dns":"redis\ntest.development.kontena.local","ports":[],"env":[],"secrets":[],"memory":null,"memory_swap":null,"cpu_shares":null,"volumes":[],"volumes_from":[],"cap_add":[],"cap_drop":[],"state":"initialized","grid":{"id":"development"},"stack":{"id":"development/null","name":"null"},"links":[],"log_driver":null,"log_opts":{},"strategy":"ha","deploy_opts":{"_id":{"$oid":"591ac4b7de357847e2000002"},"interval":null,"min_health":0.8,"wait_for_port":null},"pid":null,"instance_counts":{"total":0,"running":0},"hooks":[],"revision":1,"stack_revision":null}
 [done] Creating redis
test service      
```

#### `kontena service ls`
```
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ redis
test                                                 0 / 1      no       initialized                                                   
```

**Comment by SpComb** [comment]
Good news is that the Kontena Cloud -integration seems to be unicode-safe

![2017-05-16-122922_822x273_scrot](https://cloud.githubusercontent.com/assets/3950373/26101190/ed11cee0-3a38-11e7-92ba-edf18837c00a.png)

**Comment by kke** [comment]
Can you inject `<script>` or something and get funny stuff on cloud?

**Comment by SpComb** [comment]
It is impossible to remove services with invalid names created like this using the CLI, because the service names are invalid URL paths and need quoting. The services cannot be removed using the API even when using quoting (`kontena service rm 'redis%0Atest'`), because roda [does not unescape URL paths](https://groups.google.com/forum/#!topic/ruby-roda/6mcuq6Y8TMo) by default. Upgrading to roda 2.16 and using `plugin :unescape_path` does let you remove the services.

Deploying such a service will fail, because the Docker API does reject the invalid names with newlines:

```
W, [2017-05-16T13:27:11.441567 #25283]  WARN -- GridServiceInstanceDeployer: Failed to deploy service instance development/null/redis
{}test--<>-1 to node core-02: GridServiceInstanceDeployer::ServiceError: Docker::Error::ServerError: Invalid container name (redis
{}test--<>-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

OTOH seems like our Agent RPC / Docker API is not unicode-safe :broken_heart: 
```
W, [2017-05-16T13:26:41.314624 #25287]  WARN -- GridServiceInstanceDeployer: Failed to deploy service instance development/null/redis
☃-1 to node core-02: GridServiceInstanceDeployer::ServiceError: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
```

**Comment by SpComb** [comment]
This also affects a large number of other validations that use `matches: /^(foo|bar)$/`, they will accept parameters of the form "foo\ninvalid".

**Comment by SpComb** [comment]
Random background article talking about this: http://batsov.com/articles/2013/12/04/regexp-anchors-in-ruby/

Apparently ruby is kinda special in that it uses multi-line matching for `^` and `$`:

```
irb(main):006:0> /^(foo|bar)$/.match("something invalid\nfoo")
=> #<MatchData "foo" 1:"foo">
```

This is not the case in e.g. Python:

```
>>> re.match(r'^(foo|bar)$', "something invalid\nfoo")
>>> 
```
