### ISSUE TITLE
Improved node remove logic

### ISSUE THREAD

**Issue by miskun** [kontena/kontena#235]
At the moment it is possible to remove node from grid. This functionality works ok in case user has manually terminated the machine and the intention is to remove node from the list of grid nodes. However, we don't have ability to "kick" unwanted nodes from grid that are running ok and have valid grid token. This needs to be fixed. We need to be able to kick any unwanted node from a grid.

**Comment by kke** [comment]
Still relevant?

**Comment by jakolehm** [comment]
Fixed (with node tokens).
