### ISSUE TITLE
How to deploy image from repo -> Kontena using drone?

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2354]
I am trying to setup drone. I am able to build and push image. Now I have to deploy image from repo -> Kontena.  Drone running in Kontena grid. 

I followed the Video. https://www.youtube.com/watch?v=ViYOZZgyHSw 

what are the secrets need to be set here?

On drone I am getting below error.  I know login to master from CLI and its pop ups browser and confirm login success. But not getting how to login to master from drone?

SSL_IGNORE_ERRORS=true kontena stack upgrade webhook/webhook
 [error] ArgumentError : You are not logged into a Kontena Master. Use: kontena master login
         Rerun the command with environment DEBUG=true set to get the full exception 

.drone.yml
--------------------------------------------

pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: <domain>/<service>
    registry: <repo>
    insecure: true
    dockerfile: Dockerfile
    compose:
      from-file: docker-compose.yml

  kontena:
    image: kontena/cli
    commands:
      - SSL_IGNORE_ERRORS=true kontena stack upgrade <stack/service>

**Comment by jnummelin** [comment]
You need to provide the authentication token to drone via secrets. So use the following drone CLI commands to set the needed configuration:
```
drone secret add --image=kontena/cli <git repo> KONTENA_GRID <kontena grid name>
drone secret add --image=kontena/cli <git repo> KONTENA_URL <kontena master url>
drone secret add --image=kontena/cli <git repo> KONTENA_TOKEN <kontena token>
```

You can create a new (newer expiring) auth token by using:
`kontena master token create -e 0`
