### ISSUE TITLE
https://cloud.kontena.io is not working (No Master,Grid, Node) information showing

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2368]
I was able to see my complete https://cloud.kontena.io but today when I login only master name is showing and no  grid or nodes or services.  Loading sing just showing for hours.  I can see complete cluster working fine from CLI. and I can access my services running. 

So executed commands in below order but still nothing showing in https://cloud.kontena.io

1.  kontena cloud master ls
ID                         NAME                         OWNER        URL
ID                      MASTER_NAME              oner_name  https://IP
2. Kontena cloud  master rm ID
3. Kontena cloud logout

4. Kontena cloud login

5.  kontena master init-cloud

6. kontena cloud master ls
ID                         NAME                         OWNER        URL
NEW_ID                      MASTER_NAME              oner_name  https://IP

7.  kontena cloud master update NEW_ID
 [error] Kontena::Errors::StandardError : Forbidden

**Comment by jnummelin** [comment]
Should be fixed now.
