### ISSUE TITLE
Kontena master ssh fails if no server.provider set

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#2373]
If masters `server.provider` is not set, `kontena master ssh` fails with:
```
$ kontena master ssh
 [error] Kontena::Errors::StandardError : Not Found
```
Not very user friendly error. :)

Running things with debug on reveals that it fails to get `server.provider` config value:
```
[API Client Error]: 
D, [2017-05-27T00:04:33.522879 #74679] DEBUG -- CLIENT: Request GET /v1/config/server.provider: 404 Not Found: "Not found"
D, [2017-05-27T00:04:33.523092 #74679] DEBUG -- CLIENT: JSON parse exception: JSON::ParserError : 757: unexpected token at '"Not found"'
Command raised Kontena::Errors::StandardError with message: Not Found
```

I think it would be good for the CLI to still try with some sane defaults if the `server.provider` is not set.

**Comment by kke** [comment]
It's only needed to detect if it's vagrant, when it runs `kontena vagrant X ssh` instead.
