### ISSUE TITLE
How to run https://cloud.kontena.io/  UI in Local environment?

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2401]
Now kontena init-cloud registering to  https://cloud.kontena.io/ . 
Is there is a way, we can run this app in local environment and simulate authentication in Local?

**Comment by kke** [comment]
For authentication, any oauth2 compatible authentication provider should work: (Documentation)[http://www.kontena.io/docs/using-kontena/authentication.html#using-an-external-authentication-provider]

**Comment by jnummelin** [comment]
As @kke said, auth can be handled with any oauth2 provider. 

For the dashboard itself we do not currently offer it for local deployments.
