### ISSUE TITLE
Add a switch to stack upgrade to not prompt values that have defaults

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2406]
Perhaps `--use-defaults`.

When doing `kontena stack upgrade`, the answers/values to any variables from the previous install/upgrade are downloaded from the master and used as the default values.

Currently you have to hit enter a zillion times to use the answers as is.

A switch like `--use-defaults` could be added that would not prompt for anything that has a default value (defined in the yaml or coming from the master).

**Comment by matti** [comment]
Another workaround: write all values to vault and resolve them from there.

**Comment by kke** [comment]
This was implemented as `--reuse-values` in 1.5
