### ISSUE TITLE
Exec commands are not passing TERM

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2426]
```console
$ bin/kontena service exec --interactive --shell redis/redis top
TERM environment variable not set.
```

```console
$ bin/kontena service exec --interactive --shell redis/redis sh
# export TERM=xterm
# top
Win!
```

**Comment by jakolehm** [comment]
Works with #2412

**Comment by kke** [comment]
```
$ git status -b
On branch fix/split-interactive-and-tty-options
$ bin/kontena service exec -it redis/redis top
TERM environment variable not set.
```

**Comment by jakolehm** [comment]
Oh, right... it depends on used image. If image does not have proper environment then we cannot do much about it (and actually shouldn't do).

Try with `redis:3-alpine` image and see if it still complains?

**Comment by kke** [comment]
The alpine image defaults to xterm no matter what the local terminal is.

Ssh sends the local TERM to target host:

```
TERM=dumb ssh host.example.com
$ echo $TERM
dumb
```

But yep, I guess it's not possible since the ENV is passed in `run`, not `exec`.

**Comment by jnummelin** [comment]
Actually there's possiblity to pass new envs inDocker  exec API:
https://docs.docker.com/engine/api/v1.29/#operation/ContainerExec

Not sure if the Docker api gem supports that.

So this should be possible AFAICT, though clearly an enhancement :)
