### ISSUE TITLE
Increase Rpc default timeout

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#2460]
The default timeout used in server-agent RPC is 2secs. In cases where there are e.g. multiple deployments ongoing both agent and server has their hands full of work. This makes the RPC channel hit timeouts and thus may cause failed instance deploys.
```
Failed to deploy instance xyz-1 to node foo-node: RpcClient::TimeoutError: Connection timeout (2.0s)
```

**Comment by SpComb** [comment]
To be percise, the default timeout for the server `RpcClient` and `HostNode#rpc_client` is 300s (5m).

Some callers like the `GridServiceInstanceDeployer#notify_node` then use a default timeout of 2.0s, which is a bit optimistic.

**Comment by SpComb** [comment]
Some of the callers that specify arbitrary timeouts for the `RpcClient` (like the `Agent::NodePlugger`) only ever send RPC notifys, so those timeout values are meaningless.
