### ISSUE TITLE
e2e service exec spec using kommando shell is broken on alpine without bash

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2468]
The `service exec runs a command with piped stdin` spec is broken when run via the Vagrant + compose method, where the specs run within a Docker container based on the alpine image, which does not include `bash`:

```
  1) service exec runs a command with piped stdin
     Failure/Error: expect(k.run).to be_truthy
     
     Kommando::Error:
       Command 'bash' not found
     # ./spec/features/service/exec_spec.rb:48:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ENOENT:
     #   No such file or directory - fork failed
     #   ./spec/features/service/exec_spec.rb:48:in `block (2 levels) in <top (required)>'
```

[The spec](https://github.com/kontena/kontena/blob/v1.3.0/test/spec/features/service/exec_spec.rb#L47) uses the kommando `$ ...` syntax:

```ruby
    k = kommando("$ echo beer | kontena service exec -i test-1 rev")
```

And [kommand uses `bash`](https://github.com/matti/kommando/blob/v0.1.0/lib/kommando.rb#L144):

```ruby
 ["bash", "-c", line]
```

This doesn't work in the `test/Dockerfile.test` image, because the alpine base image does not include bash:

```
$ docker-compose run --rm test bash -v
ERROR: Cannot start service test: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"
```

Kommando should probably use `/bin/sh` instead of `bash`?

**Comment by kke** [comment]
Kommando btw seems to have problem with spaces, it has something like `split(" ")` for the params.

**Comment by matti** [comment]
@SpComb  Kommando's "$ ls" will use bash always. I've been planning to make a change to fall back to "sh" if "bash" was not found, but haven't done it yet for possible compatibility reasons...

@kke yes. Should use something like shellwords right?

**Comment by matti** [comment]
@SpComb I now made an unreleased fix https://github.com/matti/kommando/commit/1078eaeb30e81c9154ce9e7c263fb04c662b5de4#diff-5f8e9bdb2908432f8b546828992a8999R338 - but it looks like the method of checking the existence won't pass all the Kommando tests when run hard enough in parallel...  Any better ideas? (that one was stackoverflow's most upvoted without mkmf dependency)...

**Comment by kke** [comment]
@matti yes, `args.shellsplit` & `args.shelljoin` or such.

**Comment by matti** [comment]
@SpComb decided to use `command -v` -- Please update kommando 0.1.1

**Comment by matti** [comment]
(Kommando is also tested with alpine images without bash)

**Comment by SpComb** [comment]
> @SpComb decided to use command -v -- Please update kommando 0.1.1

So close, but not quite D:

```

  1) service exec runs a command with piped stdin
     Failure/Error: expect(k.run).to be_truthy
     
     Errno::ENOENT:
       No such file or directory - command
     # ./spec/features/service/exec_spec.rb:48:in `block (2 levels) in <top (required)>'
```

```
$ docker-compose run --rm test command -v bash                           
ERROR: Cannot start service test: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"command\\\": executable file not found in $PATH\"\n"
```

**Comment by SpComb** [comment]
> No such file or directory - command

I think `command` is just a bash shell builtin, not an actual binary... not sure how the [ruby backticks with `command`](https://github.com/matti/kommando/blob/v0.1.1/lib/kommando.rb#L145) even work... it seems to fail with `Errno::ENOENT` even if `/bin/sh` is a symlink to `bash`, not `busybox`?

**Comment by matti** [comment]
Yes. It fails with the advertised alpine tests (and my test wrapper failed to check if the alpine tests actually pass..). Shouldn't "fix" things in a hurry :D

Made the detection super simple so it "just works" if sh is in /bin/sh and bash in /bin/bash...

So there's a new 0.1.2 for you.

**Comment by SpComb** [comment]
Yes, kommando 0.1.2 works. PR to upgrade over in #2475
