### ISSUE TITLE
custom VPS as node and/or server

### ISSUE THREAD

**Issue by tcurdt** [kontena/kontena#247]
> Kontena CLI may be used to provision new Kontena Nodes based on CoreOS, fully configured and ready for action! At the moment, you can provision Nodes to following platforms:

- Amazon AWS
- Microsoft Azure
- DigitalOcean
- Vagrant (local environment)

Can any docker host be turned into a Kontena node? I am currently running a server that hosts a few Docker containers and a private registry. I would love to use this abstraction.

Any instructions on how to run Kontena my own servers (not AWS and friends)? including the containers?

**Comment by nevalla** [comment]
Any Docker host can be turned into a Kontena node. If you are setting up a new docker host you can use [example CoreOS cloud-config](http://www.kontena.io/docs/getting-started/installing/nodes#manual-install)  or install [Kontena Ubuntu packages](http://www.kontena.io/docs/getting-started/installing/nodes#manual-install) to setup Kontena Node. 

If you have existing Docker host (other than Ubuntu) and you want to turn it to Kontena node, you can do it manually by following steps:

1. Modify Docker daemon options `DOCKER_OPTS=--insecure-registry="10.81.0.0/19" --bip="10.255.0.1/16`.  Choose some bip value that is not conflicting with your infrastructure.
2. Set docker bip value (10.255.0.1) as the default nameserver in `/etc/resolv.conf`
3. Install kontena-agent container:

```
$ docker run --name kontena-agent \
            -e KONTENA_URI=${KONTENA_URI} \
            -e KONTENA_TOKEN=${KONTENA_TOKEN} \
            -e KONTENA_PEER_INTERFACE=eth1 \
            -v=/var/run/docker.sock:/var/run/docker.sock \
            --net=host \
            --restart=always \
            -d \
            kontena/agent:latest
```

Where 
* `${KONTENA_URI}` is WebSocket uri to Master node
* `${KONTENA_TOKEN}` is token from Kontena Grid, which agent will join

After that stop and start Docker and you should see the node connected to Kontena Master: `$ kontena node list`

Unfortunately, you cannot turn existing containers to Kontena services. You have to create and deploy them with Kontena instead.

**Comment by tcurdt** [comment]
Perfect - that's what I was looking for! It is indeed a Ubuntu host - so the package should make it easy.

Re-deploying the containers is no problem.

**Comment by tcurdt** [comment]
@nevalla a few questions before I proceed

- why the insecure registry? (my current registry uses client cert auth)
- not fully understand where the bip value is coming from and how that is used (I assume that's the shared network of the containers?)
- I am not sure I fully understand the following notes from the instructions yet:

> The address of the Kontena server. Note! You must use WebSocket protocol: ws or wss for secured connections

> Grid token from the Kontena server

(from http://www.kontena.io/docs/getting-started/installing/nodes#manual-install)

**Comment by nevalla** [comment]
Kontena includes built-in image registry that can be reach only from the Kontena grid and via VPN connection. At this moment it is insecure and you need to set Docker daemon to handle it as insecure. Since you have secured registry you don't need to set that option.

bip is ip address of `docker0` network interface. You can see it by running `ifconfig` on Docker host machine. You can read more about Docker networking [here](https://docs.docker.com/articles/networking/)

Kontena Agent establishes a connection automatically to Kontena Master on starting and it uses WebSocket protocol for that. So if you have Kontena Master server running on ip address xx.yy.zz.nn, you have to set wss://xx.yy.zz.nn (add port if Kontena Master container is listening non-standard port 443). If Master container does not have SSL certificate, use ws:// protocol.

**Comment by mtrofimm** [comment]
@nevalla There is some issue with weave in mixed environment.
My case is as follows. I have 3 nodes in digitalocean.
When I add a node from OVH, the weave container is created to use digitalocean private IPs 
docker inspect weave (at OVH node) 
```
[....]
        "Path": "/home/weave/weaver",
        "Args": [
            "--port",
            "6783",
            "--name",
            "a2:38:a5:e4:42:c5",
            "--nickname",
            "vps281854",
            "--datapath",
            "datapath",
            "--ipalloc-range",
            "",
            "--dns-effective-listen-address",
            "172.17.0.1",
            "--dns-listen-address",
            "172.17.0.1:53",
            "--http-addr",
            "127.0.0.1:6784",
            "--dns-domain",
            "kontena.local",
            "--trusted-subnets",
            "",
            "10.135.10.53",
            "10.135.10.214",
            "10.135.11.104",
            "10.135.8.224"
        ],
```
Do you have any workaround for this?

Thanks,
Marek
