### ISSUE TITLE
`kontena app init` products "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by Mrono** [kontena/kontena#253]
Dockerfile gets created but nothing else does
Ubuntu 14.10

**Comment by Mrono** [comment]
Kontena Version 0.9.1

**Comment by nevalla** [comment]
How about if you run `DEBUG=true kontena app init`. Can you provide the backtrace?

**Comment by Mrono** [comment]
$ DEBUG=true kontena app init
Found Dockerfile
/var/lib/gems/2.1.0/gems/kontena-cli-0.9.1/lib/kontena/cli/apps/init_command.rb:75:in `create_env_file': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/kontena-cli-0.9.1/lib/kontena/cli/apps/init_command.rb:39:in `execute'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/2.1.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /var/lib/gems/2.1.0/gems/kontena-cli-0.9.1/bin/kontena:67:in `<top (required)>'
        from /usr/local/bin/kontena:23:in `load'
        from /usr/local/bin/kontena:23:in `<main>'

**Comment by nevalla** [comment]
Thanks. I found the reason for this error and fix is coming.
