### ISSUE TITLE
server: cap grid_service_deploys collection

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2563]
Looks like grid_service_deploys collection just keeps growing, currently 280mb (noticed this with https://github.com/matti/kontena-heroku that runs a free mlab instance that has 0.5gb limit)

Shouldn't this collection be capped along with CONTAINER_STATS_CAPPED_SIZE, EVENT_LOGS_CAPPED_SIZE and CONTAINER_LOGS_CAPPED_SIZE

?

**Comment by matti** [comment]
workaround: running this in kontena-console

```
GridServiceDeploy.collection.client.command(
  convertToCapped: GridServiceDeploy.collection.name,
  capped: true,
  size: 10.megabytes
)
```

**Comment by matti** [comment]
If this collection is capped, then agent will crash:

```
2017-09-02T13:14:27.695718+00:00 app[web.1]: E, [2017-09-02T13:14:27.695591 #8] ERROR -- : Actor crashed!
2017-09-02T13:14:27.695721+00:00 app[web.1]: Mongo::Error::OperationFailure: cannot remove from a capped collection: heroku_9k9k9afsdf.grid_service_deploys (20)
2017-09-02T13:14:27.695722+00:00 app[web.1]: 	/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/result.rb:256:in `validate!'
```

**Comment by SpComb** [comment]
> If this collection is capped, then the server will crash when a stack is removed:

That would be from the `has_many :stack_deploys, dependent: :destroy`

**Comment by SpComb** [comment]
Looks like using a capped collection for the deploys won't work, because there are restrictions on updates to objects in capped collections:

```
api_1      | E, [2017-12-11T10:09:24.259979 #8] ERROR -- StackDeployWorker: failing update: objects in a capped ns cannot grow (10003)
```

```
api_1      | W, [2017-12-11T10:16:27.756392 #9]  WARN -- GridServiceSchedulerWorker: exception: failing update: objects in a capped ns cannot grow (10003) (Mongo::Error::OperationFailure)
```

https://docs.mongodb.com/v3.0/core/capped-collections/#restrictions-and-recommendations
> With MMAPv1, you can only make in-place updates of documents. If the update operation causes a document to grow beyond the document’s original size, the update operation will fail.
