### ISSUE TITLE
What do you think about OVH VPN for deployment ?

### ISSUE THREAD

**Issue by solisoft** [kontena/kontena#261]
Not sure that anyone asked before, but OVH's VPN are very powerful... 
So maybe it's a good idea to be able to deploy on them easily ?

**Comment by jakolehm** [comment]
Do you mean VPS (https://www.ovh.co.uk/vps/)? Don't know it OVH provides rest apis for automation or CoreOS images. But actually Kontena can be installed to any provider pretty easily using our ubuntu packages (or plain docker images).

http://www.kontena.io/docs/getting-started/installing/master
http://www.kontena.io/docs/getting-started/installing/nodes
(scroll down the page)
