### ISSUE TITLE
CLI timeout is too low

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2637]
Could be a few seconds longer and it wouldn't hurt (eg. make the client to be stuck for 20-30s like it used to be with a longer timeout)

```
 [error] Excon::Errors::Timeout : connect_write timeout reached
```

**Comment by jakolehm** [comment]
10s might be better default than current 5.

**Comment by SpComb** [comment]
The default `EXCON_CONNECT_TIMEOUT` is 5 seconds, which is a bit optimistic. You can override that as an env, but the default could be something like 10s.
