### ISSUE TITLE
CLI: kontena master use nonexisting breaks master listing

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2647]
(also minor formatting issue in use)

```
$ kontena master use nonexisting
"Could not resolve master by name 'nonexisting'.\nFor a list of known masters please run: kontena master list"
 [error] Could not resolve master by name 'nonexisting'.
For a list of known masters please run: kontena master list

$ kontena master list
 [error] NoMethodError : undefined method `insert' for nil:NilClass
```

**Comment by SpComb** [comment]
Unable to repro the broken `master list`:

```
$ kontena _1.3.4_ master use nonexisting
"Could not resolve master by name 'nonexisting'.\nFor a list of known masters please run: kontena master list"
 [error] Could not resolve master by name 'nonexisting'.
$ kontena _1.3.4_ master list
NAME                      URL
...
```

Can you include the complete `DEBUG` stack trace from `~/.kontena/kontena.log` for the `NoMethodError : undefined method 'insert' for nil:NilClass`?

**Comment by kke** [comment]
There is a bug in the error message anyway:

https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/master/use_command.rb#L21

There's a `p` before double quotes which makes it print out the message instead of passing to exit_with_error.

**Comment by kke** [comment]
I think Matti's problem could be that there's a server with "null" as name in `.kontena_client.json`
