### ISSUE TITLE
CLI: kontena plugin install to support private git repositories / file paths

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2657]

**Comment by kke** [comment]
Hmm. You just need to `gem install` any gem that has a `lib/kontena_cli_plugin.rb` into any path in `gem env gempath` or `~/.kontena/gems/RUBY_VERSION/gems` for it to get loaded.

The `kontena plugin install` itself just runs a regular gem install with GEM_HOME set to `~/.kontena/gems/RUBY_VERSION/` and prefixes whatever you give as parameter with `kontena-plugin-`.

For example `kontena plugin install vagrant` will run `gem install kontena-plugin-vagrant -i ~/.kontena/gems/RUBY_VERSION/`

**Comment by matti** [comment]
Yes, but would be so much more user friendlier to support paths, so that the command could be `kontena plugin install git://....`

**Comment by kke** [comment]
That would require some sort of git support, but that would be handy with stack install also.

**Comment by matti** [comment]
YES!

**Comment by kke** [comment]
Adding bundler as dependency could bring in something handy
