### ISSUE TITLE
LogWorker shouldn't spam docker logs

### ISSUE THREAD

**Issue by dsmiley** [kontena/kontena#2661]
See https://github.com/kontena/kontena/blob/master/agent/lib/kontena/workers/log_worker.rb#L69
I get this message logged seemly every few milliseconds: `WARN -- Kontena::Workers::LogWorker: queue size is 1600`.  I think this code should never log this same warning more frequently than say 5 seconds.

This isn't a bug; just an improvement.

**Comment by matti** [comment]
Also seeing this.

**Comment by SpComb** [comment]
Those warnings should never be logged more than once every 10s. This might be related to #2232, does it only happen after the agent websocket has reconnected several times?
