### ISSUE TITLE
CLI: stack logs by service

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2712]
```
k stack logs --service a --service b
```

or

```
k stack logs <stack> <a> <b>
```

**Comment by matti** [comment]
workaround

```
          grep_filter="$stack_name.$1"
          shift
          for service in $@; do
            grep_filter="$grep_filter\|$stack_name.$service"
          done
          kontena stack logs $log_opts $stack_name | grep "$grep_filter"
```

**Comment by SpComb** [comment]
The `kontena grid logs` also accepts a `--service`, but unfortunately it looks like this only accepts the bare service name, and it's thus kind of broken for stack services: https://github.com/kontena/kontena/blob/3b5a3d8c2846cd4757ad70a1d23df3eea1000213/server/app/routes/v1/grids_api.rb#L128-L134

```ruby
            unless r['services'].nil?
              services = r['services'].split(',').map do |service|
                @grid.grid_services.find_by(name: service).try(:id)
              end.delete_if{|s| s.nil?}

              scope = scope.where(grid_service_id: {:$in => services})
end
```

This should probably also be fixed to allow `kontena grid logs --service stack/foo`, in addition to `kontena stack logs --service`?
