### ISSUE TITLE
cannot connect to master on ubuntu

### ISSUE THREAD

**Issue by xavierle** [kontena/kontena#2730]
after creating a new master on a fresh ubuntu server

kontena master login --code some code  https://someIP:8443

Connection refused - connect(2) for 51.15.10.66:17920 (Errno::ECONNREFUSED)

any idea ?

**Comment by kke** [comment]
How did you create it?

**Comment by xavierle** [comment]
based on that guide
 https://www.kontena.io/docs/getting-started/installing/ubuntu.html#installing-kontena-master

sudo apt-get install kontena-server

**Comment by kke** [comment]
Did you set up the SSL certificate?

**Comment by xavierle** [comment]
i suppose yes

using command : 
ssh-keygen -t rsa -b 2048 -v

and i put the  .pem certificate adress in the file called  : 
/etc/kontena-server.env

**Comment by kke** [comment]
Maybe the cert you generated is somehow invalid and the load balancer refuses to start with it loaded.

I think you need to sign it:
https://serversforhackers.com/c/using-ssl-certificates-with-haproxy

**Comment by xavierle** [comment]
sure i shall have done something wrong.

thank you for the hint, will review that better

**Comment by xavierle** [comment]
i think i was wrong in the concatenation

https://www.kontena.io/docs/using-kontena/loadbalancer.html

**Comment by jnummelin** [comment]
Based on the last comment I assume things are working now so closing.
