### ISSUE TITLE
Make fluentd forwarded logs more structured by default

### ISSUE THREAD

**Issue by japsu** [kontena/kontena#2735]
Currently when `fluentd` log forwarding is active, the logs contain only these fields

* `source` (`stderr`/`stdout`)
* `log` (the log message)
* `@log_name` or the _tag_ (`node.grid.stack.service.container_number`)

However, `fluentd` is best served structured logs, especially when it is combined with ElasticSearch. The current format makes it a bit cumbersome and inaccurate to filter by stack (`@log_name:*.mystack.*`).

I propose adding `node`, `grid`, `stack`, `service` and `cnt_no` as fields in `fluentd` log forwarding so that we could make concise queries `stack:mystack` etc. Some of these fields could then be dropped from `@log_name`, shortening it and reducing it to eg. `stack.service` or even just `kontena` (remember syslog inputs are often tagged `syslog` or `system`).

This can of course be accomplished with a `filter_parser` in `fluentd`, but the logs should be as useful as possible by default.

**Comment by japsu** [comment]
Btw, this is how I accomplished the transformation in `fluentd`:

```
# Expose tag to next filter
<filter **>
  @type record_transformer
  <record>
    interim_tag_field ${tag}
  </record>
</filter>

# Parse tag into node, grid, stack, service and container number
<filter **>
  @type parser
  key_name interim_tag_field
  time_parse false
  format /^(?<node>[a-z0-9-]+)\.(?<grid>[a-z0-9-]+)\.(?<stack>[a-z0-9-]+)\.(?<service>[a-z0-9-]+)\.(?<container_no>[a-z0-9-]+)$/
  ignore_key_not_exist true
  reserve_data true
</filter>

# Drop extra field
<filter **>
  @type record_transformer
  remove_keys interim_tag_field
</filter>
```

**Comment by jakolehm** [comment]
@japsu we have [open pr](https://github.com/kontena/kontena-stacks/pull/8) in Kontena Stacks repo for many log storage providers.. and there we parse tag like this:

```
<filter **>
  @type record_transformer
  <record>
    node "${tag_parts[0]}"
    grid "${tag_parts[1]}"
    stack "${tag_parts[2]}"
    service "${tag_parts[3]}"
    instance "${tag_parts[4]}"
  </record>
</filter>
```

**Comment by japsu** [comment]
@jakolehm cool, that looks slightly nicer
