### ISSUE TITLE
"Authentication provider not configured" when i try invite a user to master

### ISSUE THREAD

**Issue by greyarch** [kontena/kontena#2744]
hi guys, I get "Authentication provider not configured" when i try invite a user to a master, yet i have configured oauth provider (github). do i need to somehow restart the master after importing the auth settings?

**Comment by kke** [comment]
Did you set all of the required oauth settings?

* oauth2.client_id
* oauth2.client_secret
* oauth2.authorize_endpoint
* oauth2.token_endpoint
* oauth2.userinfo_endpoint
* oauth2.userinfo_scope

**and:**

* server.root_url

**Comment by greyarch** [comment]
I had missed the server.root_url setting. Thanks a lot.
