### ISSUE TITLE
Kontena Uninstall

### ISSUE THREAD

**Issue by osobh** [kontena/kontena#278]
Not sure how to stop and uninstall Kontena server and agents...any help would be appreciated.

**Comment by jakolehm** [comment]
Did you install them to vagrant or some cloud?

**Comment by osobh** [comment]
I have the master setup on Ubuntu 14.04 and all the slaves on ubuntu 14.04

**Comment by jakolehm** [comment]
You can just remove those installed kontena-* packages.

**Comment by osobh** [comment]
that worked for the master, but the slaves show kontena agent 0.9.2 and google/cadvisor. When I stop them they restart, when I delete them they restart, apt-get remove kontena* on the slaves finds nothing. Not sure how to get them off the slaves..

**Comment by jakolehm** [comment]
Thats weird. Try to stop agent first using `sudo service stop kontena-agent`. If that works, just remove `/etc/init/kontena-*` files.

**Comment by osobh** [comment]
ok thank you this worked:

sudo service kontena-agent stop , then docker rm kontena-agent
