### ISSUE TITLE
kontena plugin uninstall does not prompt or accept --force

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2810]
Looks like there's some old `--force` flag being used in the spec that no longer exists:

```
ERROR: Unrecognised option '--force'

See: 'kontena plugin uninstall --help'
  removes installed plugin (FAILED - 1)

Failures:

  1) plugin uninstall removes installed plugin
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/plugin/uninstall_spec.rb:10:in `block (2 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
The `kontena plugin uninstall` prompt/`--force` flag were removed in #2434. Was that by design, or should they be restored?

**Comment by SpComb** [comment]
Let's call this a bug. AFAIK there's no reason why the `kontena plugin uninstall` command shouldn't continue to prompt for confirmation, or accept `--force`.

**Comment by kke** [comment]
I don't see how removing a plugin would make you lose anything. You can just reinstall the plugin.

**Comment by SpComb** [comment]
Either this is a cli bug that needs to be fixed to restore the prompt/`--force`, or then it's a test chore where the e2e spec needs to be fixed to not call `kontena plugin uninstall --force`. I'll accept a PR that does either of those as fixing this issue for 1.4.0...

**Comment by SpComb** [comment]
BTW this is going to be annoying for anyone that's been scripting `kontena plugin uninstall`. They will have necessarily been using `--force` before, and anything like that is going to fail after 1.3 -> 1.4.

Still considering if we shouldn't just reconsider this and revert the `kontena plugin uninstall` change to restore `--force`....

**Comment by jakolehm** [comment]
Could we add `--force` as hidden option just for backwards compatibility?

**Comment by SpComb** [comment]
Didn't happen for 1.4.0, please fix any callers of `kontena plugin uninstall --force`.

Re-open and revive #2937 if this turns out to still be an issue.
