### ISSUE TITLE
Having a dry-run option for stack upgrade would be great

### ISSUE THREAD

**Issue by deiga** [kontena/kontena#2819]
We've got a Continuous Deployment system which acts on certain changes, but we'd also like to verify on Pull Requests that changes don't break deployment.

For this a dry-run option would be awesome, which would talk to the stack and even verify the `kontena.yml` parameters but not make any changes.

**Comment by daniel-bytes** [comment]
`kontena stack validate` might be helpful here.

**Comment by kke** [comment]
#2707 adds `--dry-run` to `stack upgrade`

**Comment by SpComb** [comment]
It depends on what exactly you want to check. The `kontena stack validate` command can be used to check the YAML syntax, but it doesn't show you things like what services will be updated/removed etc.

Same thing for `kontena stack upgrade --dry-run` - it will show installed/upgraded/removed stacks, but it won't be able to show what services changed.

Ideally the server/agent would have some kind of noop update/deploy mode, where it would run the actual code to check for service/container changes, but without actually changing anything.

**Comment by kke** [comment]
Hmm the dry-run could show a diff between current master stack data and the yaml reader.execute output?

**Comment by SpComb** [comment]
> Hmm the dry-run could show a diff between current master stack data and the yaml reader.execute output?

Yeah, some kind of diff would be what's needed to make `--dry-run` actually useful. A diff between the `reader.execute['services']` and `client.get("stacks/#{grid}/#{stack}")['services']` might be useful, but there could be some subtlety involved there too...

#2311 also applies to the `GET /v1/stacks/:grid/:stack` JSON `{ "services": [ ... ] }` data, it's generated from the "deployed" [`stack.grid_services`](https://github.com/kontena/kontena/blob/master/server/app/views/v1/stacks/_stack.json.jbuilder#L15-L17) models, and not from the [`StackRevision.services`](https://github.com/kontena/kontena/blob/4954578b5c7a3b0ee55cc9d8a9ab2435f825b54c/server/app/models/stack_revision.rb#L13) that actually gets "updated" from the [PUT `/v1/stacks/:grid/:stack` JSON `{"services": ... }`](https://github.com/kontena/kontena/blob/4954578b5c7a3b0ee55cc9d8a9ab2435f825b54c/server/app/mutations/stacks/update.rb#L69)... there may be some differences between the two?

**Comment by kke** [comment]
Yyyyep. The GET response is completely different from the PUT data and undiffable.

**Comment by matti** [comment]
@deiga I think what you really need is a testing grid where it can be deployed automatically.

**Comment by deiga** [comment]
@matti Yes and no. Having a testing grid is of course preferable, but that requires extra setup for each app (env variables etc.).
As Ops, we'd like to be able to at least verify automatically that a PR's deployment would work without having to configure the actual app.

**Comment by matti** [comment]
I don't think there is any way to do a meaningful dry-run without actually deploying it.

**Comment by daniel-bytes** [comment]
> I don't think there is any way to do a meaningful dry-run without actually deploying it.

Agree.  That's why I mentioned `stack validate` earlier, checking that `kontena.yml` is not broken is probably the best you can hope for as a pre-deployment check.
