### ISSUE TITLE
Support for `stop-signal`

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#2878]
Docker supports giving a custom `stop-signal` during container creation. This is the signal Docker will send to the main process when container is stopped.

## Example use case:

Nginx uses `SIGTERM` as default stop signal. Unfortunately that does not allow graceful shutdown of nginx and ongoing requests will get dropped. Using `SIGQUIT` stops nginx processes gracefully and thus would allow true zero-downtime deployment with Kontenas default rolling deployment.

**Comment by jnummelin** [comment]
The yaml should be:
```
stop_signal: SIGUSR1
```
Implementation should be fairly straigforward, pretty much like #2767

**Comment by mikkopiu** [comment]
Added quick PR: #2918
