### ISSUE TITLE
Stack yml does not support entrypoint

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2949]
Entrypoint is supported by api.

**Comment by kke** [comment]
![image](https://user-images.githubusercontent.com/224971/31807272-e18ba920-b575-11e7-84f1-a3026ba306f5.png)
![image](https://user-images.githubusercontent.com/224971/31807280-f1fc12c2-b575-11e7-9025-35feedf6dc03.png)
![image](https://user-images.githubusercontent.com/224971/31807293-0100a620-b576-11e7-9bd7-c221f8a93e05.png)
![image](https://user-images.githubusercontent.com/224971/31807306-144ff92e-b576-11e7-8858-16fcdbe5df21.png)

**Comment by kke** [comment]
Nothing about entrypoint in CLI ever.

**Comment by jakolehm** [comment]
Yeah, noticed that too. But still it's a bug.

**Comment by kke** [comment]
1.3  and 1.2 seem to catch entrypoint as invalid in `kontena stack validate`

![image](https://user-images.githubusercontent.com/224971/31807654-1b255f30-b578-11e7-8bbf-3efd90ed168a.png)
