### ISSUE TITLE
grid default affinities

### ISSUE THREAD

**Issue by matti** [kontena/kontena#3000]
having just one default affinity is limiting

**Comment by jakolehm** [comment]
Default affinity is an array... so it should be possible to define multiple default affinities.

**Comment by matti** [comment]
yes, it is - CLI update behaviour with multiple values supported (in this case) was misleading

**Comment by SpComb** [comment]
This is probably a valid docs issue. The [docs](https://www.kontena.io/docs/using-kontena/platform.html#create-a-new-kontena-platform) aren't that great on this, and they actually imply a single default affinity rule: 

> default-affinity - Specify the default affinity rule for the entire Kontena Platform using the affinity filter syntax. The default affinity rule is applied to all Kontena Stacks on this Kontena Platform by default. The most common use case is to prevent Kontena Stack deployments to specific Kontena Nodes unless specified in Kontena Stacks.

The way that multiple `--default-affinity` options work in `kontena grid create` and `kontena grid update` isn't really documented anywhere. The `--help` output doesn't really make it clear that it supports multiple instances of the option either.

**Comment by SpComb** [comment]
https://github.com/kontena/docs/issues/51
