### ISSUE TITLE
grid default affinity not working

### ISSUE THREAD

**Issue by matti** [kontena/kontena#3001]
service gets scheduled to a node that should be banned by the default affinity

```
$ kontena node ls
NAME                            VERSION   STATUS       INITIAL   LABELS
⊛ i-1   1.4.0     online 26h   1 / 1     node=initial
```

```
$ kontena grid current
mygrid:
  default_affinity:
    - label!=node=initial
```

```
$ kontena service show mystack/service
  affinity:
    - label==~node=sticky
    - label==~node=ephemeral
    - label!=node=persistent
  instances:
    mystack/service/1:
      scheduled_to: i-1
```

**Comment by jakolehm** [comment]
Default affinity is used only if service does not specify any affinity rules.

**Comment by matti** [comment]
misunderstood the word default.

**Comment by SpComb** [comment]
https://github.com/kontena/docs/issues/51 this should also be clarified in the docs, the wording on there isn't very clear about this: 

> The default affinity rule is applied to all Kontena Stacks on this Kontena Platform by default.
