### ISSUE TITLE
kontena node label rm exits with code 0 if label not found

### ISSUE THREAD

**Issue by matti** [kontena/kontena#3064]

**Comment by kke** [comment]
Not sure if good or bad.

```
kontena node label rm xyz && kontena node label add zyx
```

It's kind of a success, the end result is that the node does not have the label. On the other hand it's not a success because the action of removing a label was not performed, since it wasn't there in the first place.

**Comment by kke** [comment]
Interestingly, there's no node labels endpoint. It's all done through the nodes-endpoint by updating the node config without the label that is to be removed.

**Comment by kke** [comment]
Also, you can remove multiple labels. Should it refuse to perform if one of the labels to be removed is not found?

**Comment by matti** [comment]
Atleast it could say an error (to stderr) ?
