### ISSUE TITLE
S3FS + RexRay + Third party S3 integration possible?

### ISSUE THREAD

**Issue by piscis** [kontena/kontena#3083]
Hi I have a quick question, I played around with 

https://wasabi.com/

A 100% compatible, as they claim, S3 storage service. I noticed that rexray recently exposed the S3FS_ENDPOINT setting for s3fs via environment variable.

When I create a docker volume with kontena (config below) the buckets get created but the deployment fails because of a error the rexray/s3fs throws. Deploying a container manually and mounting it works.

Do you support wasabi as storage backend or is there some example how to greate a s3fs volumn driver with kontena?

If I do the same with a AWS integration everything works.

### Docker plugin install
```bash
docker plugin install rexray/s3fs S3FS_ENDPOINT='https://s3.wasabisys.com' S3FS_MAXRETRIES=20 S3FS_ACCESSKEY=XXXX S3FS_SECRETKEY=YYYY  REXRAY_LOGLEVEL=debug
```

### Create driver
```bash
kontena volume  create --driver rexray/s3fs --scope instance testvolume
```

### Create driver
```bash
kontena volume  create --driver rexray/s3fs --scope instance testvolume
```

**Comment by jnummelin** [comment]
If wasabi.com is really 100% S3 compatible, I don't see any reason why it shouldn't work. Kontena "just"  instructs Docker to create and mount the volumes, really the same operation you do manually with `docker volume create` +  `docker run -v my-s3-vol:/data ...`

> When I create a docker volume with kontena (config below) the buckets get created but the deployment fails because of a error the rexray/s3fs throws.

What kind or error you see?

**Comment by jnummelin** [comment]
I was able to get volumes running to the point where the bucket is created on wasabi side. 

**BUT**

There seems to be something wrong with rexray, it is able to create the bucket, but when mounting it on a container it actually gets mounted as local storage only. See: https://github.com/thecodeteam/rexray/issues/908
I just included some debug info on the issue, let's see if rexray folks are able to pin down the issue.

One other thing I encountered was this:
```
core@wild-shadow-74 ~ $ docker run -ti -v wasabi-rexray-test:/data alpine sh
/ # ls -lah /data/
total 16
drwx------    2 root     root        4.0K Nov 24 08:38 .
drwxr-xr-x    1 root     root        4.0K Nov 24 08:38 ..
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 133.1G      1.1G    126.4G   1% /
overlay                 133.1G      1.1G    126.4G   1% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
/dev/sda9               133.1G      1.1G    126.4G   1% /data
/dev/sda9               133.1G      1.1G    126.4G   1% /etc/resolv.conf
/dev/sda9               133.1G      1.1G    126.4G   1% /etc/hostname
/dev/sda9               133.1G      1.1G    126.4G   1% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.9G         0      3.9G   0% /sys/firmware
/ # exit
$ docker run -ti -v wasabi-rexray-test:/data alpine sh
/run/torcx/bin/docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/3ddde09ebb0b23c0011ceb685cd3699b18ba019c7954493cd1a58b88d10081b3/rootfs': VolumeDriver.Mount: docker-legacy: Mount: wasabi-rexray-test: failed: error mounting s3fs bucket.
```

So I'm only able to mount the volume once. Mounting it second time always fails. :/

**Comment by piscis** [comment]
I'm getting this error:

```bash
Deployment of service vicoli/wordpress/redis failed:
  - halting deploy of vicoli/wordpress/redis, one or more instances failed
  - GridServiceInstanceDeployer::ServiceError: Docker::Error::ServerError: VolumeDriver.Mount: docker-legacy: Mount: wordpress.redis.testvolume13-1: failed: error mounting s3fs bucket (on node company)
```

**Comment by doncicuto** [comment]
Hi @piscis and @jnummelin,
I copy here my answer for [rexray#849 issue](https://github.com/thecodeteam/rexray/issues/849#issuecomment-346240841) maybe it can solve your issue in Kontena.

If you want to install the plugin using a 3rd party like minio or wasabi, you should use S3FS_OPTIONS and specidy the URL that you use in the S3FS_ENDPOINT as @clintkitson mentioned, but there's a typo it should be S3FS_OPTIONS="url=http://..." removing the -o. For example: 

`docker plugin install rexray/s3fs S3FS_OPTIONS="allow_other,use_path_request_style,nonempty,url=http://127.0.0.1:9000" S3FS_ENDPOINT="http://127.0.0.1:9000" S3FS_ACCESSKEY="xxxxxxxxxxxxxxxx" S3FS_SECRETKEY="xxxxxxxxxxxxxxxxxx" --alias s3fs --grant-all-permissions`

Hope that helps!

**Comment by jnummelin** [comment]
@piscis did you test with the `S3FS_OPTIONS` pointing to Wasabi?

I was able to use volumes with Wasabi

**Comment by piscis** [comment]
@jnummelin yes it works for me thank you

**Comment by jnummelin** [comment]
Closing, revealed to be docs/usability thing in rexray side

**Comment by Tariqu** [comment]
same compose file used by my mate it worked in there system but in mine it doesn't. 
Volume is creating But at the time of mounting I am getting this error

ERROR: for node-server  Cannot create container for service server: VolumeDriver.Mount: docker-legacy: Mount: code2rockenvironmentsfile: failed: error mounting s3fs bucket

ERROR: for server  Cannot create container for service server: VolumeDriver.Mount: docker-legacy: Mount: code2rockenvironmentsfile: failed: error mounting s3fs bucket
ERROR: Encountered errors while bringing up the project.

**Comment by himalreddy** [comment]
@Tariqu Have you found solution?
