### ISSUE TITLE
kontena stack install fails in 1.4.1 with KONTENA_URL=...

### ISSUE THREAD

**Issue by matti** [kontena/kontena#3089]
```
kontena stack install kontena/ingress-lb
```
works, but

```
KONTENA_URL=https://master.eu-west-1.kontena.cloud KONTENA_TOKEN=asdfasdf KONTENA_GRID=my-grid kontena stack install kontena/ingress-lb
```

fails with

```
[error] NoMethodError : undefined method `stacks_url' for nil:NilClass
```

/usr/local/Cellar/kontena/1.4.1/libexec/gems/kontena-cli-1.4.1/lib/kontena/cli/stacks/common.rb:208
```
    # @return [Kontena::StacksClient]
    def stacks_client
      @stacks_client ||= Kontena::StacksClient.new(current_account.stacks_url, current_account.token, read_requires_token: current_account.stacks_read_authentication)
    end
```

**Comment by kke** [comment]
I think a workaround is to set `KONTENA_CLOUD_TOKEN` to anything

**Comment by SpComb** [comment]
This looks like it could be a regression in 1.4.1 from #3013. Previously the `load_settings_from_env` would skip the config file and unconditionally load a skeleton `kontena` cloud account if `KONTENA_URL` was set... the cloud account would use the `KONTENA_CLOUD_TOKEN` env as the token if set, allowing commands like `kontena stack install` to work for GET requests without a token, but commands like `kontena stack registry push` would fail without also having `KONTENA_CLOUD_TOKEN`.
