### ISSUE TITLE
Docker client in kontena/cli needed?

### ISSUE THREAD

**Issue by yuruki** [kontena/kontena#3092]
Is the (very old) docker client really needed in kontena/cli image? It often makes sense to do the docker stuff with docker (if you need to set labels, for example) and kontena stuff with kontena/cli.

Some pipeline tools inject their docker client into any builder image, in which case the included client gets in the way.

**Comment by SpComb** [comment]
The `docker` CLI in the `kontena/cli` image is used for `kontena stack build`, but I'm pretty sure that's the only usage. However, it's hard to run `kontena stack build` in the CLI container without having an embedded `docker` CLI.

**Comment by yuruki** [comment]
Fair enough. Any chance to see the client upgraded (for multi-stage Dockerfiles and stuff) or maybe providing a version of kontena/cli without the client? I just don't feel like maintaining a fork for it.

**Comment by jakolehm** [comment]
@yuruki see #3177
