### ISSUE TITLE
Env missing for setting global haproxy options

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#3356]
From community slack:

> I've been trying to setup my LB to force tls v1.2 with no luck.... typically I'd add something like "ssl-default-bind-options force-tlsv12" in the global section of haproxy config

**Comment by kke** [comment]
https://github.com/kontena/kontena-haproxy/pull/7 related?

**Comment by jakolehm** [comment]
> kontena/kontena-haproxy#7 related?

Nope.

**Comment by sbrocher** [comment]
Thanks so much, this works great!
