### ISSUE TITLE
Ubuntu 14.04 Vagrant issue

### ISSUE THREAD

**Issue by Knoxvillain** [kontena/kontena#355]
Hi,

When trying to run the  kontena master vagrant create command on Ubuntu 14.04 by following the quick start guide, Vagrant always fails to initialize with:

$ kontena master vagrant create
Creating Vagrant machine kontena-master-white-shadow-98 ... \Vagrant failed to initialize at a very early stage:

Vagrant is attempting to interface with the UI in a way that requires
a TTY. Most actions in Vagrant that require a TTY have configuration
switches to disable this requirement. Please do that or run Vagrant
with TTY.
done
Waiting for Kontena-master-white-shadow-98 to start...

This is using Virtualbox 4.3 from the Virtualbox repos, Ruby 2.2.3 via rbenv (the Ruby portion of this: https://gorails.com/setup/ubuntu/14.04), and I've tried with Vagrant from both the Ubuntu repository and via the Vagrant package (1.7.4). Vagrant does work on it's own, but kontena still can't create the master via Vagrant.

**Comment by Knoxvillain** [comment]
I managed to get it working by running the vagrant init command again. If I write up a step by step for Ubuntu 14.04 where should that go? Thanks!

**Comment by nevalla** [comment]
Hi,

Good to hear you've got your problem solved. It would be great to have a step by step guide, we could publish it for example on our blog. Would that be okay?

**Comment by Knoxvillain** [comment]
Sure, the master appears okay and they can be created and destroyed but when I spin up nodes they won't connect to the master so I probably need to review the steps at least once or people will end up with happily running masters but no nodes to connect to! ;-)

Is there an official list of versions of Virtualbox, Ruby, and Vagrant that are recommended? Thanks!

**Comment by jakolehm** [comment]
I don't think there is really an official list for those.. for Ruby >= 2.0 version should be good. Virtualbox 4.3 and 5.0 seems to work fine.

**Comment by jnummelin** [comment]
let's document some working combinations as this has been discussed in Gitter also:
https://gitter.im/kontena/kontena?at=5768511b4227fdc92298edfa
