### ISSUE TITLE
kontena connect without http://

### ISSUE THREAD

**Issue by miskun** [kontena/kontena#36]
at the moment `kontena connect` is expecting host and port information with protocol info included. it should be possible to use connect without protocol, like:

```sh
kontena connect 192.168.66.100:8080
```

**Comment by jakolehm** [comment]
Which one is the default, secure (https/8443) or insecure (http/8080)?

**Comment by jakolehm** [comment]
I would prefer https but then we have to create self-signed certificates automatically or user is lost.

**Comment by miskun** [comment]
I agree. https is preferred in my opinion. if we do self-signed certificates by default, do we need to support standard http at all?

**Comment by miskun** [comment]
This issue is now obsolete. See issue #38.
