### ISSUE TITLE
Weave Scope

### ISSUE THREAD

**Issue by faddat** [kontena/kontena#378]
You've already got weave on each node.  I'd like to strongly recommend that you check out github.com/weaveworks/scope and just... toss it in there somewhere.  It's gorgeous and will make your platform more readily understood.

**Comment by bobcolner** [comment]
+!

**Comment by jakolehm** [comment]
Not sure but I think it should be possible to deploy weave scope as a service using daemon strategy?

**Comment by jakolehm** [comment]
Just tested, it's not possible because there are some hardcoded things inside scope image.

**Comment by jakolehm** [comment]
Update: it seems to run quite ok.. see this example: https://github.com/kontena/examples/tree/master/weavescope#weave-scope-on-kontena
