### ISSUE TITLE
Add KONTENA_LB_PATH for redirect on path, without removing it like VIRTUAL

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#380]
Allow `KONTENA_LB_VIRTUAL_PATH` or `KONTENA_LB_VIRTUAL_PATHS` to contain comma separated paths, like `KONTENA_LB_VIRTUAL_HOSTS`

**Comment by hans-d** [comment]
better to have a separate option. Virtual path is now removed, with multiple paths one would like to keep the paths. 
`KONTENA_LB_PATH` could be used to select the correct backend, like its `VIRTUAL` cousin, but the path does not get removed

**Comment by jakolehm** [comment]
It seems that some websockets libraries require this.
