### ISSUE TITLE
Define Kontena infrastructure by Vagrantfile

### ISSUE THREAD

**Issue by Tails** [kontena/kontena#381]
Currently we are supposed to use commands like `kontena master vagrant create` to define the infrastructure. Is it possible to define the Kontena infrastructure using a Vagrantfile or Terraform file?

**Comment by jakolehm** [comment]
Short answer: yes

Basically you just need to provision master/nodes using you favorite tool with coreos (or ubuntu) image + cloudconfig yml file. It's also possible to provision with any Linux distro with docker and just start kontena master / agent containers.

**Comment by jnummelin** [comment]
One can dump the needed (CoreOS) cloud-config for a given grid with `kontena grid cloud-config`. Plus we have instructions for docker-compose based setup. That should provide enough information to create infrastructure setup for any given tool.
