### ISSUE TITLE
Why is linking needed?

### ISSUE THREAD

**Issue by Tails** [kontena/kontena#382]
I understand Kontena creates a VPN automatically when creating a Grid. Why then are container links still needed? Docker will deprecate these in the future in favor of service discovery. 

Is it not possible for load balanced services to discover their load balancers on their own?

**Comment by alexw23** [comment]
You can do it through `external_links` in kontena.yml or `-l lb` in service create/update

**Comment by nevalla** [comment]
Actually you don't need VPN to connect containers together. VPN is only needed when a user wants to connect to container. Services discover other services automatically on the same grid via DNS, so no links are needed. Kontena uses links basically only for internally, for example deploying services on correct order, but they are not necessary. 

Only real use case when you need links is attaching service to load balancer. I don't know do we use `links` property in future or deprecate them as Docker has done and switch to use some Kontena specific property, but let's use links at this moment.

If you have a load balancer part of your application and it is described in `kontena.yml` you can use `link` property. If you have a shared load balancer between multiple applications and it is not described in `kontena.yml` as a part of your application you can use `external_links` property to attach services to the load balancer.

**Comment by Tails** [comment]
Thanks!
