### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by alexw23** [kontena/kontena#383]
Loving this project - it's the perfect level of abstraction from docker and cluster components. Much prefer convention over configuration! The only component missing from my cluster is a secrets vault - I can see the documentation and the code in master but it hasn't been released yet? Will this be released in a 0.12.x? or 0.13.0? :+1: :+1:

**Comment by nevalla** [comment]
Hi, thanks for the kind words, I love it too :) Vault is already merged to master branch (#357) and it is scheduled to 0.11 release, so not so far away. The main implementation is done but we are paying more attention to test it carefully before releasing it. It's going to be awesome feature.
