### ISSUE TITLE
load balancer functionality tied to image name, need BYOLB

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#389]
The current load balancer is tied to a hard coded image name it seems:
- https://github.com/kontena/kontena/blob/daa4634d2a408a6033d4c35d7120564afa3dc8d2/server/app/models/grid_service.rb#L56
- https://github.com/kontena/kontena/blob/daa4634d2a408a6033d4c35d7120564afa3dc8d2/server/app/models/grid_service.rb#L5

when wanting to supply my own LB, eg because I want to modify the config a bit, this fails.
Eg Dockerfile for my LB:
```
FROM kontena/lb:latest
ADD confd /etc/confd
```

* BYOLB: Bring Your Own Load Balancer

**Comment by hans-d** [comment]
or, as a first step, should allow for Bring Your Own Load Balancer Config Template

**Comment by miskun** [comment]
@hans-d I got impression you have some improvements to Kontena Load Balancer? If you don't mind, you can create pull request to https://github.com/kontena/kontena-loadbalancer repo so we could make those improvements available to all. At the moment, we are quite busy baking the new release :)

Also, not directly related to this topic: I feel it's good to have all issues in here. Even ones that are not related to this repo; like LB itself. So, if you find some issues with Kontena LB or some improvement ideas, let's post them in here. Just like you have done so far.

**Comment by hans-d** [comment]
@miskun Currently noting what I encounter, not all is coded (yet?). Certainly will create PRs when I have something implemented.

**Comment by jakolehm** [comment]
This has been fixed in #361 . You should be able to point service to any image/service that acts as a lb.

**Comment by jakolehm** [comment]
Just realized that #361 does not fix this completely...

**Comment by jakolehm** [comment]
Fixed in #443
