### ISSUE TITLE
LB config should be able to specify accept-proxy and send-proxy

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#390]
~~currently the source IP gets lost.~~ Source ip is forwarded for http(s) using X-Forwarded-For (option forwardfor)
For http(s) `bind *:<port> accept-proxy` and `sever [..] send-proxy` should be possible
In case of TCP this should be more configurable, separately for bind and server.

**Comment by jakolehm** [comment]
Fixed in https://github.com/kontena/kontena-loadbalancer/pull/38
