### ISSUE TITLE
Kontena app deploy command is doing too much work

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#403]
`kontena app deploy` command is very handy when deploying application first time. It creates services, build and push images and makes deploys just with one command. But when application is already deployed it is not so handy anymore. User might want to only update application config or just deploy service after image is updated. Now `app deploy` updates service config from kontena.yml including environment variables and deploys application services.

My propotion is that we reserve `kontena app deploy` command only for doing deploys, nothing more. In addition we can introduce `kontena app up` command to do current workflow.

So we could have the following workflows:

**App does not exist yet**

```
kontena app create
kontena app build
kontena app deploy
```

**App exists and user wants to update image and make deploy**

```
kontena app build
kontena app deploy
```

**User wants to update app configuration**

```

kontena app update
```

**User wants to deploy application after images has been updated for example in docker hub**

```
kontena app deploy
```

**User wants to setup application in one command**

```
kontena app up
```

What do you think?

**Comment by hans-d** [comment]
Not quite understanding the differences yet. What are the main differences between `deploy`, `update` and `up`, in terms of:
- (re-)pulling images already on the node
- containers already deployed
- changes in the local kontena.yml, excl underlying Dockerfile (compared to current running app)
- changes in the underlying Dockerfile

And what do you mean exactly by 'deploy' and 'app configuration'

**Comment by nevalla** [comment]
Differences between commands are:

**kontena app update**
updates service(s) configuration from kontena.yml to kontena master. No direct changes to running containers.

**kontena app deploy**
requests Kontena master to deploy service(s) with existing service configuration. Agents will pull images and containers are replaced with new ones.

If Dockerfile is changed **kontena app build** is needed to run before deploy.

**kontena app up**
creates or updates services, builds and pushes image if image not exist and makes deploy. Command is doing somewhat similar what `docker-compose up` does.

By 'deploy' I mean similar function than `kontena service deploy` does. 'App configuration' or 'Service configuration' includes all options that are saved to service from kontena.yml.

**Comment by hans-d** [comment]
:+1:

**Comment by jakolehm** [comment]
:+1:

**Comment by mtrofimm** [comment]
:+1:

**Comment by jnummelin** [comment]
I think this can be closed in favor of stacks.
