### ISSUE TITLE
KONTENA_LB_VIRTUAL_PATH acl too greedy

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#442]
given `KONTENA_LB_VIRTUAL_PATH=path`

produces
```
acl host_project-service_path url_beg /path
[...]
reqrep ^([^\ :]*)\ /path[/]?(.*)     \1\ /\2
```

but does also capture: `host/paths`.

**Comment by jakolehm** [comment]
Can you give an example where this happens?

**Comment by hans-d** [comment]
I see this happen with the kontena loadbalancer.
- have a LB
- have a nginx service, pointing to LB, with `KONTENA_LB_VIRTUAL_PATH=path`
- use the LB, eg via curl, using `/path`
- again, use `/pathtomuch`

**Comment by jakolehm** [comment]
Virtual path match is done using `url_beg`, so it will match all paths starting with given string. Maybe workaround is to use `KONTENA_LB_VIRTUAL_PATH=/path/`?

**Comment by hans-d** [comment]
closing. can be handled by config, and by means of this issue it's now documented.
