### ISSUE TITLE
enh: add pre-build hook

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#479]
Currently, images can be build directly from a Dockerfile and pushed to a registry.
Would be nice if something can be started before the `kontena app build` does the docker building

Use case:
- have a dockerfile BUILD that has various extras needed to do the build, making it quite bloated
- have a dockerfile RUN that is much smaller and picks up the results from runnnig BUILD (eg via a COPY).

Currently using make to manage this build. Happy just to have some pre-build hook to invoke this makefile.

**Comment by nevalla** [comment]
Yes this would be handy. For example having a node.js app that produces some javascript and html files. With this I could just run some npm commands before docker build instead of running those steps in Dockerfile or manually.
