### ISSUE TITLE
coreOS

### ISSUE THREAD

**Issue by vialcollet** [kontena/kontena#48]
Hi.
This projects looks promising.
Is it possible to run the server and the agents on coreOS?
If yes, what would be the setup process?

Thx

**Comment by nevalla** [comment]
With CoreOS, we'd like to have some kind of updating tool. You can use cloud config to setup the system but maintaining and updating the system is challenging. And this is something we are currently working on. So, stay tuned! In meanwhile, if you are interested, you can play around with our current CoreOS setup templates in [kontena-jumpstarter](https://github.com/kontena/kontena-jumpstarter) repo. They might (or might not) work :)

### Kontena Master Node
https://github.com/kontena/kontena-jumpstarter/blob/master/lib/kontena/configurator/user_data/master.yml.erb

Where current values of variables are:
```
kontena_version: '0.6.1',
redis_version: '2.8',
mongo_version: '3.0',
haproxy_version: 'latest'
```

### Kontena Host Nodes
https://github.com/kontena/kontena-jumpstarter/blob/master/lib/kontena/configurator/user_data/node.yml.erb

Where current values of variables are:
```
kontena_version: '0.6.1',
weave_version: '0.10.0',
cadvisor_version: '0.12.0',
master_uri: '<uri of master node>', # for example ws://master_node_ip:8080
grid_token: '<grid token>',
node_number: 1...254 # incremental value for each node
discovery_url: '' # you can get it from here: https://discovery.etcd.io/new?size=<initial_cluster_size>

**Comment by vialcollet** [comment]
Ok I see. As long as updates are not handled, that will be an issue I guess.
But I'll give it a try right now, I am curious :)

Thanks

**Comment by nevalla** [comment]
:+1: 

Please share how did it go and if there are something that we can improve there!
