### ISSUE TITLE
show more info about nodes

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#508]
the `kontena node show <node>` should show:
- the last reported agent version (and an indicator if there is a mismatch)
- first connect
- grid
- master url (as used in agent config)
and some basic stats: 
- disk free
- mem free
- cpu load
- number of running containers
- uptime

the `kontena node list` should show, eg via `--details`, some more info
- last seen
- public ip
- last reported agent version
- os
and eg via `--stats` some basic stats as per `node show`

**Comment by jakolehm** [comment]
Related https://github.com/kontena/kontena/pull/607

**Comment by jakolehm** [comment]
Closing this because #607 implements stats. Let's create separate issues for other things if needed.
