### ISSUE TITLE
fatal docker deploy errors should prevent container from being redployed

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#509]
errors like `ERROR -- Kontena::ServicePods::Creator: Docker::Error::ConflictError: Conflicting options: -h and the network mode (—net)` should cause the container/service not to be redeployed again.

Currently they get stuck in a redeploy loop, causing a high load also on the master machine

**Comment by jakolehm** [comment]
Fixed in upcoming 0.12.0 version.
