### ISSUE TITLE
distribute cli via installer (instead of gem)

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#511]
Just like vagrant... https://github.com/mitchellh/vagrant-installers

**Comment by jakolehm** [comment]
Now that Windows and OSX is going to have better Docker  support (https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) maybe we could package cli as a docker image and just install wrapper script to host?

**Comment by jnummelin** [comment]
There is work ongoing to create installers with https://github.com/chef/omnibus

see #1019

**Comment by kke** [comment]
OSX installer now available

**Comment by SpComb** [comment]
Omnibus installer is available for OSX, let's use new issues for tracking other missing platforms.
