### ISSUE TITLE
grid list-users --> grid users list

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#512]
`kontena grid` has some user specific subcommands: `list-users`, `add-users`, `remove-user`.

Suggest to make this into another subcommand:
- `kontena grid users list`
- `kontena grid users add`
- `kontena grid users remove`

and deprecate the current ones (like `kontena deploy`)

**Comment by jakolehm** [comment]
I agree :)

Related PR's: 
- https://github.com/kontena/kontena/pull/505 
- https://github.com/kontena/kontena/pull/482
