### ISSUE TITLE
move vpn and registry under grid

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#522]
`kontena vpn create` is normally executed only once per grid, same for `kontena registry`.

To declutter the root level commands, these could be move under grid, eg `kontena grid vpn create`

**Comment by jnummelin** [comment]
Vpn and registry are truly once per grid type of services so I think it would make sense to move them under grid commands. What do you think @nevalla & @jakolehm ?

**Comment by nevalla** [comment]
I think the initial thought was that on the CLI all commands are executed within the grid scope (`service`, `app`, `container`, `vault` etc). IMHO that is still a valid idea and moving only `vpn` and `register` commands under the `grid` command might be also confusing.

**Comment by jnummelin** [comment]
Solid point. I think we can close this.
