### ISSUE TITLE
CLI: Terminate Digital Ocean node reports error (404) 

### ISSUE THREAD

**Issue by luislavena** [kontena/kontena#537]
Hello folks,

When trying to destroy all the nodes of a grid, first I ensured no app/service was defined or running on the nodes, and then proceed to use `node digitalocean terminate`:

```
$ kontena node digitalocean terminate  --token $DO_TOKEN frosty-field-48
Terminating DigitalOcean droplet frosty-field-48 ... fail
404: {"id":"not_found","message":"The resource you were accessing could not be found."}
```

This happened with every node that was terminated, but looking at Digital Ocean dashboard, I see the nodes were terminated properly.

Perhaps the CLI is attempting to grab the node status and it has already been removed from DO?

Thank you
:heart: :heart: :heart:

**Comment by luislavena** [comment]
Sorry, hit sent too soon.

I noticed that after removing the nodes, they are still listed as part of the grid but with `offline` state:

```
$ kontena node list
Name                           OS                                       Driver          Labels                         Status    
damp-dew-69                    CoreOS 835.13.0 (4.2.2-coreos-r2)        overlay         region=nyc3                    offline   
frosty-field-48                CoreOS 835.13.0 (4.2.2-coreos-r2)        overlay         region=nyc3                    offline   
patient-forest-32              CoreOS 835.13.0 (4.2.2-coreos-r2)        overlay         region=nyc3                    offline   
```

**Comment by nevalla** [comment]
Thanks for the information. Kontena tries to delete droplet first on DigitalOcean and after that it will remove it from Master. Now it seems that checking the status of droplet after deletion fails and node is not removed from Master correctly. https://github.com/kontena/kontena/blob/master/cli/lib/kontena/machine/digital_ocean/node_destroyer.rb#L23

I will check is DO API changed somehow that could cause this issue.

You can delete those offline nodes with  `kontena node remove NODE_ID` command.

**Comment by luislavena** [comment]
@nevalla thanks for the promptly response.

For reference, here are the relevant gem versions:

- kontena-cli (0.11.6)
- droplet_kit (1.3.3)
