### ISSUE TITLE
Few Questions about Grid and Networking

### ISSUE THREAD

**Issue by fbrbovic** [kontena/kontena#545]
I've just discovered kontena, and I am considering using it but I have few questions that maybe someone can answer for me.

1. Can services in one grid link to other services on another grid ?
2. Can one host/node contain multiple grids ?
3. Are all of the services/containers within the grid accessible to each other ? and if so is it possible that access between the services is restricted unless they are linked to each other ?
4. Is it possible for host/node to provide multiple IPs to choose from to all of the containers

Thank you

**Comment by miskun** [comment]
Hi! Here's some answers:

1. No. Each grid is isolated virtual private network and therefore services can not be linked between virtual private networks. Therefore, the only viable options at the moment to link services from different grids are a) linking over Internet; or b) create some kind of VPN tunnel service that will connect the two grids together.
2. No. At the moment a host may belong only to a single grid. However, we have some ideas how to make it possible for node to serve multiple grids at once but this technology is not yet available.
3. Yes. All services in a grid can access other services. You can connect to other services using the DNS address that is assigned to each service. We don't have option to restrict the access between services in a single grid.
4. This one I don't understand. Maybe somebody else can answer this?

Thank you for your questions! I think this stuff will end up in Kontena FAQ at some point :)

**Comment by fbrbovic** [comment]
Thank you for the quick response. 

I am kind of surprised that majority of container orchestration tools don't have some kind of way to restrict access between containers. It seems almost a requirement for any serious deployment.

**Comment by miskun** [comment]
Yes. The reason is: it is not so secure as you might think :) The correct way to restrict communication between services (in a grid) is to use networks. I hope we have some time to make it reality in near future. See #343

**Comment by fbrbovic** [comment]
Yes implementing networks would be one way to solve that problem, and I would assume you would have ways to route the networks and possibly add firewalls in between them.

**Comment by jakolehm** [comment]
I agree that it would solve most of these problems if we add support for separate networks within a grid.

**Comment by jnummelin** [comment]
closing in favor of: #343
