### ISSUE TITLE
cli: service update command overwrites some parameters

### ISSUE THREAD

**Issue by msokk** [kontena/kontena#563]
CLI version: 0.11.7

When running `kontena service update --link lb ...` on a service with secrets, all those secrets will be removed from service.

Haven't tested other combinations yet.

**Comment by msokk** [comment]
Also updating `--env` clears secrets.

This brings me to question, how does one unset stuff. Environment variables have explicit command such as `add-env` and `remove-env`.

Should there be an unset counterpart for each param? `--unset-link lb`?

**Comment by jakolehm** [comment]
Fixed in #574
