### ISSUE TITLE
Hide/redact vault secrets in master API

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#578]
Currently the master API e.g. `v1/grids/:grid_name/services` exposes all attached secrets as environment variables. This action is also not audited.

I would suggested redacting or hiding environment variables that are injected as secrets.

**Comment by jakolehm** [comment]
This needs more investigation. Cannot reproduce this with 0.11.7.

**Comment by christofferh** [comment]
Okay, I'll try and repro it.
