### ISSUE TITLE
kontena/lb sticky session / backend affinity

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#582]
My app is a classic symfony2 web app. I'm testing scaling. 
I noticed that haproxy is not configured neither to use ip-based backend affinity nor sticky session.

Is there a way to fix that?

**Comment by jakolehm** [comment]
You can change this behaviour via `KONTENA_LB_BALANCE` env variable. For ip based affinity value should be `source`. 

These env variables are documented here: http://www.kontena.io/docs/using-kontena/loadbalancer .
