### ISSUE TITLE
Deployment output

### ISSUE THREAD

**Issue by msokk** [kontena/kontena#601]
It would be great to see more output while deploying apps/services.

Something like image pulling output.

**Comment by matti** [comment]
Especially when deploys fail. Usually you need to hunt down the reason from grid/service logs..

**Comment by matti** [comment]
It seems that if agent is unable to deploy from external registry because of authentication issues, the deploy will be "... done" in CLI after agent `ERROR -- Kontena::ServicePods::Creator: Docker::Error::NotFoundError`

**Comment by matti** [comment]
list of possible errors:

- no port available on the node
- agent can not pull from the registry (invalid credentials OR ssl OR network connectivity)
- memory limit prevents deploy
- affinity rule can not be satisfied
- there is a container with the same name already running (somehow not managed by kontena)
- (kontena.yml has changed, revert to last known)

**Comment by SpComb** [comment]
These sound like kontena-server `GridServiceDeployer` -> `GridServiceScheduler` error cases for #1028 ( "Cannot find applicable node for service instance ..."):

> * no port available on the node
> * memory limit prevents deploy
> * affinity rule can not be satisfied

These sound like kontena-server `GridServiceDeployer` -> kontena-agent  `Kontena::ServicePods::Creator` errors:

> * there is a container with the same name already running (somehow not managed by kontena)
> * agent can not pull from the registry (invalid credentials OR ssl OR network connectivity)

**Comment by SpComb** [comment]
Closing because deployment errors are reported reasonably well now.

#2114 is the issue for better deploy progress status output on the CLI. The server API already reports the per-instance deploy state.
