### ISSUE TITLE
Grid log tailing crashes with EOFError after a minute

### ISSUE THREAD

**Issue by msokk** [kontena/kontena#624]
Running `kontena grid logs -t` crashes at some point (usually a minute or two) with message
```
kontena-agent | I, [2016-04-20T13:51:52.163798 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
end of file reached (EOFError)
```

Looks like something in publishing node stats contains invalid character.

**Comment by jakolehm** [comment]
Most likely this is an issue with kontena master haproxy timeouts.
