### ISSUE TITLE
Ubuntu does not work with latest version of docker

### ISSUE THREAD

**Issue by webflo** [kontena/kontena#667]
Kontena requires docker-engine (< 1.11) but 1.11.\* is already released.

```
apt-get install kontena-server -y

The following packages have unmet dependencies:
 kontena-server : Depends: docker-engine (< 1.11) but 1.11.1-0~trusty is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by jakolehm** [comment]
Kontena does not (yet) support docker 1.11.x. Mainly because cadvisor does not have stable version that brings support for docker 1.11.x.

**Comment by webflo** [comment]
v0.23.0 supports Docker v1.11 according to the Changelog https://github.com/google/cadvisor/blob/v0.23.0/CHANGELOG.md

**Comment by webflo** [comment]
Related to #668

**Comment by jnummelin** [comment]
Latest changes in #1950 to Docker dependencies have updated to support also the ee and ce packages so I think this can be closed.
