### ISSUE TITLE
Force write/upsert vault secrets

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#673]
I'm programatically adding/updating secrets with the master API and would like to avoid to keeping track of whether to use the `update` or `write` action.

Are you up for including support to make it possible to do e.g. `POST /v1/grids/grid_id/secrets` with an optional argument for doing an upsert operation of the secret if already present?

Exposed in the CLI I imagine it could be something similar to:
`kontena vault write MY_SECRET *secret* --force` or
`kontena vault write MY_SECRET *secret* --upsert`

If yes I'm happy to submit a PR.

**Comment by jakolehm** [comment]
Makes sense to me. Correct http verb might be `PUT` for `--upsert` option?

/cc @nevalla

**Comment by nevalla** [comment]
Sounds good, go ahead!

+1 for `--upsert`

**Comment by jnummelin** [comment]
implemented in #711
