### ISSUE TITLE
StatsWorker: undefined method `count' for nil:NilClass

### ISSUE THREAD

**Issue by mikkopiu** [kontena/kontena#678]
kontena-etcd logs an Error `ERROR -- Kontena::Workers::StatsWorker: error on stats fetching: undefined method 'count' for nil:NilClass` from stats_worker.rb#L71 when (I think) `::per_cpu_usage` is `nil`.

Here's the approriate line: `num_cores = current_stat[:cpu][:usage][:per_cpu_usage].count` from `send_container_stats`.

Surely not a huge issue, but seems like an issue nonetheless.

kontena-agent version is 0.12.2 and docker version is 1.8.2-el7.

**Comment by jnummelin** [comment]
fixed in #769
