### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#704]
We should add first class Let's Encrypt support to Kontena Master that uses dns based verification and writes certificate to Kontena Vault. This allows to use LE certificates on any service that can handle certs from environment variables (not only Kontena Loadbalancer).

**Comment by mtrofimm** [comment]
@jakolehm is there any hope to include this feature earlier than 0.16.0 ?

**Comment by mtrofimm** [comment]
there also an interesting solution for webroot based letsencrypt verification for haproxy: https://github.com/janeczku/haproxy-acme-validation-plugin

**Comment by jakolehm** [comment]
@mtrofimm there is always hope :) This will be in 0.15 if we have time to test this properly.
