### ISSUE TITLE
Mixed DC network issue

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#705]
related to #247 

There is some issue with weave in mixed environment.
My case is as follows. I have 3 nodes in digitalocean.
When I add a node from OVH, the weave container is created to use digitalocean private IPs 
docker inspect weave (at OVH node)

[....]
        "Path": "/home/weave/weaver",
        "Args": [
            "--port",
            "6783",
            "--name",
            "a2:38:a5:e4:42:c5",
            "--nickname",
            "vps281854",
            "--datapath",
            "datapath",
            "--ipalloc-range",
            "",
            "--dns-effective-listen-address",
            "172.17.0.1",
            "--dns-listen-address",
            "172.17.0.1:53",
            "--http-addr",
            "127.0.0.1:6784",
            "--dns-domain",
            "kontena.local",
            "--trusted-subnets",
            "",
            "10.135.10.53",
            "10.135.10.214",
            "10.135.11.104",
            "10.135.8.224"
        ],
Do you have any workaround for this?

Thanks,
Marek

**Comment by nevalla** [comment]
@mtrofimm proposed PR will fix this issue, but current workaround is to ssh into OVH node and tell weave to connect to DO node with public ip: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock weaveworks/weaveexec:1.4.5 connect <do_public_ip>`. You can tell weave to connect several DO nodes by repeating the command.

**Comment by mtrofimm** [comment]
@nevalla thx!
