### ISSUE TITLE
Ubuntu docker.io package compatibility

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#730]
Ubuntu renamed docker-engine to docker.io in 16.04

**Comment by d2s** [comment]
This would be important for our future testing environment,
because it would enable usage of more recent Ubuntu version.

**Comment by jakolehm** [comment]
Ubuntu 16.04 packages are now merged with #1150 (will be part of 0.16 release). They still depend on "official" docker packages so docker.io package is not supported.

**Comment by SpComb** [comment]
#1173 added Ubuntu xenial `docker.io=1.12*` support.

**Comment by jnummelin** [comment]
Close via #1150 & #1173
