### ISSUE TITLE
deploy agents by SSH

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#737]
It will be great to have a feature to deploy kontena agents by ssh, Any Linux OS with correct docker version must be valid.

Rancher has a similar feature, is very handy and save couple of extra steps.
As bonus, mostly any distro will work out-of-the-box

This will allow too, to deploy agents without internet connection (as in a internal network)

I find quite frustrating tha tI am "forced" to use a very specific ubuntu version + very specific docker version

**Comment by jakolehm** [comment]
Actually you can install master & agent just by starting docker containers with right run options.

**Comment by nevalla** [comment]
@jalberto you can try with these commands (taken from cloudinit files)
https://gist.github.com/nevalla/c4b3362623c0e3e9f03d3122e530a4ff

**Comment by nevalla** [comment]
Just noticed that docker run are missing -d options. Will update gist.

**Comment by jnummelin** [comment]
Docs have now instructions how to deploy Kontena with docker-compose: 
https://www.kontena.io/docs/getting-started/installing/docker-compose

Using these instructions it should be pretty easy for users to setup Kontena anywhere.

Feel free to re-open in case something is missing.
