### ISSUE TITLE
Etcd could not connect after first node is removed from the cluster

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#767]
I have a grid with initial_size=1. When I remove the first node  from the grid  etcd daemons on the remaining nodes fail to connect to the etcd cluster.

**Comment by jnummelin** [comment]
That is actually expected. When the grid initial-size is 1 only the first node run the etcd in member role. All the other nodes start in proxy mode. Now when you remove the first node you actually remove the whole etcd as you remove all member nodes.

We should probably document this more detailed how the initial-size effects the etcd clustering and what situations we can recover from.

**Comment by mtrofimm** [comment]
Thank for information. I was forced to remove the first node due to failure of Digital Ocean droplet after resizing in their control panel :(
I managed to workaround this issue by updating node_number in the host_nodes mongo collection.

**Comment by jnummelin** [comment]
So you "forced" some other node to take place of the first one?

**Comment by mtrofimm** [comment]
yes, and then recreated all kontena related containers on all nodes

**Comment by jnummelin** [comment]
cool workaround :)

I'll tag this as documentation as clearly there's some improvements needed on those regarding the etcd membership and caveats.

**Comment by mtrofimm** [comment]
@jnummelin what do you think about starting one etcd per grid at kontena master?

**Comment by jnummelin** [comment]
Single etcd would create rather fragile failure point for multiple grids and it would need to be clustered for HA which in turn would mean more resource needs for master etc.. It's a bit of a rabbit hole. :) Also it would mean that there should be a secure communication path from agent to masters etcd which again would require quite much tuning. Current way enables rather easy comms path from agent to master as it requires only one websocket. So I think moving etcd to master side does not really make sense and would create more issues/challenges than benefits.

**Comment by jakolehm** [comment]
Documentation improved in #776
