### ISSUE TITLE
Ability to define host ip in ports mapping

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#795]
I mean something like defined here:
https://docs.docker.com/compose/compose-file/#ports
i.e. exposing container port only on the given host interface/ip, for example for a corporate VPN.

**Comment by jnummelin** [comment]
Would you expect that when you specify ip address in port expose that Kontena is able to automatically schedule your service instance to correct node that has the specified ip?

**Comment by mtrofimm** [comment]
I think it would be difficult because in my case it's an external openvpn IP (legacy corporate network) where I want to expose my kontena service. This interface is not used in kontena node2node communication. I want to set exact affinity to the chosen node where the lb is to be deployed.
Maybe it would be enough if scheduler checked if the node had such ip on any interface.

**Comment by jnummelin** [comment]
In this case it would be difficult for the scheduler to know the correct node as scheduler (on the master) probably doesn't even know this particular VPN IP.
