### ISSUE TITLE
replace haproxy with traefik?

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#797]
the project look very promising: https://github.com/containous/traefik

What do you think?

**Comment by jakolehm** [comment]
Traefik does not support plain tcp. Otherwise it looks pretty cool and we have been following that project closely.

**Comment by jakolehm** [comment]
@mtrofimm what features are you missing from our haproxy based loadbalancer?

**Comment by mtrofimm** [comment]
Mostly letsencrypt, sticky sessions.

**Comment by jakolehm** [comment]
Added issue about sticky sessions: #799 . Letsencrypt is tracked in #704 .
