### ISSUE TITLE
Kontena 0.14.2 won't assign public IP when creating aws master

### ISSUE THREAD

**Issue by teroniemisto** [kontena/kontena#805]
When trying to create kontena master to aws using kontena client version 0.14.2, it won't assign public IP:

"Could not get public IP for the created master, private connect url is..."

Problem is solved when reverting back to 0.14.0 (not sure about 0.14.1).

**Comment by jnummelin** [comment]
This is a kind of regression in 0.14.1. You can use a flag called `--associate-public-ip-address` to enable public IP assignment during master or node creation. We will change the default of that flag to true in next release so it will behave like it used to.

**Comment by jakolehm** [comment]
Fixed in #808
