### ISSUE TITLE
How to achieve docker-compose's link = hostname behaviour?

### ISSUE THREAD

**Issue by suniala** [kontena/kontena#811]
I'm looking at how to utilise kontena in a dockerized project that is already in production. The use case is: in development, distribute containers between local and other hosts in order to free resources on local host (I have quite a lot of containers). In development, I use docker-compose. 

Now, I know I can use hostnames like `project_name_service_name.grid.kontena.local` with kontena but my existing configuration relies on short names that can be conveniently set with docker-compose links. For example `redis`. Links in kontena do not seem to create a DNS entry for the link name/alias.

Migrating everything on top of kontena is currently out of scope so my question is: is there any feasible way to get DNS lookup for a link name/alias working? If kontena links are not meant for this, are there any other viable solutions?

**Comment by jakolehm** [comment]
Link name/alias is not supported, but you can use short name when pointing to service (`project_name-service_name`). Usually it's good idea to pass these addresses as an environment variable to service container:

```
name: myproject
version: '2'
services:
  app:
    image: my/app:latest
    environment:
      - REDIS_HOST=%{project}-redis
```

**Comment by suniala** [comment]
Thanks! This does not solve my problem but on the other hand it verifies I understood the docs correctly and did not miss anything. Unfortunately this means I can't use kontena for this specific use case but I look forward to getting a change to try kontena in another project.
