### ISSUE TITLE
Request timeouts on long-running service container exec commands

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#823]
We run our master in Heroku which has a 30 second connection timeout, after that the connection is dropped. Running `kontena container exec` with a command that exceeds this time limit will error out in the following fashion:

```
$ kontena container exec my-api-1 sleep 40 && echo "Success!"
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

Could a solution be to return the request immediately and start tailing the container log (with the addition that exit codes needs to be handled properly)?

**Comment by SpComb** [comment]
#2271 would use a CLI-server websocket connection for the `exec` commands, which would probably also help with request timeouts for long-running execs?

**Comment by SpComb** [comment]
I'm guessing that this is no longer an issue with the websocket-based container execs in 1.3.
