### ISSUE TITLE
Service instance cannot start with too long instance name

### ISSUE THREAD

**Issue by janivihervas** [kontena/kontena#825]
Noticed this with a long project name running `kontena app deploy`: service with longer than 48 character name fails to start, so the instance name must be 50 characters or less. Creation and deployment runs fine, but the instance cannot start. I tested this also locally with Docker for Mac (client and server versions `1.12.0-rc2` and api versions `1.24`) and was able to run a container with arbitrary long container name. 

```
$ kontena version
cli: 0.14.3
master: 0.14.3
```

This fails:

```
$ kontena service create --grid dev 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49 kontena/lb:latest
$ kontena service deploy 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49
$ kontena service show 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49
dev/0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49:
  status: running
  image: kontena/lb:latest
  stateful: no
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
  dns: 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49.dev.kontena.local
  net: bridge
  instances:
    0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49-1:
...
      dns: 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxxx49-1.dev.kontena.local
...
      status: stopped
      reason: [8] System error: invalid argument
```

This works:

```
$ kontena service create --grid dev 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48 kontena/lb:latest
$ kontena service deploy 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48
$ kontena service show 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48
dev/0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48:
  status: running
  image: kontena/lb:latest
  stateful: no
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
  dns: 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48.dev.kontena.local
  net: bridge
  instances:
    0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48-1:
...
      dns: 0xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxxxxxx40xxxx48-1.dev.kontena.local
...
      status: running
```

**Comment by kke** [comment]
> According to RFC 1035 the length of a FQDN is limited to 255 characters, and each label (node delimited by a dot in the hostname) is limited to 63 characters, so in effect the limit you're after is 63.

The limit could be increased but not much to keep in line with the standards.

CLI should complain or refuse to deploy.

**Comment by jnummelin** [comment]
This seems to be the issue downstairs in docker: https://github.com/docker/docker/issues/21445

**Comment by matti** [comment]
Following stack won't deploy due to this:

```
stack: matti/kontena-mongodb-single
version: 0.0.1
description: Single MongoDB instance for Kontena Master

expose: mongodb

services:
  mongodb:
```

**Comment by matti** [comment]
okay so it seems that it's due to my extremely long grid name that makes "Domainname" to become long:

```
            "Hostname": "mongodb-1",
            "Domainname": "konte.lolmaster-mega-gcp-us-east1-masters.kontena.local",
```

**Comment by SpComb** [comment]
Confirmed, there seems to be a maximum limit of 64 bytes on the Docker container hostname + domain, so with a grid `development.kontena.local` domain, the maximum length service name that still works is `xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36`: `xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36-1.development.kontena.local` is exactly 64 bytes. A service called `xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37` fails to deploy, because it is 64 bytes long.


```
$ kontena service create xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36 redis
 [done] Creating xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36 service      
$ kontena service deploy xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36
 [done] Deploying service xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36      
⊛ Deployed instance development/null/xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36-1 to node core-01
$ kontena service create xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37 redis
 [done] Creating xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37 service      
$ kontena service deploy xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37
 [fail] Deploying service xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37      
 [error] 500 : halting deploy of development/null/xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37, one or more instances failed:
	⊗ Failed to deploy instance development/null/xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxxx37-1 to node core-01: GridServiceInstanceDeployer::ServiceError: Docker::Error::ServerError: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"invalid argument\\\"\"\n"
```

The resulting error from Docker is not very pretty.

**Comment by SpComb** [comment]
The stack name is also included in the limitation on the total DNS name length:

```yaml
stack: test/test-asdfasdfasdfasdf
services:
  xxxxxxxx10xx12:
    image: redis

  xxxxxxxx10xxx13:
    image: redis
    depends_on:
      - xxxxxxxx10xx12
```

```
 [done] Creating stack test-asdfasdfasdfasdf      
 [done] Triggering deployment of stack test-asdfasdfasdfasdf     
 [done] Waiting for deployment to start     
 [done] Deploying service xxxxxxxx10xx12     
 [fail] Deploying service xxxxxxxx10xxx13     
Deployment of service development/test-asdfasdfasdfasdf/xxxxxxxx10xxx13 failed:
  - halting deploy of development/test-asdfasdfasdfasdf/xxxxxxxx10xxx13, one or more instances failed
  - GridServiceInstanceDeployer::ServiceError: Docker::Error::ServerError: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"invalid argument\\\"\"\n" (on node core-01)
```

**Comment by SpComb** [comment]
> This seems to be the issue downstairs in docker: docker/docker#21445

That issue is about `{"Config": {"Hostname": "..."}}` longer than 63 chars... this seems to be about `$hostname.$domain` being limited to 64 chars, even though the plain hostname itself is well below the 63-char limit.

**Comment by SpComb** [comment]
Fundamentally this is happening because `docker-runc` is calling `sethostname` with the complete container FQDN, even when specifying a plain `Hostname` with a separate `Domainname`. This fails with `EINVALID` if the FQDN hostname is longer than `HOST_NAME_MAX`, which is 64 on Linux.

Very little we can do about this without breaking the DNS search domains... possibly docker/runc would need to be fixed to only use the plain `Hostname` for `sethostname`.

#### `container.json`
```
{
        "Image": "redis:latest",
        "Hostname": "xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36-1",
        "Domainname": "development2.kontena.local"
}
```

Created using `curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" -X POST http:/v1.22/containers/create -d @container.json` => `a447c7661138a`

#### `docker inspect -f '{{.Config.Hostname}}' a447c7661138a`
```
xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36-1
```
#### `docker inspect -f '{{.Config.Domainname}}' a447c7661138a`
```
development2.kontena.local
```

#### `curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" -X POST http:/v1.22/containers/a447c7661138a764da71a0ce7389e72afba1ef8f02f1bb373bf149595ce31e38/start`
```
oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"invalid argument\""
```

#### `strace -s 512 -f -p $(pidof containerd)`
```
14666 sethostname("xxxxxxxxx10xxxxxxxx20xxxxxxxx30xxx36-1.development2.kontena.local", 65) = -1 EINVAL (Invalid argument)
```

**Comment by matti** [comment]
How about warning user when grid name exceeds X? Maybe same logic for stack install etc.

Atleast kontena could detect that container name is too long and tell about it / refuse to start deploy?

**Comment by SpComb** [comment]
> Atleast kontena could detect that container name is too long and tell about it / refuse to start deploy?

Yes, that's what #2376 does, it raises a validation error on the service create/update before deploying.

> How about warning user when grid name exceeds X? Maybe same logic for stack install etc.

Perhaps... #2376 adds a note in the documentation that grid/stack names should be kept reasonably short. Dunno what the warning threshold would be.

@jnummelin  perhaps consider #2376 for 1.3.0?

**Comment by SpComb** [comment]
> Atleast kontena could detect that container name is too long and tell about it / refuse to start deploy?

Yes, that's what #2376 does, it raises a validation error on the service create/update before deploying.

> How about warning user when grid name exceeds X? Maybe same logic for stack install etc.

Perhaps... #2376 adds a note in the documentation that grid/stack names should be kept reasonably short. Dunno what the warning threshold would be.

@jnummelin  perhaps consider #2376 for 1.3.0?

**Comment by matti** [comment]
hit this again. named services with "func-run-UUID-UUID-UUID-UUID" and the resulting name was too long..

**Comment by jakolehm** [comment]
@SpComb what if we just pass `hostname` (without `domainname`) to docker engine?

**Comment by SpComb** [comment]
> @SpComb what if we just pass hostname (without domainname) to docker engine?

The concept of the Linux system `domainname` is very vauge, it's difficult to say offhand exactly what kind of effects that change would have... initial guess is that it could work to retain the current beavhior, assuming the DNS search domain is such that the plain hostname + DNS search domain resolves to an IP address that has a reverse-dns mapping with the correct domain - which should be the case with Weave DNS :)
