### ISSUE TITLE
Infinite re-scheduling of service instances

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#827]
```
$ kontena service list | grep builder
builder                                                      63 / 1     yes      deploying
```

> it seems that builder instance dies after ~5 minutes and Kontena will schedule new deploy for the service. Not sure why instances are not removed on Kontena master - @nevalla 

`service remove` & `service deploy` resolved the issue.

**Comment by jnummelin** [comment]
We haven't been able to reproduce this. My suspicion is that this has had something to do with missing notification from Docker which have been patched couple of times, latest in 0.15.3 release.

Let's re-open if this is seen again.
