### ISSUE TITLE
Occasionally unable to remove services

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#828]
We have occasionally bumped into the problem of not being able to remove services.
After a `service remove`, the service state is stuck in `deleting`. In some of the cases executing `remove` again will successfully remove the service. In other nothing happens and the state remains in `deleting`. It has taken hours for some of the services to be removed once stuck in that state.

**Comment by juhazi** [comment]
`

juhazi:kontena-localgyver/ (master) $ kontena service ls                                                                                                                                                                                                                                                                                                                                                                   [17:16:19]
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS
⊝ localgyver-registry                                        1 / 1      yes      running
⊝ localgyver-redis-sentinel-monitor                          5 / 5      yes      running
⊝ localgyver-redis-sentinel-node                             5 / 5      yes      running
⊝ localgyver-redis-sentinel-loadbalancer                     1 / 1      no       running
⊝ localgyver-postgres                                        0 / 1      yes      deleting   0.0.0.0:15432->5432/tcp
⊝ localgyver-loadbalancer                                    1 / 1      no       running    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:12222->12222/tcp
juhazi:kontena-localgyver/ (master) $ kontena service show localgyver-postgres                                                                                                                                                                                                                                                                                                                                             [17:16:24]
localgyver/localgyver-postgres:
  status: deleting
  image: postgres:9.5
  revision: 1
  stateful: yes
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
    wait_for_port: 5432
  dns: localgyver-postgres.localgyver.kontena.local
  net: bridge
  ports:
    - 15432:5432/tcp
  volumes:
    - localgyver-postgres:/var/lib/postgresql
  instances:
    localgyver-postgres-1:
      rev: 2016-09-01 14:07:17 UTC
      service_rev: 1
      node: moby
      dns: localgyver-postgres-1.localgyver.kontena.local
      ip: 10.81.1.173
      public ip: 185.11.211.158
      status: dead
juhazi:kontena-localgyver/ (master) $ kontena container show localgyver-postgres-1                                                                                                                                                                                                                                                                                                                                         [17:16:47]
ERROR: No such sub-command 'show'

See: 'kontena container --help'
juhazi:kontena-localgyver/ (master) $ kontena container inspect localgyver-postgres-1                                                                                                                                                                                                                                                                                                                                      [17:17:02]
{"code":500,"message":"Docker::Error::NotFoundError: No such container: 4efac48e99a7764d87f90b8a724c9317a721ee1270708b7901afdc70109be013\n","backtrace":["/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:46:in `rescue in request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in \u003cclass:Connection\u003e'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:284:in `get'","/app/lib/kontena/rpc/docker_container_api.rb:131:in `inspect'","/app/lib/kontena/rpc_server.rb:40:in `handle_request'","/app/lib/kontena/websocket_client.rb:108:in `block in on_message'","/usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'"]}
juhazi:kontena-localgyver/ (master) $ kontena service stop localgyver-postgres                                                                                                                                                                                                                                                                                                                                             [17:17:14]
juhazi:kontena-localgyver/ (master) $ kontena service ls                                                                                                                                                                                                                                                                                                                                                                   [17:17:32]
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS
⊝ localgyver-registry                                        1 / 1      yes      running
⊝ localgyver-redis-sentinel-monitor                          5 / 5      yes      running
⊝ localgyver-redis-sentinel-node                             5 / 5      yes      running
⊝ localgyver-redis-sentinel-loadbalancer                     1 / 1      no       running
⊝ localgyver-postgres                                        0 / 1      yes      stopped    0.0.0.0:15432->5432/tcp
⊝ localgyver-loadbalancer                                    1 / 1      no       running    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:12222->12222/tcp
juhazi:kontena-localgyver/ (master) $ kontena service show localgyver-postgres                                                                                                                                                                                                                                                                                                                                             [17:17:38]
localgyver/localgyver-postgres:
  status: stopped
  image: postgres:9.5
  revision: 1
  stateful: yes
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
    wait_for_port: 5432
  dns: localgyver-postgres.localgyver.kontena.local
  net: bridge
  ports:
    - 15432:5432/tcp
  volumes:
    - localgyver-postgres:/var/lib/postgresql
  instances:
    localgyver-postgres-1:
      rev: 2016-09-01 14:07:17 UTC
      service_rev: 1
      node: moby
      dns: localgyver-postgres-1.localgyver.kontena.local
      ip: 10.81.1.173
      public ip: 185.11.211.158
      status: dead
juhazi:kontena-localgyver/ (master) $ kontena container inspect localgyver-postgres-1                                                                                                                                                                                                                                                                                                                                      [17:17:49]
{"code":500,"message":"Docker::Error::NotFoundError: No such container: 4efac48e99a7764d87f90b8a724c9317a721ee1270708b7901afdc70109be013\n","backtrace":["/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:46:in `rescue in request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in \u003cclass:Connection\u003e'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:284:in `get'","/app/lib/kontena/rpc/docker_container_api.rb:131:in `inspect'","/app/lib/kontena/rpc_server.rb:40:in `handle_request'","/app/lib/kontena/websocket_client.rb:108:in `block in on_message'","/usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'"]}
juhazi:kontena-localgyver/ (master) $ kontena service rm localgyver-postgres                                                                                                                                                                                                                                                                                                                                               [17:17:56]
Destructive command. To proceed, type "localgyver-postgres" or re-run this command with --force option.
> ^C%                                                                                                                                                                                                                                                                                                                                                                                                                                 juhazi:kontena-localgyver/ (master) $ kontena service rm --force localgyver-postgres                                                                                                                                                                                                                                                                                                                                       [17:18:30]
juhazi:kontena-localgyver/ (master) $ kontena service show localgyver-postgres                                                                                                                                                                                                                                                                                                                                             [17:18:37]
localgyver/localgyver-postgres:
  status: deleting
  image: postgres:9.5
  revision: 1
  stateful: yes
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
    wait_for_port: 5432
  dns: localgyver-postgres.localgyver.kontena.local
  net: bridge
  ports:
    - 15432:5432/tcp
  volumes:
    - localgyver-postgres:/var/lib/postgresql
  instances:
    localgyver-postgres-1:
      rev: 2016-09-01 14:07:17 UTC
      service_rev: 1
      node: moby
      dns: localgyver-postgres-1.localgyver.kontena.local
      ip: 10.81.1.173
      public ip: 185.11.211.158
      status: dead
juhazi:kontena-localgyver/ (master) $ kontena container inspect localgyver-postgres-1                                                                                                                                                                                                                                                                                                                                      [17:18:42]
{"code":500,"message":"Docker::Error::NotFoundError: No such container: 4efac48e99a7764d87f90b8a724c9317a721ee1270708b7901afdc70109be013\n","backtrace":["/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:46:in `rescue in request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in \u003cclass:Connection\u003e'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:284:in `get'","/app/lib/kontena/rpc/docker_container_api.rb:131:in `inspect'","/app/lib/kontena/rpc_server.rb:40:in `handle_request'","/app/lib/kontena/websocket_client.rb:108:in `block in on_message'","/usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'"]}
juhazi:kontena-localgyver/ (master) $

`

**Comment by aleksijohansson** [comment]
I'm still having this same issue with 0.15.5

**Comment by jakolehm** [comment]
@aleksijohansson are you running kontena locally (for example with docker for mac)?

**Comment by aleksijohansson** [comment]
@jakolehm I've been testing with kontena vagrant based local master and nodes and also running master and a node locally on the host machine (macOS with Docker for Mac) with docker-compose. I've encountered this issue with both cases.

**Comment by aleksijohansson** [comment]
It seems that the running instance of the service is killed and removed, but the service stays in deleting state.

**Comment by matti** [comment]
Just got this in AWS: service was crashing constantly and 1/3 was left deleting even if I

a) stopped and deleted again
b) restarted all agents
c) rebooted all nodes

what helped: I deleted the service where the service was trying to connect (there was no linking, not sure how this would make any difference)

**Comment by matti** [comment]
...okaaaay: now the service is not listed in `kontena service ls`, but it's still running and outputting to `kontena grid logs`

**Comment by mattdavenport** [comment]
Can confirm this behavior with `kontena app rm --force` as well. Regarding @matti's comment on linking, if the services are linked it is impossible to delete them via CLI. Since the containers aren't running on the nodes (despite being listed as 'deleting'), I usually `docker exec -it kontena-server-mongo /bin/bash` in order to manually delete the records from mongoDB. This seems to have no adverse side effects on the next deploy.

**Comment by matti** [comment]
So to clarify: if a service is crashing on the start it's a) flooding grid logs with the exceptions b) stuck in deleting with `1/3` or `2/3` no matter how hard you try to stop/delete until something magical happens and kontena/docker is able to stop this loop.

**Comment by matti** [comment]
okay, seems like rebooting all nodes cleared the service now.

**Comment by aleksijohansson** [comment]
> if a service is crashing on the start it's a) flooding grid logs with the exceptions b) stuck in deleting with 1/3 or 2/3 no matter how hard you try to stop/delete until something magical happens and kontena/docker is able to stop this loop.

This is exactly how it happened for me.

**Comment by matti** [comment]
Yep, I can reproduce this 100%

**Comment by jnummelin** [comment]
So to reproduce this one would need a container image that just crashes on start (Docker keeps restarting) and now Kontena is not able to remove the service?

**Comment by matti** [comment]
Deploying this (3.2 causes infinite restarting) https://github.com/matti/kontena-mongodb32-bomb works as a 100% way to get this bug reproduced [as shown live to jnummelin a few minutes ago]

**Comment by jnummelin** [comment]
yep, I have couple of ideas that might cause this. Docker might not emit the events agent is expecting when removing restarting container. Or the container deletion might need some extra force on Docker API to remove restarting container. Or some combination of these. :)

Will reproduce locally and debug.

**Comment by jakolehm** [comment]
Some explanation why this happens: https://github.com/docker/docker/issues/26372

**Comment by mattdavenport** [comment]
It appears #1196 fixes this if you stop the service that is currently deploying before performing a `k app rm --force` or similar.

**Comment by mattdavenport** [comment]
An update: `kontena app rm --force` without performing `kontena app stop` is far more volatile. For some reason sending the stop signal then removing works, yet force removing without stopping doesn't. However it seem that this should be convention anyways to prevent any sort of corruption.

**Comment by matti** [comment]
Saw this with my Azure setup yesterday. `kontena app stop` + `kontena app rm --force` worked every time, without `stop` did not.

**Comment by panuhorsmalahti** [comment]
Happened for me today with Kontena 1.0.4. Seems to affect every service that I try to remove. Stopping works and I see that the containers are not running, but deleting is stuck indefinitely, and the services are left in 'deleting' state accroding to kontena service ls.
