### ISSUE TITLE
Community building, suggesting a book

### ISSUE THREAD

**Issue by omidfi** [kontena/kontena#844]
Hello, 
This is a free book by Pieter Hintjens, creator of zeroMQ. It has great practical guidelines for building online communities: 
https://www.gitbook.com/book/hintjens/social-architecture/details

Hope it helps building an awesome community around Kontena
Omid

**Comment by jnummelin** [comment]
Thanks for sharing this. I've browsed it through when you opened the issue and I think other Kontena members have do so also.

I'll close the issue as there's no direct actions to be taken.
