### ISSUE TITLE
service creation error

### ISSUE THREAD

**Issue by tamagokun** [kontena/kontena#847]
Trying to deploy an app. everything working dandy locally (`docker-compose up`).

When I deploy to kontena, it appears to deploy, but an instance is never created. Checking the grid logs, it seems there is a problem when trying to create the service.

```
Kontena::ServicePods::Creator: Docker::Error::ServerError: create .: volume name invalid: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
```

I'm assuming this is referring to a volumes line in docker-compose.yml, but even after removing that I am still seeing this problem.

Any help tracking this down much appreciated!

**Comment by nevalla** [comment]
What did you have in `volumes` options? After you removed volumes from YAML file, were they removed correctly from service config (`kontena app show <service>`)?

**Comment by tamagokun** [comment]
```yaml
volumes:
  - .:/code
```

I've noticed that just updating the config doesn't remove the directory from the service. So, I removed the service and re-added it. Worked like a charm.

Is there not a way to do host volumes in kontena?

**Comment by jnummelin** [comment]
The issue is the host dir, it must be absolute path as mentioned in Docker docs:
(https://docs.docker.com/engine/tutorials/dockervolumes/)

> The container-dir must always be an absolute path such as /src/docs. The host-dir can either be an absolute path or a name value. If you supply an absolute path for the host-dir, Docker bind-mounts to the path you specify. If you supply a name, Docker creates a named volume by that name.

**Comment by tamagokun** [comment]
the configuration is inside docker-compose.yml, and docker-compose states that you *can* use relative paths on the host.

**Comment by mtrofimm** [comment]
@tamagokun  my suggestion is to include code inside the docker image (ADD . /code in Dockefile) and use docker image versions for deploying changes in your kontena service.

**Comment by tamagokun** [comment]
That's exactly what I ended up doing. Thanks so much for the clarification!
