### ISSUE TITLE
Docs: host your own authentication service

### ISSUE THREAD

**Issue by patrick-jones** [kontena/kontena#852]
The quick start (and elsewhere) mentions that you can provide your own auth server.  It would be great to see some docs on how to do this.

**Comment by kke** [comment]
This is something we are currently working on and reinventing, the milestone is something like 0.16, meaning in a month or so and then it will be even easier to reimplement.

Currently you can use the ENV variable AUTH_API_URL on your master and cli to point to another auth provider, but the endpoints are not documented.

**Comment by nevalla** [comment]
Meanwhile you can check this self-hosted auth server: https://github.com/jnummelin/kontena-local-auth

**Comment by matti** [comment]
I don't think that `kontena-local-auth` works anymore, it's missing auth for grid or something.

**Comment by jakolehm** [comment]
0.16 will support standard OAuth2 authentication services: https://github.com/kontena/kontena/blob/master/docs/using-kontena/authentication.md
