### ISSUE TITLE
CLI: requires ~/.kontena_client.json when ENV's are set

### ISSUE THREAD

**Issue by matti** [kontena/kontena#857]
This used to work previously, now code reads something from settings and fails.

```
$ mv ~/.kontena_client.json ~/.kontena_client.notjson
$ KONTENA_GRID=gridname KONTENA_TOKEN=kontena-BASE64ABBACD== KONTENA_URL=https://kontena-master.kontena.com kontena whoami
It seem's that you are not logged into ANY Kontena master, please login with: kontena login
```

**Comment by kke** [comment]
The `whoami` command seems to display information about the current master from the config. Is this an issue with other commands?

**Comment by matti** [comment]
You're right. Most of the commands work, but `kontena grid show gridname`does not work either.

**Comment by kke** [comment]
Fixed that one too. There may be others.
