### ISSUE TITLE
Switch coreos to use cgroupfs cgroup driver

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#861]
Systemd driver is causing too many problems currently, for example docker/cadvisor cannot get stats.

See: https://github.com/coreos/bugs/issues/1435

**Comment by jnummelin** [comment]
This needs to be handled within all the upcoming plugins:
- [ ] AWS
- [ ] Azure
- [ ] Packet
- [ ] Vagrant
- [ ] DigitalOcean
- [ ] Upcloud

**Comment by jnummelin** [comment]
All plugins should be now updated! :)

**Comment by jakolehm** [comment]
Nice!
