### ISSUE TITLE
Health check uri is misleading

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#866]
Health check uri is not actual uri, it's actually http request path. I think we should change naming.

/cc @miskun

**Comment by jnummelin** [comment]
[nitpicking]
To be precise it's an URI reference, at least according to my interpretation of: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
[/nitpicking]

I chose the term as it is used in HAProxy configs also as URI: http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#option%20httpchk

I would keep as it is as URI term is pretty commonly used also in this kind of "partial" URI way. If others think path would be more proper I'm good with that also as it is also technically correct. :)

**Comment by jakolehm** [comment]
Ok, understood :) I just somehow thought URI as "full" URL (not just the path part) and set that as health check. Maybe this is just an user error?
