### ISSUE TITLE
CLI: timeout to master is 60 seconds, makes all commands (including kontena version) hang if no master is available

### ISSUE THREAD

**Issue by matti** [kontena/kontena#874]
`~/.kontena_client.json:`

```
{
  "current_server": "default",
  "servers": [
    {
    },
    {
      "name": "default",
      "url": "http://kontena-master.example.com",
```

all commands like `kontena service ls` will just hang. CLI should fail faster.

**Comment by jnummelin** [comment]
The default `connect_timeout` used in the underlying HTTP library (Excon) is 60 seconds. IMO we could lower that a bit. Maybe even to 20secs, if we don't get HTTP connection to master within 20 secs things are anyway going pretty south. :)

**Comment by jnummelin** [comment]
Closing this as the timeouts are now configurable and the default connect timeout is now 5 secs. https://github.com/kontena/kontena/blob/master/cli/lib/kontena/client.rb#L59
