### ISSUE TITLE
Master high availability

### ISSUE THREAD

**Issue by bseng** [kontena/kontena#876]
Hi,

I'm trying to find information on master high availability but I can't find any.

So what happens if master is down? Will one of the nodes get promoted?

and if master is down will apps continue to work on nodes?

thanks.

**Comment by nevalla** [comment]
Hi,

If master is down, nodes are still working and all the services fully operational. Only new log and stat entries are not available. Also new deploys are not possible.

To gain HA for master setup we recommend to create MongoDB replica set and setup multiple instances of kontena masters.

This is a question that many have asked, so we need to update our documentation regarding this and provide some example how to setup HA Kontena Master.

**Comment by bseng** [comment]
Hopefully you can extend `kontena master create` to specify how many master servers you want.

**Comment by SpComb** [comment]
See #948 re master HA documentation
