### ISSUE TITLE
Cannot create vagrant master after first attempt failed

### ISSUE THREAD

**Issue by ronkot** [kontena/kontena#879]
I tried to follow the quick start guide. All went smoothly until the `kontena master vagrant create` command failed due to network errors (propably). `kontena master ls` shows that no master was created but trying to run command again gives an error `Oops... cannot create Kontena Master! You can run only one Kontena Master with Vagrant`. How can i get back to clean initial state?

    14:14 $ kontena master vagrant create
    Creating Vagrant machine kontena-master-sparkling-haze-90 ... -An error occurred while downloading the remote file. The error
    message, if any, is reproduced below. Please fix this error and try
    again.

    transfer closed with 286653149 bytes remaining to read
    done
    Waiting for kontena-master-sparkling-haze-90 to start ... |^Cfail  # Ctrl + C due hang here

    14:24 $ kontena master vagrant create
    Oops... cannot create Kontena Master! You can run only one Kontena Master with Vagrant

**Comment by sahvenni** [comment]
Please do:  

$ rm -rf ~/.kontena/vagrant_master/  

and then recreate the master.

**Comment by ronkot** [comment]
Okay, that did it. Thanks!
