### ISSUE TITLE
Master installation support for OAuth2

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#887]
Master needs oauth2 application id/secret and maybe some other configuration parameters.

**Comment by kke** [comment]
For generic oauth2 that will require several api endpoint paths and maybe auth request payload templating. For preconfigured providers you need provider name + client_id + client_secret.

**Comment by kke** [comment]
Also include setting master FQDN when provisioning

**Comment by jakolehm** [comment]
Installation should create local "initial" master admin user that is not related to any authentication provider. This user can thought as a "root" for master installation.

**Comment by kke** [comment]
Implemented in #891

**Comment by kke** [comment]
Implemented in #931

**Comment by jakolehm** [comment]
Implemented in #1035
