### ISSUE TITLE
Updating master SSL cert

### ISSUE THREAD

**Issue by adrianchifor** [kontena/kontena#912]
Once I've created a master server (DigitalOcean CoreOS) with an SSL cert (Let's Encrypt), how can I update the certificate on the server when the initial one expires?

**Comment by mudspot** [comment]
I have met this same issue.

I tried replacing /etc/kontena-server.pem

But after rebooting, the original Kontena-server.pem got restored.

My Kontena master was created on AWS with the "kontena master create " command

**Comment by SpComb** [comment]
The `/etc/kontena-server.pem` is provisioned via the user-data cloud-config. The cloud-config gets re-applied at every boot, so it will restore the original cert.

You either need to update the cloud-config in the AWS EC2 instance user-data, or write it out as a new file (`/etc/kontena-server-2.pem` or whatever), and use the `/etc/kontena-server.local.env` to point `SSL_CERT=/etc/kontena-server-2.pem` at that non-cloudconfig'd file.

**Comment by mudspot** [comment]
Works perfect!!

I used the second method.
I put it into `/etc/kontena-server.custom.env` (where I have also defined my KONTENA_VERSION

**Comment by jnummelin** [comment]
> Works perfect!!
closing as solved. :)
