### ISSUE TITLE
CLI support for updated master authentication

### ISSUE THREAD

**Issue by kke** [kontena/kontena#932]
The CLI needs changes for it to work with the master oauth2 improvements in PR #931.

**Comment by kke** [comment]
Needed two (preferably self contained single file) html's that say:

1:
> Success, you can now close this window or tab and return to the terminal

2:

>To complete the authentication enter this command: `kontena master auth --code <script>document.write(window.location.hash.split('code=')[1]));</script> <script>document.write(window.location.origin);</script>`

PING @miskun

**Comment by jakolehm** [comment]
Implemented in #1035
