### ISSUE TITLE
restart failed containers

### ISSUE THREAD

**Issue by digitalism** [kontena/kontena#94]
When I start a kontena service with:

```
kontena service create ghost-blog ghost:0.5 --stateful -p 8181:2368 
kontena service deploy ghost-blog
```

it correctly starts a docker container on `node1`.

But when I stop the docker container on `node1` using

```
docker stop ghost-blog-1
```

I expected kontena to restart the container and keep the service running.

Kontena seems to immediately recognize that the container is stopped, but does not restart it.

```
$ kontena service show ghost-blog
first-grid/ghost-blog:
  status: running
  stateful: yes
  scaling: 1
  image: ghost:0.5
  cmd: -
  env: 
  ports:
    - 8181:2368/tcp
  links: 
  containers:
    ghost-blog-1:
      rev: 2015-07-27 11:42:11 UTC
      node: node1
      dns: ghost-blog-1.kontena.local
      ip: 
      public ip: xxx.xxx.xxx.xxx
      status: stopped
```

Do you plan to support automatic restart of failed containers?

**Comment by jakolehm** [comment]
Yes we support automatic restart of failed containers. If you issue `stop` command, docker does not translate that to failure because you (as an administrator) issued a stop. If container fails without interaction then it's restarted automatically.

You can try it out by killing the process on `node1`.

**Comment by digitalism** [comment]
I tried again with `docker kill ghost-blog-1`, but the service does not get restarted.

`docker kill` should send `SIGKILL` to the process, as shown here:

```
$ docker kill --help

Usage: docker kill [OPTIONS] CONTAINER [CONTAINER...]

Kill a running container using SIGKILL or a specified signal

  --help=false         Print usage
  -s, --signal=KILL    Signal to send to the container
```

Again, container status is `stopped` and service status is `running`.

**Comment by jakolehm** [comment]
Yes, this is expected behaviour. Try again so that you find pid and just kill it directly from host without docker tooling, `sudo kill -9 <pid>` .

**Comment by digitalism** [comment]
Ok, if I get the pid of the container with `docker inspect --format '{{.State.Pid}}, {{.ID}}' ghost-blog-1` and then kill this process with `kill -9 <pid>`, the process gets restarted. Thanks for your support!
