### ISSUE TITLE
Certificates not trusted by all client software

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#943]
There are some client software (wget, some Rubies, Docker, ...) that doesn't seem to trust the LE issued certificates if they are used as standalone. All browsers seem to trust LE intermediaries directly. Instead we should provide option for user to use fullchain certificates so that the whole trust chain can be established. Maybe the best option is to by default use fullchain certificates and if user opts for plain certificate use that.

**Comment by matti** [comment]
let's encrypt is especially great for SSLing kontena registry with the kontena loadbalancer in less than 20 seconds. This usecase doesn't work right now (docker push fails).

**Comment by jnummelin** [comment]
fixed in #946
