### ISSUE TITLE
Add Kontena HA-setup documentation

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#948]
Documentation is needed how to setup high available Kontena Master.

**Comment by dennschu** [comment]
Or as a starting point a How To for backing up and restoring a Kontena Master, when it gets lost during a failure

**Comment by SpComb** [comment]
AFAIK

* Run a mongodb replica set
* Run multiple instances of kontena-server
* Configure each kontena-server to use the same mongodb replset
* For each kontena-agent, `KONTENA_URI=wss://...` connections should be distributed across multiple kontena-server instances (DNS round-robin, haproxy load balancer?)
* For the kontena-cli, either use a load-balanced `kontena master login ... https://...` URL, or configure multiple kontena masters and manually select which one to use?

* Both kontena-server instances need matching `VAULT_KEY` and `VAULT_IV` etc configuration envs, or the vault and login tokens etc will not work.
* The kontena-server instances will use the shared mongo replset to manage service state/deployments and accept CLI requests / forward agent RPCs on commands.
* The kontena-server instances will use mongodb to elect a leader to coordinate tasks such as rebalancing services, handling the kontena-cloud communcation etc.

**Comment by jakolehm** [comment]
There is also an alternative way... provision ha-master to a grid using kontena cli. I think this will be the easiest way for many, although user needs to sacrifice one machine for the initial (non-ha) master that orchestrates the first grid. Using this method installation of ha-setup should be as easy as:

`$ kontena stack install --deploy kontena/master`
