### ISSUE TITLE
Failed hosts are note detected

### ISSUE THREAD

**Issue by digitalism** [kontena/kontena#95]
Assume I start two nodes:

```
$ kontena node list
Name                           OS                                       Driver          Labels                         Status    
node1                          CoreOS 717.3.0 (4.0.5)                   overlay         -                              online    
node2                          CoreOS 717.3.0 (4.0.5)                   overlay         -                              online    
```

If I completely stop the machine `node2`, I expect the status to change from `online` to `offline`. However, the status is not updated.

Furthermore, if there were any services running on `node2`, I expect them to be restarted on `node1` which also does not happen.

Do you have any plans to fix/implement this behavior?

**Comment by jakolehm** [comment]
Status should update immediately when `node2` is stopped (master does get that status from websocket connection close). I'm interested about that `node list` output, are you really running kontena on coreos or is that just example output?

Service migration/balancing on node add/remove is coming soon. At first it will only support stateless containers because we don't have any means to migrate data from offline nodes.

**Comment by digitalism** [comment]
Tried this again. Again, I started two coreos machines and both show up on `kontena node list`. Then, I terminated one of the virtual machines. The websocket close does not seem to get detected.

Service migration: Good to hear you going to add this.

Core OS: yes, this was tested on coreos and rackspace. For my own reference, I wrote down the commands I used to set things up. I'll add them here:

```
master (on node1)
------------------

wget https://github.com/kontena/kontena/archive/master.zip
unzip master.zip 
mv kontena-master kontena
cd kontena/server
mv Dockerfile.alpine Dockerfile

curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > docker-compose
chmod +x docker-compose
./docker-compose up

create grid (on local machine)
----------------------------

gem install kontena-cli
kontena register
kontena login http://NODE1-IP:4040
kontena node list
kontena grid list
kontena grid create first-grid --initial-size=1
kontena grid current

agent (on node1 and node2)
-----------------------------

wget https://github.com/kontena/kontena/archive/master.zip
unzip master.zip 
mv kontena-master kontena
cd kontena/agent/
mv Dockerfile.alpine Dockerfile

mv .env.example .env
vi .env
-> set ip in KONTENA_URI
-> set kontena token to token from `kontena grid show first-grid`

curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > docker-compose
chmod +x docker-compose
./docker-compose up

create service (on local machine)
-------------------------------

kontena service create ghost-blog ghost:0.5 --stateful -p 8181:2368 
kontena service deploy ghost-blog 
```

**Comment by jakolehm** [comment]
It seems that terminated websocket is detected but it takes a while until master notices this (maybe when next ping happens). If agent is shutdown gracefully then master notices it right away.We can't really do much about this because we don't get any event from socket when agent terminates it forcefully.

**Comment by jakolehm** [comment]
@digitalism, coreos is now officially supported platform. See installation docs for more details.

**Comment by jakolehm** [comment]
Let's reopen this, there must be something we can do to detect this situation.

**Comment by four43** [comment]
#167 may be a duplicate of this. I re-reported it since I had a slightly different circumstance and this one was closed.
