### ISSUE TITLE
configurable.rb:83:in `setting': unknown keywords: sanitizer, json, form (ArgumentError)

### ISSUE THREAD

**Issue by nomadcanuck** [kontena/kontena#950]
Execute the following commands in iTerm2 build 3.0.2 terminal window on OS X El Capitan 10.11.6:

`ruby -v`
> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

`gem install kontena-cli`
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

`brew install ruby`
`exit`
`CMD+q`
`restarted iTerm2`

`ruby -v`
> ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

`gem install kontena-cli`
> Fetching: kontena-cli-0.15.0.gem (100%)
> Successfully installed kontena-cli-0.15.0
> Parsing documentation for kontena-cli-0.15.0
> Installing ri documentation for kontena-cli-0.15.0
> Done installing documentation for kontena-cli after 1 seconds
> 1 gem installed

added to .bashrc
`which kontena > /dev/null && . "$( kontena whoami --bash-completion-path )"`

`exit`
`CMD+q`
`restarted iTerm2`
`kontena -v`
> /usr/local/lib/ruby/gems/2.3.0/gems/dry-configurable-0.2.0/lib/dry/configurable.rb:83:in `setting': unknown keywords: sanitizer, json, form (ArgumentError)
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry/validation/schema.rb:40:in `<class:Schema>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry/validation/schema.rb:20:in `<module:Validation>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry/validation/schema.rb:19:in `<module:Dry>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry/validation/schema.rb:18:in `<top (required)>'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry/validation.rb:5:in `<top (required)>'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/dry-validation-0.8.0/lib/dry-validation.rb:1:in `<top (required)>'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/yaml/validator.rb:1:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/yaml/reader.rb:3:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/yaml/reader.rb:3:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/common.rb:5:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/common.rb:5:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/init_command.rb:2:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/apps/init_command.rb:2:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/app_command.rb:1:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/cli/app_command.rb:1:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/main_command.rb:7:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena/main_command.rb:7:in `<top (required)>'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena_cli.rb:6:in `require_relative'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/lib/kontena_cli.rb:6:in `<top (required)>'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>        	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.15.0/bin/kontena:11:in `<top (required)>'
>        	from /usr/local/bin/kontena:23:in `load'
>        	from /usr/local/bin/kontena:23:in `<main>'
>

**Comment by SpComb** [comment]
See #949, dry-configurable 2.0.0 broke things: https://github.com/dry-rb/dry-configurable/issues/12

The workaround is to downgrade to dry-configurable 1.6.0.

**Comment by jakolehm** [comment]
Fixed in 0.15.1
