### ISSUE TITLE
CLI: interactive TTY support

### ISSUE THREAD

**Issue by matti** [kontena/kontena#961]
Currently `$ kontena container exec redis-1 passwd` or `$ kontena container exec railsapp rails console` will just hang.

There should be a `$ kontena container tty redis-1 passwd` command that runs `docker exec -ti` in the agent where `redis-1` is being deployed and streams the stdout and stdin to/from the CLI.

**Comment by bompi88** [comment]
+1 I cannot figure out how to inspect my database easily without an interactive TTY.

**Comment by jakolehm** [comment]
@bompi88 you can always use kontena vpn (openvpn) to access you database. Not the same thing as an interactive TTY but usually works fine :)

**Comment by bompi88** [comment]
@jakolehm thanks. This worked perfectly.

**Comment by kke** [comment]
There's service exec now but can it run interactively? @SpComb ?

**Comment by SpComb** [comment]
No. Interactive exec would require a lot of support from both the server API and agent RPC implementations.
