### ISSUE TITLE
tailing service logs - memory consumption

### ISSUE THREAD

**Issue by dishcandanty** [kontena/kontena#963]
When I run:

`kontena service logs -t fancyname`

The CLI immediately begins to eat memory, eventually crashing. During the times that ive had issues there's been no output happening on the service.

![memoryabused](https://cloud.githubusercontent.com/assets/2327777/18212413/6c2f8bd4-7100-11e6-991c-ff59b3076189.png)
 

Version: kontena-cli (0.15.1)

**Comment by matti** [comment]
we are also seeing this. currently workarounding by running kontena log archiver flushing logs to disk and then tailing that..

**Comment by jakolehm** [comment]
Which ruby/operating system are you using?

**Comment by matti** [comment]
el cap osx 2.3.1 here

**Comment by christofferh** [comment]
I'm still seeing this:

```
$ bontena version
cli: 0.16.0.pre6
$ bontena service logs -t loadbalancer
$ ps x -o rss,command | grep bontena
28756 ruby /usr/local/bin/bontena service logs -t loadbalancer
.. ~10 min
$ ps x -o rss,command | grep bontena
513696 ruby /usr/local/bin/bontena service logs -t loadbalancer
```

Requesting a GC run with `GC.start` results in the memory to drop to the initial size.

**Comment by matti** [comment]
@jakolehm reopen..?
