### ISSUE TITLE
CLI: support --master like --grid is supported

### ISSUE THREAD

**Issue by matti** [kontena/kontena#970]
Currently it's not possible to use multiple master at the same time (for example with two terminal windows where another terminal window is running bunch of commands in one master+grid)

If this is wanted, I could give a try at creating a PR?

**Comment by kke** [comment]
There's some changes coming to env + config handling pretty soon, probably not worth the effort to implement it to the current version.

Easiest would probably be something like setting env KONTENA_MASTER=master_name to override the current master in config.

**Comment by matti** [comment]
That's actually even better. Is it worth doing a PR of that (will that be deprecated in the near future as well?)

**Comment by kke** [comment]
I made the change already to the new code which is part of 0.16.0.

It needs to be documented and all the other possible env variables also. I'll make a PR for that.

**Comment by matti** [comment]
:beer: deserved

**Comment by jnummelin** [comment]
Closing as this is now implemented and for docs updates there's another issue.
