### ISSUE TITLE
docs should give pasteable commands to install prerequirements

### ISSUE THREAD

**Issue by matti** [kontena/kontena#979]
A new kontena user simply can not know what version to of the docker-engine: https://kontena.io/docs/getting-started/installing/ubuntu#prerequisities

**Comment by matti** [comment]
or just a list of which version of docker etc is supported would be a start

**Comment by matti** [comment]
(1.11.2 currently)

**Comment by matti** [comment]
(actually 1.10.x)

**Comment by jakolehm** [comment]
https://github.com/kontena/kontena/pull/1144
